### ISSUE TITLE
variant="outlined" 没有用

### ISSUE THREAD

**Issue by UzeG** [varletjs/varlet#1003]
# Bug report 🐞
我想要使用 var-input 的边框样式，设置了 variant="outlined" 但是没有效果。甚至在本地直接copy官网的示例代码都始终无法正确显示为带边框的输入框样式。
## Version & Environment
"@varlet/ui": "^2.9.6"
"vue": "^3.2.47"

**Comment by a145789** [comment]
请尝试将 varlet 版本升级至 [2.10.0](https://github.com/varletjs/varlet/blob/dev/CHANGELOG.md#features)

**Comment by UzeG** [comment]
按照你说的我更新到了2.10.0，但是variant设置依旧没有用，始终为默认的standard样式

**Comment by a145789** [comment]
可以提供一个最小的复现 repo 么？我建了一个新项目，使用2.10.0版本
```
  "dependencies": {
    "@unocss/reset": "^0.48.5",
    "@varlet/ui": "^2.10.0",
    "pinia": "^2.0.35",
    "vue": "^3.2.47",
    "vue-router": "^4.1.6"
  },
```
```html
 <var-input variant="outlined" placeholder="你好"></var-input>
```

是有 outlined 样式的
