### ISSUE TITLE
Datepicker日期选择器报错

### ISSUE THREAD

**Issue by hxyvipno1** [varletjs/varlet#1009]
# Bug report 🐞

## Version & Environment
2.9.6 生产环境
## Expectation
点击日期，能选日期
## Actual results (or Errors)
点击报错
![image](https://user-images.githubusercontent.com/30286403/236151532-171b7928-da25-47f5-8c98-96f07e1d455b.png)

**Comment by BeADre** [comment]
升级最新版本

**Comment by BeADre** [comment]
我不能复现你的问题 你用的vite吗？ 清理下缓存试试
