### ISSUE TITLE
ImagePreview在iphone的safari浏览器里关闭按钮进了顶部安全区

### ISSUE THREAD

**Issue by Gilfoylex** [varletjs/varlet#1012]
# Bug report 🐞

![微信图片_20230505164439](https://user-images.githubusercontent.com/15212559/236414502-46f27624-fb3d-4de6-b2f7-a27d0fb3f424.jpg)
![微信图片_20230505164448](https://user-images.githubusercontent.com/15212559/236414516-d37890ff-0c34-4fd1-b385-bb657fbddf4d.jpg)

`<meta name="viewport"
    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, viewport-fit=content" />`
index.html的 viewport-fit=content，按理说网页内容不会进入安全区，但是竖屏和横屏一对比发现确实进了安全区了，给 var-popup设置一个padding-top 才能正确显示出来。

**Comment by haoziqaq** [comment]
好的，我们会在之后的版本给遮罩相关的组件，加入顶部和底部的安全区适配 api。

**Comment by haoziqaq** [comment]
@Gilfoylex 请尝试 viewport-fit=cover

**Comment by Gilfoylex** [comment]
> @Gilfoylex 请尝试 viewport-fit=cover
理论上是可以，但是用了viewport-fit=cover 配合css 的padding-top: env(safe-area-inset-top) 也没什么用，还是没法正常显示关闭按钮

**Comment by haoziqaq** [comment]
升级到 @varlet/ui@2.10.2-alpha.1683285148722，应该能够解决。
