### ISSUE TITLE
bug about imagePreview 

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1020]
# Bug report 🐞

- occasionally flashing when switching
- resulting in page numbers not visible due to height exceeding

## Version & Environment

"@varlet/ui": "^2.10.2",
"vue": "^3.2.47"

## Actual results (or Errors)

When I switch images, occasionally there is a scene where half of the page is blank, and the height of the page exceeds 100%, resulting in the page being scrollable and the top page numbers not being fully visible

**Comment by haoziqaq** [comment]
Could you please provide a reproduction？

**Comment by haoziqaq** [comment]
I reproduced your problem. When I swipe very frequently.
