### ISSUE TITLE
All components replaced with latest API

### ISSUE THREAD

**Issue by tiny-dust** [varletjs/varlet#1022]
- [ ] replace `getBoundingClientRect` with `getRect`
- [ ] replace `getComputedStyle` with `getStyle`

refer to this [commit](https://github.com/varletjs/varlet/commit/e8897050178578e9372b6d15abda828c54feed69)

**Comment by gaoting** [comment]
https://github.com/varletjs/varlet/issues/1023
ripple已改完。测试已通过
<img width="776" alt="image" src="https://github.com/varletjs/varlet/assets/7401170/b3d90a6a-03d1-4914-b51d-7b3a4856c621">

**Comment by gaoting** [comment]
https://github.com/varletjs/varlet/issues/1026
card已改完。测试已通过
<img width="683" alt="image" src="https://github.com/varletjs/varlet/assets/7401170/e15a2e53-1aee-498c-a9f7-f6b28aad6a2d">

**Comment by gaoting** [comment]
https://github.com/varletjs/varlet/issues/1027
menu已改完。测试已通过
<img width="686" alt="image" src="https://github.com/varletjs/varlet/assets/7401170/df185e4e-354c-45ba-9d88-825d50254903">

**Comment by gaoting** [comment]
https://github.com/varletjs/varlet/issues/1030
utils 已改完。测试已通过
<img width="1301" alt="image" src="https://github.com/varletjs/varlet/assets/7401170/0fad6c0e-def6-497a-937d-d0c4f761bf3b">
