### ISSUE TITLE
折叠面板collapse 中的内容区域不支持SSR?

### ISSUE THREAD

**Issue by AnyFork** [varletjs/varlet#1024]
# Bug report 🐞
折叠面板collapse 中的内容区域不支持SSR
## Version & Environment
    "@varlet/ui": "2.10.3-alpha.1683532936621",

**Comment by BeADre** [comment]
没能复现你的问题
![image](https://github.com/varletjs/varlet/assets/34639100/9b98f24f-c88d-4b75-8598-446e10a464dc)

**Comment by AnyFork** [comment]
![image](https://github.com/varletjs/varlet/assets/49142023/20ddd9a3-b357-47e3-885e-4677dbfc54ae)
"@varlet/ui": "2.10.3-alpha.1683532936621",
这个版本号，发现折叠面板和tab-item都不行

**Comment by BeADre** [comment]
preview是是结合css渲染的结果 你应该看response

**Comment by AnyFork** [comment]
preview tab-item也没内容

**Comment by BeADre** [comment]
tab-item的已经[改了](https://github.com/varletjs/varlet/commit/8b6245e73631003f5e4067b7d964ab8fc166c2af), collapse应该是没问题的

**Comment by AnyFork** [comment]
已测试，ok了
