### ISSUE TITLE
当时用radioGroup组件时，报"window is not defined"

### ISSUE THREAD

**Issue by AnyFork** [varletjs/varlet#1045]
# Bug report 🐞
当时用radioGroup组件时，报"window is not defined"，好像不支持SSR，用ClientOnly组件包装，可以正常使用。
## Version & Environment
  "@varlet/ui": "^2.11.0"
## Expectation
```
500
window is not defined

at Proxy.toSizeUnit (./node_modules/@varlet/ui/es/utils/elements.mjs:235:10)
at Proxy.__render__ (./node_modules/@varlet/ui/es/icon/Icon.mjs:30:22)
at renderComponentRoot (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:812:16)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:700:28)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:631:12)
at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:743:14)
at renderVNodeChildren (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:759:5)
at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:731:7)
at renderVNodeChildren (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:759:5)
```

## Actual results (or Errors)
demo地址：https://stackblitz.com/edit/github-yd1x3p?file=package.json,nuxt.config.ts,app.vue

**Comment by haoziqaq** [comment]
好的，我们验证一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月19日(周五) 上午10:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 当时用radioGroup组件时，报"window is not defined" (Issue #1045)




 
Bug report 🐞
 
当时用radioGroup组件时，报"window is not defined"，好像不支持SSR，用ClientOnly组件包装，可以正常使用。
 
Version &amp; Environment
 
***@***.***/ui": "^2.11.0"
 
Expectation
 500 window is not defined at Proxy.toSizeUnit ***@***.***/ui/es/utils/elements.mjs:235:10) at Proxy.__render__ ***@***.***/ui/es/icon/Icon.mjs:30:22) at renderComponentRoot ***@***.***/runtime-core/dist/runtime-core.cjs.js:812:16) at renderComponentSubTree ***@***.***/server-renderer/dist/server-renderer.cjs.js:700:28) at renderComponentVNode ***@***.***/server-renderer/dist/server-renderer.cjs.js:631:12) at renderVNode ***@***.***/server-renderer/dist/server-renderer.cjs.js:743:14) at renderVNodeChildren ***@***.***/server-renderer/dist/server-renderer.cjs.js:759:5) at renderVNode ***@***.***/server-renderer/dist/server-renderer.cjs.js:731:7) at renderVNodeChildren ***@***.***/server-renderer/dist/server-renderer.cjs.js:759:5)  
Actual results (or Errors)
 
demo地址：https://stackblitz.com/edit/github-yd1x3p?file=package.json,nuxt.config.ts,app.vue

**Comment by zhangkejian0** [comment]
> 好的，我们验证一下。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月19日(周五) 上午10:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [varletjs/varlet] 当时用radioGroup组件时，报"window is not defined" (Issue #1045) Bug report 🐞 当时用radioGroup组件时，报"window is not defined"，好像不支持SSR，用ClientOnly组件包装，可以正常使用。 Version &amp; Environment ***@***.***/ui": "^2.11.0" Expectation 500 window is not defined at Proxy.toSizeUnit ***@***.***/ui/es/utils/elements.mjs:235:10) at Proxy.__render__ ***@***.***/ui/es/icon/Icon.mjs:30:22) at renderComponentRoot ***@***.***/runtime-core/dist/runtime-core.cjs.js:812:16) at renderComponentSubTree ***@***.***/server-renderer/dist/server-renderer.cjs.js:700:28) at renderComponentVNode ***@***.***/server-renderer/dist/server-renderer.cjs.js:631:12) at renderVNode ***@***.***/server-renderer/dist/server-renderer.cjs.js:743:14) at renderVNodeChildren ***@***.***/server-renderer/dist/server-renderer.cjs.js:759:5) at renderVNode ***@***.***/server-renderer/dist/server-renderer.cjs.js:731:7) at renderVNodeChildren ***@***.***/server-renderer/dist/server-renderer.cjs.js:759:5) Actual results (or Errors) demo地址：https://stackblitz.com/edit/github-yd1x3p?file=package.json,nuxt.config.ts,app.vue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

类似问题，<var-swipe />有相同问题

**Comment by zhangkejian0** [comment]
var-swipe  组件有相同问题，不支持ssr

**Comment by haoziqaq** [comment]
@AnyFork @varlet/ui@2.11.1-alpha.1684493331817 尝试升级一下，看看问题有没有得到解决。

**Comment by AnyFork** [comment]
> @AnyFork @varlet/ui@2.11.1-alpha.1684493331817 尝试升级一下，看看问题有没有得到解决。

已解决
