### ISSUE TITLE
更新一下字体图标库，兄弟

### ISSUE THREAD

**Issue by 4zzzzr** [varletjs/varlet#1050]
https://varlet.gitee.io/varlet-ui/#/zh-CN/icon

**Comment by haoziqaq** [comment]
![image](https://github.com/varletjs/varlet/assets/24223652/af41968c-bcda-41a3-8aba-100d9600dd98)


自定义你需要的，或者 pr 到官方图标库（前提是图标足够通用）。

是群里的兄弟吧？

**Comment by CNChestnut** [comment]
我觉得他只是想说更新默认的 Material Design Icon 图标库，比如 `save` `download` 等等图标都没有。

**Comment by haoziqaq** [comment]
官方的图标库不适合内置太多的图标，非常常用的图标我们会接受 pr。还是更推荐自定义扩展图标库，后续我们会在官方文档中补全更多的扩展方式。

**Comment by CNChestnut** [comment]
> 官方的图标库不适合内置太多的图标，非常常用的图标我们会接受 pr。还是更推荐自定义扩展图标库，后续我们会在官方文档中补全更多的扩展方式。

嗯，至少对于 MDI 内的字体，自己有需要有可以更好的引入方式。

~~比如通过自定义 `npx` 安装？就跟 ShadcnUI 单独安装某个组件一样。~~
