### ISSUE TITLE
input placeholder style.max-width=0px

### ISSUE THREAD

**Issue by wang1plus** [varletjs/varlet#1058]
## Bug report

遇到个奇怪的问题 , input 的 placeholder 的宽度丢失

### 截图: 
![1684995103247](https://github.com/varletjs/varlet/assets/43996237/6d6b6fca-c313-4a12-877c-8869d3936325)

## Version & Environment
"@varlet/ui": "^2.11.0",
"vue": "^3.3.2",

**Comment by a145789** [comment]
收到，正在修复

**Comment by haoziqaq** [comment]
更新到 2.11.3-alpha.1685455534947
