### ISSUE TITLE
Snackbar teleport变量或props中并有声明，因此无法挂载到指定dom中

### ISSUE THREAD

**Issue by Luwei199169** [varletjs/varlet#1059]
# Bug report 🐞

## Version & Environment

vue最新版本、当前ui库最新版本

## Actual results (or Errors)
![GO5nHL1rUk](https://github.com/varletjs/varlet/assets/49578174/5259aa50-e9b6-4b55-bae2-a03111f58f92)

**Comment by haoziqaq** [comment]
方便描述的具体一些么？没怎么看明白 issue 标题的意思～
