### ISSUE TITLE
Snackbar component adjusts action style

### ISSUE THREAD

**Issue by tiny-dust** [varletjs/varlet#1073]
now:

![Image](https://github.com/varletjs/varlet/assets/49502875/90871a9e-6a12-44f8-be63-72a90acca602)

wish:

![Image](https://github.com/varletjs/varlet/assets/49502875/e9a4468c-6b80-4093-88dd-ddcc2c10d43a)

**Comment by BeADre** [comment]
<img width="335" alt="image" src="https://github.com/varletjs/varlet/assets/34639100/46e4e0c2-5beb-4339-b404-95902bcc3f96">


这个地方间距不一致了
