### ISSUE TITLE
var-sticky粘性布局组件配合顶部导航var-app出现宽度为0情况

### ISSUE THREAD

**Issue by AnyFork** [varletjs/varlet#1087]
# Bug report 🐞
var-sticky粘性布局组件配合顶部导航var-app，实现顶部导航粘性布局时，路由跳转页面，出现宽度为0情况
## Version & Environment
 "@varlet/ui": "2.11.4",
## Expectation
正常情况：
![image](https://github.com/varletjs/varlet/assets/49142023/f410a7bb-4c5f-47f4-8066-deba374bcd85)
异常情况
![image](https://github.com/varletjs/varlet/assets/49142023/2566eb3c-b4d2-4fa7-bfa6-20e283745bc7)
## Actual results (or Errors)
相关效果可以查看例子：
http://m.ieforex.com/
具体代码就2行：
```js
      <var-sticky offset-top="0" >
          <LayoutNavbar></LayoutNavbar>
      </var-sticky>
```
LayoutNavbar如下：
```vue
<template>
    <var-app-bar elevation="0" safe-area-top color="#fff" text-color="var(--h5-text-color)">
        <template #left>
            <var-button color="transparent" text-color="var(--h5-text-color)" text @click="show = true" style="padding: 0px">
                <var-icon name="menu" :size="30" />
            </var-button>
            <img src="/images/ieforex.png" alt="logo" />
        </template>
        <template #right>
            <var-menu>
                <switcher-language></switcher-language>
            </var-menu>
        </template>
    </var-app-bar>
    <LayoutSidebar v-model:show="show"></LayoutSidebar>
</template>
```
看到var-sticky有个[resize](https://varlet.gitee.io/varlet-ui/#/zh-CN/sticky#%E6%96%B9%E6%B3%95)，尝试过不起作用，使用方法如下，是否使用错误?
```js
const sticky = ref()
onMounted(()=>{
    nextTick(()=>{
        requestAnimationFrame(sticky.value.resize)
    })
})
```

**Comment by chenQushai** [comment]
你把cssmode设置成true，试试，不知名原因，var-sticky__wrapper 宽度被置为0了

**Comment by haoziqaq** [comment]
在组件挂载时，没有正确的读取到元素的实际尺寸导致的。有很多原因都可能导致这种情况，根本原因就是在需要 resize 的时候，页面可能没有完全显示。你可以尝试在页面完全显示时，向 window 派发一个自定义事件，让所有需要 resize 的组件进行一次重绘可以解决这个问题。
```
window.dispatchEvent(new Event('resize'))
```

**Comment by haoziqaq** [comment]
也可以对元素指定宽度，也可以解决。

**Comment by AnyFork** [comment]
> 你把cssmode设置成true，试试，不知名原因，var-sticky__wrapper 宽度被置为0了

cssmode设置成true可以解决这个问题

**Comment by haoziqaq** [comment]
css mode 可能不是一个通用的解决方案，因为我观察到页面的 tabs 的指示器也没有正确的获得到元素尺寸。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月12日(周一) 晚上7:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] var-sticky粘性布局组件配合顶部导航var-app出现宽度为0情况 (Issue #1087)




 
Closed #1087 as completed.
