### ISSUE TITLE
Has the team considered directly targeting material design 3?

### ISSUE THREAD

**Issue by SnowGuest** [varletjs/varlet#1100]
# About `styles` 🛠️
Maybe this will bring a lot of work and be separated from the version style, but material design 3 is really very good-looking.
So this is just an open discussion, not an official issue.🤔

**Comment by haoziqaq** [comment]
This workload is huge, and there is no plan for the time being.

**Comment by SnowGuest** [comment]
> This workload is huge, and there is no plan for the time being.

It's a lot of work, so it's just an open discussion

**Comment by SnowGuest** [comment]
Well, it seems that not too many people pay attention to this topic.
