### ISSUE TITLE
imagePreview图片预览指定初始位置问题

### ISSUE THREAD

**Issue by manyrices** [varletjs/varlet#1105]
# Bug report 🐞

```
<var-image-preview
    closeable
    :current="curImg"
    :images="images"
    v-model:show="show"
  />

const curImg = ref('')
const images = ref<string[]>([])

const showImg = (url: string) => {
  curImg.value = url
  show.value = true
}
onMounted(()=> {
    // 通过api异步获取图片列表，赋值给images
   images.value = [...data.reportImgs, ...data.quaraImgs]
})
```

## Version & Environment
 "@varlet/ui": "^2.11.8",
 "@vitejs/plugin-vue": "^4.1.0",
 "vue": "^3.2.47"

## Expectation
  每次点击事件应该会打开指定的图片
## Actual results (or Errors)
 只有第一次点击打开正确的图片，后续都是展示第一次点击的结果

**Comment by chouchouji** [comment]
I write a demo, but i don't reappeared it. Maybe I didn't understand your question very well. You can try it in this [link](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzaG93ID0gcmVmKGZhbHNlKVxuY29uc3QgaW1hZ2VzID0gcmVmKFtdKVxuY29uc3QgY3VycmVudCA9IHJlZignJylcblxub25Nb3VudGVkKCgpID0+IHtcbiAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgIGltYWdlcy52YWx1ZSA9IFtcbiAgJ2h0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQuanBnJyxcbiAgJ2h0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQyLmpwZycsXG5dXG4gIH0sIDIwMDApXG59KVxuICBcbmNvbnN0IGhhbmRsZUJ1dHRvbiA9ICgpID0+IHtcbiAgc2hvdy52YWx1ZSA9IHRydWU7XG4gIGlmKGN1cnJlbnQudmFsdWUgPT09ICcnKXtcbiAgICBjdXJyZW50LnZhbHVlID0gJ2h0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQuanBnJ1xuICB9ZWxzZXtcbiAgICBjdXJyZW50LnZhbHVlID0gaW1hZ2VzLnZhbHVlLmZpbHRlcigoaW1hZ2UpID0+IGltYWdlICE9PSBjdXJyZW50LnZhbHVlKVswXVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLWJ1dHRvblxuICAgIHR5cGU9XCJ3YXJuaW5nXCJcbiAgICBibG9ja1xuICAgIEBjbGljaz1cImhhbmRsZUJ1dHRvblwiXG4gID5cbiAgICDmjIflrprliJ3lp4vkvY3nva5cbiAgPC92YXItYnV0dG9uPlxuICA8dmFyLWltYWdlLXByZXZpZXdcbiAgICA6Y3VycmVudD1cImN1cnJlbnRcIlxuICAgIDppbWFnZXM9XCJpbWFnZXNcIlxuICAgIHYtbW9kZWw6c2hvdz1cInNob3dcIlxuICAvPlxuPC90ZW1wbGF0ZT4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4zLjIvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiLi92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==).

**Comment by haoziqaq** [comment]
我们正好在做 image-preview 这一部分的优化，之后我们将使用 `initial-index` 和 `to`, `prev`, `next` 方法控制页数

**Comment by haoziqaq** [comment]
[v2.12.0](https://github.com/varletjs/varlet/commit/a166e0c2260fac8afc24de3bd82518489db824c0) 发布了，尝试升级。
