### ISSUE TITLE
var-input组件BUG

### ISSUE THREAD

**Issue by wfx0805** [varletjs/varlet#1106]
# Bug report 🐞
界面使用flex布局，页面出现滚动条（就是图二中span标签挤下去的）
![image](https://github.com/varletjs/varlet/assets/48720127/71eabf64-b963-426c-871f-9545dfef5bc1)
![image](https://github.com/varletjs/varlet/assets/48720127/559d55bc-f568-4a26-b07f-a0900555de58)

## Version & Environment
varlet/ui ^2.11.2

**Comment by haoziqaq** [comment]
尝试升级到最新的alpha版本。已修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月1日(周六) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] var-input组件BUG (Issue #1106)




 
Bug report 🐞
 
界面使用flex布局，页面出现滚动条（就是图二中span标签挤下去的）
 
 
 
Version &amp; Environment
 
varlet/ui ^2.11.2
 
Expectation
 
Actual results (or Errors)

**Comment by haoziqaq** [comment]
[v2.12.0](https://github.com/varletjs/varlet/commit/a166e0c2260fac8afc24de3bd82518489db824c0) 发布了，尝试升级。

**Comment by wfx0805** [comment]
@haoziqaq 感谢，更新后已解决
目前 @varlet/ui 最新版本为 2.11.9-alpha
@varlet/touch-emulator 最新版本为2.12.0-alpha

**Comment by haoziqaq** [comment]
不客气，可以尝试升级到正式版。[v2.12.1](https://github.com/varletjs/varlet/commit/9d0eaf686b26fbcfba494d13453abbca5e223f30)
