### ISSUE TITLE
Form表单按Tab从text切换到passwordBUG

### ISSUE THREAD

**Issue by wfx0805** [varletjs/varlet#1112]
# Bug report 🐞
![image](https://github.com/varletjs/varlet/assets/48720127/87381a3f-7b91-4c8b-be42-eef6e5e5d2a5)
如图，焦点在姓名
按一次tab，焦点丢失
再按一次tab，焦点才到密码框

## Version & Environment
@varlet/touch-emulator@^2.12.1
@varlet/ui/-/ui-2.11.9-alpha

**Comment by chouchouji** [comment]
Can you provide more detailed information about this bug?

**Comment by chouchouji** [comment]
I reproduce it, thanks! We will fix this problem as soon as possible.
