### ISSUE TITLE
add select option group

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1116]
# Feature request 🚀

### Expected:

- add group to partition and display data better

### Examples:

```angular

<nz-select [(ngModel)]="selectedValue" nzAllowClear nzPlaceHolder="Choose" nzShowSearch>
      <nz-option-group nzLabel="Manager">
        <nz-option nzValue="jack" nzLabel="Jack"></nz-option>
        <nz-option nzValue="lucy" nzLabel="Lucy"></nz-option>
      </nz-option-group>
      <nz-option-group nzLabel="Engineer">
        <nz-option nzValue="tom" nzLabel="Tom"></nz-option>
      </nz-option-group>
</nz-select>

```

![image](https://github.com/varletjs/varlet/assets/70570907/67bfd987-9bf7-48a7-b649-ee32394c1cb9)

### Others:

try it in this [link](https://ng.ant.design/components/select/zh)

**Comment by haoziqaq** [comment]
Not supported for now, as [this alternative](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8dmFyLXNlbGVjdCBwbGFjZWhvbGRlcj1cIuivt+mAieaLqeS4gOS4qumAiemhuVwiIHYtbW9kZWw9XCJ2YWx1ZVwiPlxuICAgICAgPGRpdiBjbGFzcz1cImdyb3VwLXRpdGxlXCI+R1JPVVAgQTwvZGl2PlxuICAgICAgPHZhci1vcHRpb24gbGFiZWw9XCJPUFRJT04gQS0xXCIgLz5cbiAgICAgIDx2YXItb3B0aW9uIGxhYmVsPVwiT1BUSU9OIEEtMlwiIC8+XG5cbiAgICAgIDxkaXYgY2xhc3M9XCJncm91cC10aXRsZVwiPkdST1VQIEI8L2Rpdj5cbiAgICAgIDx2YXItb3B0aW9uIGxhYmVsPVwiT1BUSU9OIEEtM1wiIC8+XG4gICAgICA8dmFyLW9wdGlvbiBsYWJlbD1cIk9QVElPTiBBLTRcIiAvPlxuICAgIDwvdmFyLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5ncm91cC10aXRsZSB7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgY29sb3I6ICM4ODg7XG4gIHBhZGRpbmc6IDEycHg7XG59XG48L3N0eWxlPlxuIiwiQXBwV3JhcHBlci52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUkgZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFybGV0Q3NzID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aS9lcy9zdHlsZS5jc3MnXG5jb25zdCB2YXJsZXRUb3VjaEVtdWxhdG9yID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC90b3VjaC1lbXVsYXRvci9paWZlLmpzJ1xuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBjb25zdCBzY3JpcHQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKVxuICBzY3JpcHQuc3JjID0gdmFybGV0VG91Y2hFbXVsYXRvclxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHNjcmlwdClcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0+IHtcbiAgICB3aW5kb3cucGFyZW50LmRvY3VtZW50LmRpc3BhdGNoRXZlbnQobmV3IEV2ZW50KCdjbGljaycpKVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gdmFybGV0Q3NzXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcIkB2YXJsZXQvdWlcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwiUHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn0ifQ==) is available.
