### ISSUE TITLE
var-paper ios  v-for  显示空白   换成div就好了

### ISSUE THREAD

**Issue by GuoJieIsgentleman** [varletjs/varlet#1122]
# Bug report 🐞

**Comment by GuoJieIsgentleman** [comment]
show

**Comment by chouchouji** [comment]
Can you provide more details about this bug?

**Comment by GuoJieIsgentleman** [comment]
<var-paper :elevation="9" :radius="8">

            <slot name="content"></slot>
        </var-paper>
        <VarTable>

            <slot name="items"></slot>
        </VarTable>

这是子组件的内容  父组件使用 v-for 循环 这个 组件  并填充插槽  在 iOS 浏览器上循环遍历出来的内容只有一部分 显示不全   我把上述标签 替换成div 就正常了

**Comment by GuoJieIsgentleman** [comment]
<var-paper :elevation="9" :radius="8">

            <slot name="content"></slot>
        </var-paper>
        <VarTable>

            <slot name="items"></slot>
        </VarTable>

这是子组件的内容  父组件使用 v-for 循环 这个 组件  并填充插槽  在 iOS

**Comment by haoziqaq** [comment]
https://varlet.gitee.io/varlet-ui-playground/

可以在这里提供一个复现 demo。
