### ISSUE TITLE
希望给进度条组件增加圆角

### ISSUE THREAD

**Issue by JustGenius-s** [varletjs/varlet#1135]
# Feature request 🚀

### Expected:

能够支持自定义组件的圆角显示大小

### Examples:

```js

```

**Comment by haoziqaq** [comment]
圆角指的是轨道容器的圆角，还是轨道内填充颜色的圆角？

**Comment by JustGenius-s** [comment]
> 圆角指的是轨道容器的圆角，还是轨道内填充颜色的圆角？

如果轨道容器有圆角的话，填充颜色也应该是同样的吧，类似这样的效果：
![图片](https://github.com/varletjs/varlet/assets/53108645/7d8a4ebc-55b2-4d39-9944-f352643d3fb0)

**Comment by haoziqaq** [comment]
了解了，后续会以 css-var 的方式进行支持。
