### ISSUE TITLE
"isVNode" is not exported by "node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js", imported by "node_modules/@varlet/use/lib/useChildren.js".

### ISSUE THREAD

**Issue by TTsukiTT** [varletjs/varlet#1142]
# Bug report 🐞
when i run 'npm run build:mp-weixin' then the error happend.
## Version & Environment
2.13.4 & vue3+vite+uniapp 
## Actual results (or Errors)
 uni-preset-vue@0.0.0 build:mp-weixin
> uni build -p mp-weixin --mode production

正在编译中...
"isVNode" is not exported by "node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js", imported by "node_modules/@varlet/use/lib/useChildren.js".
at ../node_modules/@varlet/use/lib/useChildren.js:2:58
  1: import { removeItem } from '@varlet/shared';
  2: import { getCurrentInstance, computed, provide, reactive, isVNode, } from 'vue';
                                                               ^
  3: function flatVNodes(subTree) {
  4:     const vNodes = [];
Build failed with errors.

**Comment by chouchouji** [comment]
This is because our component library is based on Vue and does not adapt to Uniapp.

**Comment by nonzzz** [comment]
Currently. varlet don't support work with uniapp or taro and such those cross platform tool. If you want
to use varlet. Try using web view nesting.
