### ISSUE TITLE
The click event of the child element will be triggered after the drag is over

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1149]
# Bug report 🐞

I want to use drag component to display a draggable button. I bind a click event to it, but the click event of the button will be triggered after the drag is over.

## Version & Environment

latest version

## Expectation

the click event isn't triggered after the drag is over

## Actual results (or Errors)

the click event is triggered after the drag is over

## Reproduction link

https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmNvbnN0IGhhbmRsZUNsaWNrID0gKCkgPT4ge1xuICBhbGVydCgnZ2dnJylcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItZHJhZz5cbiAgICA8dmFyLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImhhbmRsZUNsaWNrXCI+5Z+65pys5L2/55SoPC92YXItYnV0dG9uPlxuICA8L3Zhci1kcmFnPlxuPC90ZW1wbGF0ZT5cbiIsIkFwcFdyYXBwZXIudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJIGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhcmxldENzcyA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvc3R5bGUuY3NzJ1xuY29uc3QgdmFybGV0VG91Y2hFbXVsYXRvciA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdG91Y2gtZW11bGF0b3IvaWlmZS5qcydcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgY29uc3Qgc2NyaXB0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0JylcbiAgc2NyaXB0LnNyYyA9IHZhcmxldFRvdWNoRW11bGF0b3JcbiAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChzY3JpcHQpXG5cbiAgaWYgKHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xhc3NMaXN0LmNvbnRhaW5zKCdkYXJrJykpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKFZhcmxldFVJLlRoZW1lcy5kYXJrKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKGRhdGEudmFsdWUgPT09ICdkYXJrJyA/IFZhcmxldFVJLlRoZW1lcy5kYXJrIDogbnVsbClcbiAgICB9XG4gIH0pXG5cbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gICAgd2luZG93LnBhcmVudC5kb2N1bWVudC5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnY2xpY2snKSlcbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9IHZhcmxldENzc1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJAdmFybGV0L3VpXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcIlByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59In0=

**Comment by chouchouji** [comment]
@haoziqaq I solved this problem when I refactored the fab before. I think using dragging value to control is not a good option. So I want to talk with you this problem by this issue.

**Comment by haoziqaq** [comment]
Maybe we can support click event for `drag`, if some users want to avoid click event triggering on touch end, they can use it.
