### ISSUE TITLE
按钮点击水波纹失效

### ISSUE THREAD

**Issue by DonHaha233** [varletjs/varlet#1173]
#使用
![image](https://github.com/varletjs/varlet/assets/73727285/77fad625-bcf8-4d40-9505-5af14e83e58e)
#版本号
![image](https://github.com/varletjs/varlet/assets/73727285/a73220e9-fa52-40fb-896a-92f78f08ebf6)
#效果
![image](https://github.com/varletjs/varlet/assets/73727285/0fdd01dc-2247-4e0f-85e8-7a416c0a516c)

**Comment by ErKeLost** [comment]
你这个是web么 还是 h5
可以看一下适配。https://varlet.gitee.io/varlet-ui/#/zh-CN/browserAdaptation

**Comment by haoziqaq** [comment]
```shell
pnpm add @varlet/touch-emulator
```

```js
import '@varlet/touch-emulator'
```
