### ISSUE TITLE
您好，progress进度条的颜色，希望可以设置成渐变色，就像appBar那样

### ISSUE THREAD

**Issue by wangzhe11** [varletjs/varlet#1179]
# Feature request 🚀

### Expected:

- progress进度条的颜色，可以设置成渐变色

### Examples:

```js

```
![WechatIMG1122](https://github.com/varletjs/varlet/assets/11495557/f4dd866a-8ec4-4263-86cb-fb1138808b1c)

**Comment by haoziqaq** [comment]
@chouchouji

**Comment by chouchouji** [comment]
I get it, I will add it later.

**Comment by chouchouji** [comment]
> @chouchouji

I get it.
