### ISSUE TITLE
System crash caused by preview after image upload

### ISSUE THREAD

**Issue by Kunoky** [varletjs/varlet#1187]
# Bug report 🐞
After uploading the image, previewing it and long pressing the image will cause the system to crash.

## Version & Environment
2.14.2, safari ,edge in android
## Reproduction link
https://varlet.gitee.io/varlet-ui/mobile.html#/uploader?language=zh-CN&platform=mobile

**Comment by chouchouji** [comment]
Can you provide a video to show it? I didn't reproduce it. My brsower work normally.

**Comment by Kunoky** [comment]
I think this is related to the length of base64

Uploading mmexport1695384291436.mp4…

**Comment by Kunoky** [comment]
https://github.com/varletjs/varlet/assets/26639880/8cd2a98c-0f5b-44e2-a209-99d578c94a85

I think this is related to the length of base64

**Comment by chouchouji** [comment]
> mmexport1695384291436.mp4 
> I think this is related to the length of base64

How about the size of this picture which you has uploaded？

**Comment by Kunoky** [comment]
368kb

**Comment by chouchouji** [comment]
> 368kb

It is so strange. I try it in safari in ios and chrome in android. The size of picture is more 1MB. But I don't reproduce it.

**Comment by Kunoky** [comment]
Have you performed a long touch to open the menu?

**Comment by chouchouji** [comment]
Uploading 84_1695621857.mp4…

I had done like what you had said. But I don't reproduce this issue. Can you try to debug it？

**Comment by Kunoky** [comment]
I am using edge on redmi k30 pro

**Comment by chouchouji** [comment]
> I am using edge on redmi k30 pro

I tested this issue in my android phone(one plus). It looked liked well. If try to get the reason, I agree with nonzzz's idea. You can debug it with `vconsole`.

**Comment by Kunoky** [comment]
Unable to debug because it crashes. Have you used Edge?

**Comment by nonzzz** [comment]
Actually  i want to help you but i don't have any android :(

**Comment by chouchouji** [comment]
> Unable to debug because it crashes. Have you used Edge?

Yes, I used this browser.

**Comment by Kunoky** [comment]
If it cannot be reproduced, forget it. I customized the preview

**Comment by chouchouji** [comment]
> If it cannot be reproduced, forget it. I customized the preview

👍 Maybe it will be reproduced by other users. I will try to solve it as soon as possible if necessary.

**Comment by Kunoky** [comment]
👍
