### ISSUE TITLE
把tabs选项卡放到popup中时，tabs选项卡的滚动失效

### ISSUE THREAD

**Issue by chinayzq** [varletjs/varlet#1202]
把tabs选项卡放到popup中时，tabs选项卡的滚动失效，初步看了下是因为popup的position:absolute导致的，有没有解决办法呢

**Comment by haoziqaq** [comment]
您好，可否提供一个最小复现 demo，如 [playground](https://varlet.gitee.io/varlet-ui-playground)。以便我们更容器排查问题。

**Comment by chinayzq** [comment]
@haoziqaq 您好，麻烦看下下面链接

https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbmNvbnN0IHN0aWNrZXJzU2hvdyA9IHJlZihmYWxzZSlcbmNvbnN0IGFjdGl2ZSA9IHJlZigwKVxuY29uc3QgdGFicyA9IHJlZihbXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTQtMTIvYmRhMjkzYzAtZDU5MC00NThhLWI5NjAtMDk5MzkyNmZlZDIxLnBuZ1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvNTA4NjY2MWYtOWZkMS00MWI0LWE0NWItNGNkODhiMmE2ZjdmX3MuUE5HXCIsXG4gIH0sXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy9iNmI2OTNiMC1lYmNlLTQ4MjUtOTY1Mi0wNjFmNzllN2JmZDdfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zL2QwZmIxYTViLTVjNjgtNDk5Ny1hYjMwLTE2OWE2YTIxZDdiN19zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvNmUxYjkzN2QtODU0MC00N2E5LWJjYTYtMGJhMGQxNDk4Y2RhX3MuUE5HXCIsXG4gIH0sXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy9hNTYzZTIyNy0xOTc5LTQyN2QtYTZhNi0yOTYwNjQ0ZjExZDhfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtOS0xOC8xZjM0NWNjZi1kMDFlLTQxMmItYmE5ZS1mZDBlMmRjNDhhYzFfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtOS0xOC8yZjQ5MzNhOC02MGMzLTRiZjEtOTdlNC1hMjYwNzE2N2Y1MDNfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zL2E1NjNlMjI3LTE5NzktNDI3ZC1hNmE2LTI5NjA2NDRmMTFkOF9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzFmMzQ1Y2NmLWQwMWUtNDEyYi1iYTllLWZkMGUyZGM0OGFjMV9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzJmNDkzM2E4LTYwYzMtNGJmMS05N2U0LWEyNjA3MTY3ZjUwM19zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy00LTEyL2JkYTI5M2MwLWQ1OTAtNDU4YS1iOTYwLTA5OTM5MjZmZWQyMS5wbmdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zLzUwODY2NjFmLTlmZDEtNDFiNC1hNDViLTRjZDg4YjJhNmY3Zl9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvYjZiNjkzYjAtZWJjZS00ODI1LTk2NTItMDYxZjc5ZTdiZmQ3X3MuUE5HXCIsXG4gIH0sXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy9kMGZiMWE1Yi01YzY4LTQ5OTctYWIzMC0xNjlhNmEyMWQ3Yjdfcy5QTkdcIixcbiAgfSxcbiAgIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy82ZTFiOTM3ZC04NTQwLTQ3YTktYmNhNi0wYmEwZDE0OThjZGFfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zL2E1NjNlMjI3LTE5NzktNDI3ZC1hNmE2LTI5NjA2NDRmMTFkOF9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzFmMzQ1Y2NmLWQwMWUtNDEyYi1iYTllLWZkMGUyZGM0OGFjMV9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzJmNDkzM2E4LTYwYzMtNGJmMS05N2U0LWEyNjA3MTY3ZjUwM19zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvYTU2M2UyMjctMTk3OS00MjdkLWE2YTYtMjk2MDY0NGYxMWQ4X3MuUE5HXCIsXG4gIH0sXG5dKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3RpY2tlcnNTaG93ID0gdHJ1ZVwiPnt7IG1zZyB9fTwvdmFyLWJ1dHRvbj5cbiAgPHZhci1wb3B1cFxuICAgICAgb3ZlcmxheS1jbGFzcz1cInBvcHVwLWN1c3RvbS1vdmVybGF5XCJcbiAgICAgIHBvc2l0aW9uPVwiYm90dG9tXCJcbiAgICAgIHYtbW9kZWw6c2hvdz1cInN0aWNrZXJzU2hvd1wiXG4gICAgPlxuICAgICAgPHZhci10YWJzIHYtbW9kZWw6YWN0aXZlPVwiYWN0aXZlXCI+XG4gICAgICAgIDx2YXItdGFiXG4gICAgICAgICAgdi1mb3I9XCJ0YWIgaW4gdGFic1wiXG4gICAgICAgICAgOmtleT1cInRhYi5zcmNcIlxuICAgICAgICAgIGNvbG9yPVwidmFyKC0tY29sb3ItcHJpbWFyeSlcIlxuICAgICAgICAgIGFjdGl2ZS1jb2xvcj1cIiNmZmZcIlxuICAgICAgICAgIGluYWN0aXZlLWNvbG9yPVwiaHNsYSgwLCAwJSwgMTAwJSwgLjYpXCJcbiAgICAgICAgPlxuICAgICAgICAgIDx2YXItaW1hZ2VcbiAgICAgICAgICAgIHdpZHRoPVwiNDBweFwiXG4gICAgICAgICAgICBoZWlnaHQ9XCI0MHB4XCJcbiAgICAgICAgICAgIGxhenlcbiAgICAgICAgICAgIDpzcmM9XCJ0YWIuc3JjXCJcbiAgICAgICAgICAvPlxuICAgICAgICA8L3Zhci10YWI+XG4gICAgICA8L3Zhci10YWJzPlxuICAgICAgICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiAzMDBweFwiPjwvZGl2PlxuICAgIDwvdmFyLXBvcHVwPlxuPC90ZW1wbGF0ZT5cbiIsIkFwcFdyYXBwZXIudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJIGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhcmxldENzcyA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvc3R5bGUuY3NzJ1xuY29uc3QgdmFybGV0VG91Y2hFbXVsYXRvciA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdG91Y2gtZW11bGF0b3IvaWlmZS5qcydcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgY29uc3Qgc2NyaXB0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0JylcbiAgc2NyaXB0LnNyYyA9IHZhcmxldFRvdWNoRW11bGF0b3JcbiAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChzY3JpcHQpXG5cbiAgaWYgKHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xhc3NMaXN0LmNvbnRhaW5zKCdkYXJrJykpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKFZhcmxldFVJLlRoZW1lcy5kYXJrKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKGRhdGEudmFsdWUgPT09ICdkYXJrJyA/IFZhcmxldFVJLlRoZW1lcy5kYXJrIDogbnVsbClcbiAgICB9XG4gIH0pXG5cbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gICAgd2luZG93LnBhcmVudC5kb2N1bWVudC5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnY2xpY2snKSlcbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9IHZhcmxldENzc1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJAdmFybGV0L3VpXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcIlByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59In0=

**Comment by haoziqaq** [comment]
您可以通过显式设置 tabs 的宽度解决这个问题，[Playground](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbmNvbnN0IHN0aWNrZXJzU2hvdyA9IHJlZihmYWxzZSlcbmNvbnN0IGFjdGl2ZSA9IHJlZigwKVxuY29uc3QgdGFicyA9IHJlZihbXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTQtMTIvYmRhMjkzYzAtZDU5MC00NThhLWI5NjAtMDk5MzkyNmZlZDIxLnBuZ1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvNTA4NjY2MWYtOWZkMS00MWI0LWE0NWItNGNkODhiMmE2ZjdmX3MuUE5HXCIsXG4gIH0sXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy9iNmI2OTNiMC1lYmNlLTQ4MjUtOTY1Mi0wNjFmNzllN2JmZDdfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zL2QwZmIxYTViLTVjNjgtNDk5Ny1hYjMwLTE2OWE2YTIxZDdiN19zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvNmUxYjkzN2QtODU0MC00N2E5LWJjYTYtMGJhMGQxNDk4Y2RhX3MuUE5HXCIsXG4gIH0sXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy9hNTYzZTIyNy0xOTc5LTQyN2QtYTZhNi0yOTYwNjQ0ZjExZDhfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtOS0xOC8xZjM0NWNjZi1kMDFlLTQxMmItYmE5ZS1mZDBlMmRjNDhhYzFfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtOS0xOC8yZjQ5MzNhOC02MGMzLTRiZjEtOTdlNC1hMjYwNzE2N2Y1MDNfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zL2E1NjNlMjI3LTE5NzktNDI3ZC1hNmE2LTI5NjA2NDRmMTFkOF9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzFmMzQ1Y2NmLWQwMWUtNDEyYi1iYTllLWZkMGUyZGM0OGFjMV9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzJmNDkzM2E4LTYwYzMtNGJmMS05N2U0LWEyNjA3MTY3ZjUwM19zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy00LTEyL2JkYTI5M2MwLWQ1OTAtNDU4YS1iOTYwLTA5OTM5MjZmZWQyMS5wbmdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zLzUwODY2NjFmLTlmZDEtNDFiNC1hNDViLTRjZDg4YjJhNmY3Zl9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvYjZiNjkzYjAtZWJjZS00ODI1LTk2NTItMDYxZjc5ZTdiZmQ3X3MuUE5HXCIsXG4gIH0sXG4gIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy9kMGZiMWE1Yi01YzY4LTQ5OTctYWIzMC0xNjlhNmEyMWQ3Yjdfcy5QTkdcIixcbiAgfSxcbiAgIHtcbiAgICBzcmM6IFwiaHR0cHM6Ly9vc3MuZGF0YS5pZGVhc2tpbnMuY29tLmNuL2RpeS8yMDIzLTctMy82ZTFiOTM3ZC04NTQwLTQ3YTktYmNhNi0wYmEwZDE0OThjZGFfcy5QTkdcIixcbiAgfSxcbiAge1xuICAgIHNyYzogXCJodHRwczovL29zcy5kYXRhLmlkZWFza2lucy5jb20uY24vZGl5LzIwMjMtNy0zL2E1NjNlMjI3LTE5NzktNDI3ZC1hNmE2LTI5NjA2NDRmMTFkOF9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzFmMzQ1Y2NmLWQwMWUtNDEyYi1iYTllLWZkMGUyZGM0OGFjMV9zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy05LTE4LzJmNDkzM2E4LTYwYzMtNGJmMS05N2U0LWEyNjA3MTY3ZjUwM19zLlBOR1wiLFxuICB9LFxuICB7XG4gICAgc3JjOiBcImh0dHBzOi8vb3NzLmRhdGEuaWRlYXNraW5zLmNvbS5jbi9kaXkvMjAyMy03LTMvYTU2M2UyMjctMTk3OS00MjdkLWE2YTYtMjk2MDY0NGYxMWQ4X3MuUE5HXCIsXG4gIH0sXG5dKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3RpY2tlcnNTaG93ID0gdHJ1ZVwiPnt7IG1zZyB9fTwvdmFyLWJ1dHRvbj5cbiAgPHZhci1wb3B1cFxuICAgICAgb3ZlcmxheS1jbGFzcz1cInBvcHVwLWN1c3RvbS1vdmVybGF5XCJcbiAgICAgIHBvc2l0aW9uPVwiYm90dG9tXCJcbiAgICAgIHYtbW9kZWw6c2hvdz1cInN0aWNrZXJzU2hvd1wiXG4gICAgPlxuICAgICAgPHZhci10YWJzIHYtbW9kZWw6YWN0aXZlPVwiYWN0aXZlXCIgc3R5bGU9XCJ3aWR0aDogMTAwdndcIj5cbiAgICAgICAgPHZhci10YWJcbiAgICAgICAgICB2LWZvcj1cInRhYiBpbiB0YWJzXCJcbiAgICAgICAgICA6a2V5PVwidGFiLnNyY1wiXG4gICAgICAgICAgY29sb3I9XCJ2YXIoLS1jb2xvci1wcmltYXJ5KVwiXG4gICAgICAgICAgYWN0aXZlLWNvbG9yPVwiI2ZmZlwiXG4gICAgICAgICAgaW5hY3RpdmUtY29sb3I9XCJoc2xhKDAsIDAlLCAxMDAlLCAuNilcIlxuICAgICAgICA+XG4gICAgICAgICAgPHZhci1pbWFnZVxuICAgICAgICAgICAgd2lkdGg9XCI0MHB4XCJcbiAgICAgICAgICAgIGhlaWdodD1cIjQwcHhcIlxuICAgICAgICAgICAgbGF6eVxuICAgICAgICAgICAgOnNyYz1cInRhYi5zcmNcIlxuICAgICAgICAgIC8+XG4gICAgICAgIDwvdmFyLXRhYj5cbiAgICAgIDwvdmFyLXRhYnM+XG4gICAgPC92YXItcG9wdXA+XG48L3RlbXBsYXRlPlxuIiwiQXBwV3JhcHBlci52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUkgZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFybGV0Q3NzID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aS9lcy9zdHlsZS5jc3MnXG5jb25zdCB2YXJsZXRUb3VjaEVtdWxhdG9yID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC90b3VjaC1lbXVsYXRvci9paWZlLmpzJ1xuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBjb25zdCBzY3JpcHQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKVxuICBzY3JpcHQuc3JjID0gdmFybGV0VG91Y2hFbXVsYXRvclxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHNjcmlwdClcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0+IHtcbiAgICB3aW5kb3cucGFyZW50LmRvY3VtZW50LmRpc3BhdGNoRXZlbnQobmV3IEV2ZW50KCdjbGljaycpKVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gdmFybGV0Q3NzXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcIkB2YXJsZXQvdWlcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwiUHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn0ifQ==), 我们在下一个版本会对 popup 进行优化，减少这类问题发生的可能性。

**Comment by chinayzq** [comment]
@haoziqaq 好的，我刚在.var-popup--bottom的样式加一个max-width设置为100%也解决了这个问题，多谢啦~

**Comment by haoziqaq** [comment]
不客气～
