### ISSUE TITLE
a warning appears in the pull-refresh component

### ISSUE THREAD

**Issue by Bruce-1988** [varletjs/varlet#1212]
# Bug report 🐞
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

This warning appears in the document PullRefresh.mjs
## Version & Environment
I find it in the version 2.16.6, but it still appear until update to version 2.17.1
## Expectation
I don't know whether it will work, develop the code like:
```
if (isReachTop && deltaY >= 0) {
        if (event.cancelable) event.preventDefault();
      }
```
## Actual results (or Errors)
<img width="281" alt="image" src="https://github.com/varletjs/varlet/assets/52615429/227d89d2-2cef-4018-9b53-c3dcc38db4ec">

**Comment by haoziqaq** [comment]
OK.
