### ISSUE TITLE
The fixed child element doesn't work if its parent element has transform property

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1218]
# Bug report 🐞

I used the tab component and wanted to achieve view linkage. I added a fixed first tab item to the bottom div, but it failed.

The reason of this problem is the transform property.

You can find it in this [link](https://www.w3.org/TR/css-transforms-1/#issue-ca2c412c)

So are there some good solutions for this issues?

![image](https://github.com/varletjs/varlet/assets/70570907/00510ef0-43d7-4de1-8ba5-7f9a6f1f64ac)

## Version & Environment

latest

## Reproduction link

https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgYWN0aXZlID0gcmVmKDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLXRhYnMgZWxldmF0aW9uIGNvbG9yPVwidmFyKC0tY29sb3ItcHJpbWFyeSlcIiBhY3RpdmUtY29sb3I9XCIjZmZmXCIgaW5hY3RpdmUtY29sb3I9XCJoc2xhKDAsIDAlLCAxMDAlLCAuNilcIlxuICAgIHYtbW9kZWw6YWN0aXZlPVwiYWN0aXZlXCI+XG4gICAgPHZhci10YWI+6YCJ6aG5MTwvdmFyLXRhYj5cbiAgICA8dmFyLXRhYj7pgInpobkyPC92YXItdGFiPlxuICAgIDx2YXItdGFiPumAiemhuTM8L3Zhci10YWI+XG4gIDwvdmFyLXRhYnM+XG5cbiAgPHZhci10YWJzLWl0ZW1zIHYtbW9kZWw6YWN0aXZlPVwiYWN0aXZlXCI+XG4gICAgPHZhci10YWItaXRlbT5cbiAgICAgIDxkaXYgY2xhc3M9XCJ0ZXh0LWNvbnRhaW5lclwiPlxuICAgICAgICDlvojlpJrkurrkuI3plb/nnLznnZvvvIzlmqPlvKDpg73pnaDmrablmajjgIJcbiAgICAgIDwvZGl2PlxuICAgIDwvdmFyLXRhYi1pdGVtPlxuICAgIDx2YXItdGFiLWl0ZW0+XG4gICAgICDlvojlpJrkurrkuI3plb/nnLznnZvvvIzlmqPlvKDpg73pnaDmrablmajjgIIg6LWk5omL56m65ouz5bCx57yp5oiQ6JqC6JqB44CCIOS4jeeUqOm6u+eDpuS6hu+8jOS4jeeUqOm6u+eDpuS6huOAgiDkuI3nlKjpurvng6bvvIzkuI3nlKjpurvng6bkuobvvIzkuI3nlKjpurvng6bkuobjgIJcbiAgICA8L3Zhci10YWItaXRlbT5cbiAgICA8dmFyLXRhYi1pdGVtPlxuICAgICAg5L2g5Lus5LiA6LW35LiK77yM5oiR5Zyo6LW25pe26Ze044CCIOavj+WkqeWGs+aWl+inguS8l+mDvee0r+S6hu+8jOiLsembhOS5n+e0r+S6huOAgiDkuI3nlKjpurvng6bkuobvvIzkuI3nlKjpurvng6bkuobjgIJcbiAgICAgIOWJr+atjOS4jemVv+S9oOS7rOacieWHoOS4qu+8jOS4gOi1t+S4iuWlveS6huOAgiDmraPkuYnlkbzllKTmiJHvvIznvo7lpbPpnIDopoHmiJHjgIIg54mb5LuU5b6I5b+Z55qE44CCXG4gICAgPC92YXItdGFiLWl0ZW0+XG4gIDwvdmFyLXRhYnMtaXRlbXM+XG48L3RlbXBsYXRlPlxuXG48c3R5bGU+XG4udGV4dC1jb250YWluZXIge1xuICBwb3NpdGlvbjogZml4ZWQ7XG4gIGxlZnQ6IDA7XG4gIGJvdHRvbTogMDtcbiAgd2lkdGg6IDEwMCU7XG4gIGhlaWdodDogNDAwcHg7XG4gIGJhY2tncm91bmQ6IGdvbGQ7XG59XG48L3N0eWxlPiIsIkFwcFdyYXBwZXIudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJIGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhcmxldENzcyA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvc3R5bGUuY3NzJ1xuY29uc3QgdmFybGV0VG91Y2hFbXVsYXRvciA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdG91Y2gtZW11bGF0b3IvaWlmZS5qcydcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgY29uc3Qgc2NyaXB0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0JylcbiAgc2NyaXB0LnNyYyA9IHZhcmxldFRvdWNoRW11bGF0b3JcbiAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChzY3JpcHQpXG5cbiAgaWYgKHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xhc3NMaXN0LmNvbnRhaW5zKCdkYXJrJykpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKFZhcmxldFVJLlRoZW1lcy5kYXJrKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKGRhdGEudmFsdWUgPT09ICdkYXJrJyA/IFZhcmxldFVJLlRoZW1lcy5kYXJrIDogbnVsbClcbiAgICB9XG4gIH0pXG5cbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gICAgd2luZG93LnBhcmVudC5kb2N1bWVudC5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnY2xpY2snKSlcbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9IHZhcmxldENzc1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJAdmFybGV0L3VpXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcIlByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59In0=

**Comment by haoziqaq** [comment]
It is recommended to use teleport in Vue3 to move elements to the body. This is something developers need to pay attention to.

**Comment by haoziqaq** [comment]
Teleport was proposed to solve this problem.

**Comment by chouchouji** [comment]
> It is recommended to use teleport in Vue3 to move elements to the body. This is something developers need to pay attention to.

I thought it and I tried it. It worked as I expect. I ran into this problem when I wrote a new component. Do you think add `Teleport` to FloatingPanel component. I think it is necessary to make it work normally. 

I am not sure there are some better ideas to solve this problem. So I opened this issue.

**Comment by haoziqaq** [comment]
I think FloatingPanel is similar to Popup in that it requires props.teleport to let the user choose where to mount it.

**Comment by chouchouji** [comment]
> I think FloatingPanel is similar to Popup in that it requires props.teleport to let the user choose where to mount it.

Ok, I will add it to FloatingPanel component
