### ISSUE TITLE
希望 Popup 能和 Dialog 一样 可以有函数api调用 ，并且支持传入 () => JSX.Element  render函数

### ISSUE THREAD

**Issue by PromiseAll** [varletjs/varlet#1226]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js
  import Demo from './demo.vue'
  Dialog({
    title: '兰亭序',
    message: ()=>h(Demo)
  })

  Popup({
    position: 'right',
    message: ()=>h(Demo)
  })
```

**Comment by haoziqaq** [comment]
个人感觉将 Popup 函数化的意义相对于 Dialog Snackbar 这类需要用户交互反馈或是有单例需求的组件来说是较小的，我们需要避免将组件频繁的进行函数化。


如果您确实有函数调用的需要，可以参考 varlet 的函数化实现，简单的对 Popup 组件进行包装，以一个小成本的方式使组件函数化。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 希望 Popup 能和 Dialog 一样 可以有函数api调用 ，并且支持传入 () =&gt; JSX.Element  render函数 (Issue #1226)




 
Feature request 🚀
 
Expected:
  
No breaking changes
  
Examples:
   import Demo from './demo.vue'   Dialog({     title: '兰亭序',     message: ()=&gt;h(Demo)   })   Popup({     position: 'right',     message: ()=&gt;h(Demo)   })
