### ISSUE TITLE
The zIndex of ripple affects the components that use it

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1250]
# Bug report 🐞

The zIndex of ripple affects the components that use it.

## Version & Environment

varlet: latest

## Actual results (or Errors)

The `zIndex` of header is **99** and  `rippple` is  **100**.  And the card component doesn't includes this css property.

If you add ripple prop, try to click floating button, it will be full screen. Check the card component z-index

If you remove ripple prop, try to click floating button, it will be full screen. Check the card component z-index

## Reproduction link

1.  add `ripple` for `var-card`
2.  remove `ripple` in `var-card`

try this [link](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZmxvYXRpbmcgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiaGVhZGVyXCI+PC9kaXY+XG4gIDx2YXItY2FyZFxuICAgIHRpdGxlPVwi5pys6I2J57qy55uuXCJcbiAgICBzdWJ0aXRsZT1cIuaIkeihqOaDheaCoOWTiSDot7PkuKrlpKfmpoJcIlxuICAgIHNyYz1cImh0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQuanBnXCJcbiAgICB2LW1vZGVsOmZsb2F0aW5nPVwiZmxvYXRpbmdcIlxuICA+XG4gICAgPHRlbXBsYXRlICNleHRyYT5cbiAgICAgIDx2YXItYnV0dG9uIHRleHQgdHlwZT1cIndhcm5pbmdcIiBAY2xpY2s9XCJmbG9hdGluZyA9IHRydWVcIj7lvIDlkK88L3Zhci1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cblxuICAgIDx0ZW1wbGF0ZSAjZmxvYXRpbmctY29udGVudD5cbiAgICAgIDx2YXItZGl2aWRlciBkYXNoZWQgLz5cbiAgICAgIFxuICAgICAgPGRpdiBjbGFzcz1cImNhcmQtZXhhbXBsZS10ZXh0XCI+XG4gICAgICAgIOWmguaenOWNjuS9l+WGjeS4lizltIfmtIvpg73ooqvljLvmsrss5aSW6YKm5p2l5a2m5rGJ5a2XLOa/gOWPkeaIkeawkeaXj+aEj+ivhuOAgumprOmSseWtkOOAgeWGs+aYjuWtkOOAgeiLjeiAs+WtkO+8jOi/mOacieiOsuWtkO+8m+m7hOiNr+WtkOOAgeiLpuixhuWtkOOAgeW3nealneWtkO+8jOaIkeimgemdouWtkOOAgueUqOaIkeeahOaWueW8j++8jOaUueWGmeS4gOmDqOWOhuWPsuOAguayoeS7gOS5iOWIq+eahOS6i++8jOi3n+edgOaIkeW/teWHoOS4quWtl+OAguWxseiNr+W9k+W9kuaeuOadniBHT++8jOWxseiNryDlvZPlvZIg5p645p2eIEdP77yM55yL5oiR5oqT5LiA5oqK5Lit6I2v77yM5pyN5LiL5LiA5biW6aqE5YKyflxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC92YXItY2FyZD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbi5oZWFkZXIge1xuICB3aWR0aDogMTAwJTtcbiAgaGVpZ2h0OiA0MHB4O1xuICBiYWNrZ3JvdW5kOiBwaW5rO1xuICBwb3NpdGlvbjogZml4ZWQ7XG4gIHRvcDogMDtcbiAgbGVmdDogMDtcbiAgei1pbmRleDogOTk7XG59XG5cbi5jYXJkLWV4YW1wbGUtdGV4dCB7XG4gIHBhZGRpbmc6IDE0cHg7XG4gIGZvbnQtc2l6ZTogMTRweDtcbiAgbGluZS1oZWlnaHQ6IDI4cHg7XG59XG48L3N0eWxlPlxuIiwiQXBwV3JhcHBlci52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUkgZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFybGV0Q3NzID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aS9lcy9zdHlsZS5jc3MnXG5jb25zdCB2YXJsZXRUb3VjaEVtdWxhdG9yID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC90b3VjaC1lbXVsYXRvci9paWZlLmpzJ1xuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBjb25zdCBzY3JpcHQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKVxuICBzY3JpcHQuc3JjID0gdmFybGV0VG91Y2hFbXVsYXRvclxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHNjcmlwdClcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0+IHtcbiAgICB3aW5kb3cucGFyZW50LmRvY3VtZW50LmRpc3BhdGNoRXZlbnQobmV3IEV2ZW50KCdjbGljaycpKVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gdmFybGV0Q3NzXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcIkB2YXJsZXQvdWlcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwiUHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn0ifQ==)

**Comment by haoziqaq** [comment]
Ripple's z-index does have some side effects, but there is currently no better solution. Fortunately, the negative impact so far is relatively small.

**Comment by chouchouji** [comment]
> Ripple's z-index does have some side effects, but there is currently no better solution. Fortunately, the negative impact so far is relatively small.

I get it.
