### ISSUE TITLE
varlet/cli 安装报错，麻烦看一下

### ISSUE THREAD

**Issue by shuaikai001** [varletjs/varlet#1272]
![联想999](https://github.com/varletjs/varlet/assets/45255932/b7fc1a54-1f8a-4807-8445-079f340de6f6)

想尝试用varlet/cli ，结果安装报错了，请帮我看下什么原因。

**Comment by haoziqaq** [comment]
Please check [https://github.com/varletjs/varlet/blob/dev/.github/CONTRIBUTING.md#q--a](CONTRIBUTING)

**Comment by shuaikai001** [comment]
我只是使用varlet/cli，出了点问题，找不到合适的解决方法，想让你们帮忙看一下，我又不提pr，提交代码，那个干什么？还是英文的。

**Comment by haoziqaq** [comment]
pnpm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
pnpm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"

**Comment by haoziqaq** [comment]
因为内容里包含了解决办法，所以我直接引用给你。

**Comment by shuaikai001** [comment]
很抱歉，刚才满篇英文有点没看懂，没看到最下面，非常感谢您。

**Comment by haoziqaq** [comment]
没关系，大概率是国内网络环境影响的，希望能够解决。

**Comment by haoziqaq** [comment]
嗯嗯，能够理解，哈哈。希望顺利～

**Comment by shuaikai001** [comment]
可以整一个什么专门放，在使用过程中遇到错误的解决方法的md或者其他文档嘛，因为这样更利于社区推广呢。
