### ISSUE TITLE
[datePicker&timePicker] add action buttons

### ISSUE THREAD

**Issue by BeADre** [varletjs/varlet#1273]
e.g
![image](https://github.com/varletjs/varlet/assets/34639100/ef68e931-bfb2-4498-b416-2bfcbc5fa69c)

**Comment by BeADre** [comment]
@gaoting [example](https://play.vuetifyjs.com/#eNqLrlYqLkrWdywo0CsrTVWyUrIpSc0tyEksSbWLyVNQsCnTTSwoADPBnOT8vJLEzLzUIqgQWDAFqFq3IDM5G0kYKAEzSEE5MbkkMz+vGEkSrC+pJM8uOTEvOTXHRh/Cw6IgPxtT0kYfxZEQIWzuAImiOhkkAvERiiFKtTpKxnrGeuZKINpEz0ApFgCM8FQu)

**Comment by Sixlty** [comment]
Can I try it? @BeADre @gaoting
