### ISSUE TITLE
[Chip]: The radius still exists after setting round to false 

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1280]
# Bug report 🐞

please read title

## Version & Environment

latest

## Expectation

no border radius

## Actual results (or Errors)

![image](https://github.com/varletjs/varlet/assets/70570907/69508ac7-6fea-460b-9059-8426bc5d47e9)

## Reproduction link

[link](https://varlet.gitee.io/varlet-ui/#/en-US/chip)

**Comment by haoziqaq** [comment]
"Non-round chip" just means it's not round, but has a little radius.

**Comment by chouchouji** [comment]
> "Non-round chip" just means it's not round, but has a little radius.

I get it.
