### ISSUE TITLE
input添加icon不触发动画

### ISSUE THREAD

**Issue by chaomashi** [varletjs/varlet#1284]
[https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCB2YWx1ZTIgPSByZWYoJycpXG5jb25zdCB2YWx1ZTMgPSByZWYoJycpXG5jb25zdCB2YWx1ZTQgPSByZWYoJycpXG5jb25zdCB2YWx1ZTUgPSByZWYoJycpXG5jb25zdCB2YWx1ZTYgPSByZWYoJycpXG5jb25zdCB2YWx1ZTcgPSByZWYoJycpXG5jb25zdCB2YWx1ZTggPSByZWYoJycpXG5jb25zdCB2YWx1ZTkgPSByZWYoJycpXG5jb25zdCB2YWx1ZTEwID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHZhci1zcGFjZSBkaXJlY3Rpb249XCJjb2x1bW5cIiBzaXplPVwibGFyZ2VcIj5cbiAgICA8dmFyLWlucHV0IHZhcmlhbnQ9XCJvdXRsaW5lZFwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5paH5pysXCIgdi1tb2RlbD1cInZhbHVlXCIgLz5cbiAgICA8dmFyLWlucHV0IHZhcmlhbnQ9XCJvdXRsaW5lZFwiIHBsYWNlaG9sZGVyPVwi5Y+q6K+7XCIgcmVhZG9ubHkgdi1tb2RlbD1cInZhbHVlMlwiIC8+XG4gICAgPHZhci1pbnB1dCB2YXJpYW50PVwib3V0bGluZWRcIiBwbGFjZWhvbGRlcj1cIuemgeeUqFwiIGRpc2FibGVkIHYtbW9kZWw9XCJ2YWx1ZTNcIiAvPlxuICAgIDx2YXItaW5wdXQgdmFyaWFudD1cIm91dGxpbmVkXCIgcGxhY2Vob2xkZXI9XCLlj6/muIXpmaRcIiBjbGVhcmFibGUgdi1tb2RlbD1cInZhbHVlNFwiIC8+XG4gICAgPHZhci1pbnB1dFxuICAgICAgdmFyaWFudD1cIm91dGxpbmVkXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwi5a2X5q615qCh6aqMXCJcbiAgICAgIDpydWxlcz1cIlsodikgPT4gdi5sZW5ndGggPiA2IHx8ICfmlofmnKzplb/luqblv4XpobvlpKfkuo42J11cIlxuICAgICAgdi1tb2RlbD1cInZhbHVlNVwiXG4gICAgLz5cbiAgICA8dmFyLWlucHV0IHZhcmlhbnQ9XCJvdXRsaW5lZFwiIHBsYWNlaG9sZGVyPVwi5pi+56S65Zu+5qCHXCIgdi1tb2RlbD1cInZhbHVlNlwiPlxuICAgICAgPHRlbXBsYXRlICNwcmVwZW5kLWljb24+XG4gICAgICAgIDx2YXItaWNvbiBjbGFzcz1cInByZXBlbmQtaWNvblwiIG5hbWU9XCJnaXRodWJcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDx0ZW1wbGF0ZSAjYXBwZW5kLWljb24+XG4gICAgICAgIDx2YXItaWNvbiBjbGFzcz1cImFwcGVuZC1pY29uXCIgbmFtZT1cImdpdGh1YlwiIC8+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvdmFyLWlucHV0PlxuICAgIDx2YXItaW5wdXQgXG4gICAgICB2YXJpYW50PVwib3V0bGluZWRcIiBcbiAgICAgIHBsYWNlaG9sZGVyPVwi6Ieq5a6a5LmJ5Zu+5qCH5bC65a+4XCIgXG4gICAgICBzdHlsZT1cIi0tZmllbGQtZGVjb3JhdG9yLW1pZGRsZS1vZmZzZXQteTogOHB4XCIgXG4gICAgICB2LW1vZGVsPVwidmFsdWU3XCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI3ByZXBlbmQtaWNvbj5cbiAgICAgICAgPHZhci1pY29uIGNsYXNzPVwicHJlcGVuZC1pY29uXCIgbmFtZT1cImdpdGh1YlwiIDpzaXplPVwiMjhcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDx0ZW1wbGF0ZSAjYXBwZW5kLWljb24+XG4gICAgICAgIDx2YXItaWNvbiBjbGFzcz1cImFwcGVuZC1pY29uXCIgbmFtZT1cImdpdGh1YlwiIDpzaXplPVwiNDJcIiAvPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L3Zhci1pbnB1dD5cbiAgICA8dmFyLWlucHV0IHZhcmlhbnQ9XCJvdXRsaW5lZFwiIHBsYWNlaG9sZGVyPVwi5pyA5aSn6ZW/5bqmXCIgOm1heGxlbmd0aD1cIjEwXCIgdi1tb2RlbD1cInZhbHVlOFwiIC8+XG4gICAgPHZhci1pbnB1dCB2YXJpYW50PVwib3V0bGluZWRcIiBwbGFjZWhvbGRlcj1cIuaWh+acrOWfn1wiIHRleHRhcmVhIHYtbW9kZWw9XCJ2YWx1ZTlcIiAvPlxuICAgIDx2YXItaW5wdXQgdmFyaWFudD1cIm91dGxpbmVkXCIgcGxhY2Vob2xkZXI9XCLlsI/lsLrlr7hcIiBzaXplPVwic21hbGxcIiB2LW1vZGVsPVwidmFsdWUxMFwiIC8+XG4gIDwvdmFyLXNwYWNlPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLnByZXBlbmQtaWNvbiB7XG4gIG1hcmdpbi1yaWdodDogNnB4O1xufVxuXG4uYXBwZW5kLWljb24ge1xuICBtYXJnaW4tbGVmdDogNnB4O1xufVxuPC9zdHlsZT4iLCJBcHBXcmFwcGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YXJsZXRDc3MgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpQDIuMTguMy9lcy9zdHlsZS5jc3MnXG5jb25zdCB2YXJsZXRUb3VjaEVtdWxhdG9yID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC90b3VjaC1lbXVsYXRvckAyLjE4LjMvaWlmZS5qcydcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgY29uc3Qgc2NyaXB0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0JylcbiAgc2NyaXB0LnNyYyA9IHZhcmxldFRvdWNoRW11bGF0b3JcbiAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChzY3JpcHQpXG5cbiAgaWYgKHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xhc3NMaXN0LmNvbnRhaW5zKCdkYXJrJykpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKFZhcmxldFVJLlRoZW1lcy5kYXJrKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKGRhdGEudmFsdWUgPT09ICdkYXJrJyA/IFZhcmxldFVJLlRoZW1lcy5kYXJrIDogbnVsbClcbiAgICB9XG4gIH0pXG5cbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gICAgd2luZG93LnBhcmVudC5kb2N1bWVudC5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnY2xpY2snKSlcbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9IHZhcmxldENzc1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy4zLjgvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aUAyLjE4LjMvZXMvdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIixcbiAgICBcInZ1ZS9zZXJ2ZXItcmVuZGVyZXJcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2VydmVyLXJlbmRlcmVyQDMuMy44L2Rpc3Qvc2VydmVyLXJlbmRlcmVyLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcIlByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59In0=](url)

在添加带有icon的input框placeholder内容不会上移

**Comment by haoziqaq** [comment]
这个行为源自于我们的交互设计，在使用前置图标时，placeholder 将永远会处于漂浮的状态。因为前置插槽的尺寸大小是可大可小的，placeholder 的漂浮动画会十分的不协调，这个设计也参考了 MUI。
