### ISSUE TITLE
popperjs路径报错

### ISSUE THREAD

**Issue by Ryokutouto** [varletjs/varlet#1285]
空项目安装如下插件后启动报错：
![image](https://github.com/varletjs/varlet/assets/44834187/38a872cf-712f-4195-968f-4cf546cdf5b3)
![image (1)](https://github.com/varletjs/varlet/assets/44834187/e04800db-cc24-4bff-819a-a6527076aeb3)

**Comment by Ryokutouto** [comment]
重新安装popperjs后已解决 `npm install @popperjs/core`

**Comment by haoziqaq** [comment]
pnpm 建议在 .npmrc 下添加 `shamefully-hoist=true`，来解决应用开发中遇到的依赖问题。

**Comment by Ryokutouto** [comment]
![image (2)](https://github.com/varletjs/varlet/assets/44834187/7e8fef1b-ff14-4a8f-8bb8-49874bf8228a)
用到的是npm

**Comment by haoziqaq** [comment]
好的～
