### ISSUE TITLE
var-dialog  警告BUG

### ISSUE THREAD

**Issue by eric134679** [varletjs/varlet#1295]
<var-dialog :show="show">
    <template #title>
      <var-icon name="information" color="#2979ff" />
    </template>

    <var-cell>兰亭临帖 行书如行云流水</var-cell>
    <var-cell>兰亭临帖 行书如行云流水</var-cell>
    <var-cell>兰亭临帖 行书如行云流水</var-cell>
  </var-dialog>

const show = ref(false)

弹出警告 

[Vue warn]: Invalid VNode type: undefined (undefined) 
  at <Dialog show=false > 
  at <User onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

![image](https://github.com/varletjs/varlet/assets/69500455/2fb87764-027f-44aa-8a10-fd95093ecf6c)

并且页面在show 为false 的时候 也是自动打开 弹窗 

![image](https://github.com/varletjs/varlet/assets/69500455/696b87ff-f6ec-4a83-be2d-01a725c3bb4f)

**Comment by haoziqaq** [comment]
可以提供一个更具体的代码示例么？或者通过 https://varlet.gitee.io/varlet-ui-playground/ 给我们反馈

**Comment by eric134679** [comment]
https://github.com/eric134679/varletDlialogBug   这是我的库 直接下载下来 npm run dev 运行即可 在 view 中的 home / index 下我做了一个示例

**Comment by haoziqaq** [comment]
![image](https://github.com/varletjs/varlet/assets/24223652/c0d9b6af-29bc-4c8b-80b7-6643ec985f7b)
自动引入插件 autoImport 选项应该在 auto-import 插件中开启。

**Comment by eric134679** [comment]
非常感谢 我的问题

**Comment by haoziqaq** [comment]
不客气不客气～～
