### ISSUE TITLE
var-select能支持搜索吗，如果有很多项感觉就没法用了呀~

### ISSUE THREAD

**Issue by chinayzq** [varletjs/varlet#1311]
如题~

**Comment by chouchouji** [comment]
I think it is a good idea, we will talk about it.

**Comment by haoziqaq** [comment]
varlet 本身还是一个主要侧重移动端的组件库，大数据量的选项可以使用 Picker 组件去处理。

**Comment by chouchouji** [comment]
> varlet 本身还是一个主要侧重移动端的组件库，大数据量的选项可以使用 Picker 组件去处理。

I remember this picker cannot be used to search.

**Comment by haoziqaq** [comment]
移动端场景大数据量选项的处理方式和中后台是有区别的。

**Comment by haoziqaq** [comment]
一般而言，在移动端场景中上百条的数据已经属于大数据量了，Picker 可以很好的处理这个规模的数据量。如果超过这个规模（比方说上万条数据），那就应该有一个单独的搜索页面并结合多个维度的筛选条件去处理了。部分中后台的项目将几万条数据放在一个 select 纯属是向业务和生活妥协，本身并不是一个好的交互设计。

**Comment by chinayzq** [comment]
我觉得有个搜索会更好用啊，几十条数据算大数据量吗，一个个找不是也费劲啊
<img width="298" alt="image" src="https://github.com/varletjs/varlet/assets/16029800/d099ab3e-a978-4ada-867e-d3c25e3dca59">

**Comment by haoziqaq** [comment]
现在主流的移动端组件库大多不支持 select 组件，因为 select 实际上不适合在移动端场景使用，表格组件也是类似的情况。


我们支持 select 则是因为在部分少量数据的场景下使用它会感觉很偷懒很方便，它的存在意义也仅仅如此了。


搜索功能会引入不小的复杂度，我们粗略估计如果新增该特性会新增四五个 api，还需要完善远程获取，和动态创建选项的能力，并且需要引入 input，input 本身也需要支持定制。这会极大增大我们的维护压力，并且移动端场景几乎无法受益。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月23日(周四) 晚上7:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [varletjs/varlet] var-select能支持搜索吗，如果有很多项感觉就没法用了呀~ (Issue #1311)




 
我觉得有个搜索会更好用啊，几十条数据算大数据量吗，一个个找不是也费劲啊
