### ISSUE TITLE
input输入框是否可以加一个前置搜索功能的插槽 

### ISSUE THREAD

**Issue by GU-zhongli** [varletjs/varlet#1320]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by chouchouji** [comment]
可以详细说明一下你的需求嘛，文字或者图片都可

**Comment by zhongli8166** [comment]
![input前置搜索](https://github.com/varletjs/varlet/assets/140705167/edd4e45a-8893-43cb-ba1c-7efbb9cd7a51)

**Comment by haoziqaq** [comment]
类似 input-group 的功能对吗？在 material design system 中比较少见这种多个输入框拼合在一起的设计。可能需要等我们找到合适的设计才会去跟进这个功能。

**Comment by 3512537** [comment]
这个功能确实很重要，尤其是输入手机号码需要选择区号的时候，目前无法用varletUI实现

**Comment by yapengsoft** [comment]
@3512537 
![image](https://github.com/varletjs/varlet/assets/75244754/f821dc45-b5de-4867-9c9a-816c012c2a78)
可以实现  多看组件  利用input prepend-icon插槽以及var-menu-select
