### ISSUE TITLE
var-bottom-navigation  safe-area 在ios中的bug

### ISSUE THREAD

**Issue by jinghaiying** [varletjs/varlet#1323]
# Bug report 🐞
var-bottom-navigation  safe-area 在ios中的bug
测试环境，系统safari，Chrome 正常，在某些软件内置的webview中出现只有拉倒页面底部才会有

https://github.com/varletjs/varlet/assets/11806767/07e6a251-8bb2-4470-9473-138ebaa68f86

## Version & Environment
```json
"@varlet/ui": "^2.19.2",
"vite": "^5.0.0"
"vue": "^3.3.8"
```

**Comment by jinghaiying** [comment]
代码
```html
  <var-bottom-navigation fixed :active="active" @change="active=$event as number" safe-area>
    <var-bottom-navigation-item :label="item.label()" :icon="item.icon" :namespace="item.namespace"
                                v-for="(item, index) in ProjectConfig.TabBarConfig" :key="index"
                                @click="router.push(item.router)"/>
  </var-bottom-navigation>
```

**Comment by chouchouji** [comment]
可以提供下 ios safari的 型号嘛？

**Comment by jinghaiying** [comment]
> 可以提供下 ios safari的 型号嘛？

在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的

**Comment by chouchouji** [comment]
> > 可以提供下 ios safari的 型号嘛？
> 
> 在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的

我现在手头没有苹果手机，没办法试试你说的这个，你说的源码是varlet的嘛？

**Comment by jinghaiying** [comment]
> > > 可以提供下 ios safari的 型号嘛？
> > 
> > 
> > 在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的
> 
> 我现在手头没有苹果手机，没办法试试你说的这个，你说的源码是varlet的嘛？

是啊，加班赶项目呢[破涕为笑]

**Comment by chouchouji** [comment]
> > > > 可以提供下 ios safari的 型号嘛？
> > > 
> > > 
> > > 在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的
> > 
> > 
> > 我现在手头没有苹果手机，没办法试试你说的这个，你说的源码是varlet的嘛？
> 
> 是啊，加班赶项目呢[破涕为笑]

其实这个很简单，就是加了一点 `padding-bottom`
![image](https://github.com/varletjs/varlet/assets/70570907/42595b1b-d082-4f67-99ff-278885f70522)

**Comment by haoziqaq** [comment]
实现和 ua 无关，使用的是 ios 内置的 css var 实现的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月28日(周二) 晚上8:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [varletjs/varlet] var-bottom-navigation  safe-area 在ios中的bug (Issue #1323)




     
可以提供下 ios safari的 型号嘛？
  
在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的
  
我现在手头没有苹果手机，没办法试试你说的这个，你说的源码是varlet的嘛？
  
是啊，加班赶项目呢[破涕为笑]
  
其实这个很简单，就是加了一点 padding-bottom
 image.png (view on web)

**Comment by jinghaiying** [comment]
> > > > > 可以提供下 ios safari的 型号嘛？
> > > > 
> > > > 
> > > > 在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的
> > > 
> > > 
> > > 我现在手头没有苹果手机，没办法试试你说的这个，你说的源码是varlet的嘛？
> > 
> > 
> > 是啊，加班赶项目呢[破涕为笑]
> 
> 其实这个很简单，就是加了一点 `padding-bottom` ![image](https://private-user-images.githubusercontent.com/70570907/286245696-42595b1b-d082-4f67-99ff-278885f70522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNzQ5MjIsIm5iZiI6MTcwMTE3NDYyMiwicGF0aCI6Ii83MDU3MDkwNy8yODYyNDU2OTYtNDI1OTViMWItZDA4Mi00ZjY3LTk5ZmYtMjc4ODg1ZjcwNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEyMzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzQ2M2Y5ZDNlMjBkODQ0OGM5MTViNTUxYjcxMGVmZWM2MWYyMzdjMTM1MWE4YzdkOTRkNTYzMTdjZjM2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._iZ2D0WjAxKcdifMhho525nSOGenpnhFbkyPIpNCeL4)

嗯，根据系统的不同添加不同的 padding，就是不知道你是不是根据 ua 判断的系统，因为某些特殊环境ua是不提供系统环境的，例如，我自己封装的 App，内嵌的 iOS 的webview，ua 是我自己定义的，那就会导致出现问题，例如上面视频的问题，其实我加不加安全区域等于 true，效果是一样的

**Comment by jinghaiying** [comment]
> 实现和 ua 无关，使用的是 ios 内置的 css var 实现的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月28日(周二) 晚上8:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [varletjs/varlet] var-bottom-navigation safe-area 在ios中的bug (Issue #1323) 可以提供下 ios safari的 型号嘛？ 在 ios17，16，系统自带Safari 测试是通过的，在某些 App 内嵌的webview 中复现的这个问题，你可以通过区块链钱包的 TP Wallet复现这个 bug，不过 iOS 需要海外账户才能下载，我没来的及看源码，不知道适配安全区域是不是通过 ua 来实现的 我现在手头没有苹果手机，没办法试试你说的这个，你说的源码是varlet的嘛？ 是啊，加班赶项目呢[破涕为笑] 其实这个很简单，就是加了一点 padding-bottom image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

这个就不知道具体问题点了，我不是大前端，回头我研究下这个问题，我有时间去看看iOSwebview 的实现方式，先用有替代方案，暂时先跑项目
