### ISSUE TITLE
var-bottom-navigation-item 设置自定义icon 苹果手机无效呢

### ISSUE THREAD

**Issue by zoujianliang1994** [varletjs/varlet#1327]
# Bug report 🐞

## Version & Environment
   2.19.1
## Expectation
 <var-bottom-navigation inactive-color="#333" active-color="#5661d7" :safe-area="true" :border="true"
      v-model:active="active" @change="handleChange" :fab-props="{
        text: false,
        type: 'primary',
        color: '#fff',
      }" @fab-click="fabClick">
      <var-bottom-navigation-item name="/GaokaoMessage" label="高考信息">
        <template #icon>
          <var-icon v-if="active == '/GaokaoMessage'" namespace="my-icon3" name="gaokaozhishi" size="32" />
          <var-icon v-else namespace="my-icon3" name="a-gaokaozhishiweixuanzhong" size="32" />
        </template>
      </var-bottom-navigation-item>
      <var-bottom-navigation-item name="/PublicService" label="公共服务">
        <template #icon>
          <var-icon v-if="active == '/PublicService'" namespace="my-icon3" name="a-gonggongfuwuxuanzhong" size="32" />
          <var-icon v-else namespace="my-icon3" name="a-gonggongfuwuweixuanzhong1" size="32" />
        </template>
      </var-bottom-navigation-item>
      <var-bottom-navigation-item name="/PersonalCenter" label="个人中心">
        <template #icon>
          <div id="intro_titl" />
          <var-icon v-if="active == '/PersonalCenter'" namespace="my-icon3" name="geren" size="32" />
          <var-icon v-else namespace="my-icon3" name="a-gerenweixuanzhong" size="32" />
        </template>
      </var-bottom-navigation-item>
      <var-bottom-navigation-item label="标签" icon="account-circle" />
    </var-bottom-navigation>
## Actual results (or Errors)
苹果手机无效呢 安卓手机显示正常
## Reproduction link
项目展示地址https://card.gaozhaotong.cn/
iconfont文件https://at.alicdn.com/t/c/font_4295705_gp9d458ysq6.css

**Comment by zoujianliang1994** [comment]
<var-bottom-navigation inactive-color="#333" active-color="#5661d7" :safe-area="true" :border="true"
      v-model:active="active" @change="handleChange" :fab-props="{
        text: false,
        type: 'primary',
        color: '#fff',
      }" @fab-click="fabClick">
      <var-bottom-navigation-item name="/GaokaoMessage" label="高考信息">
        <template #icon>
          <var-icon v-if="active == '/GaokaoMessage'" namespace="my-icon3" name="gaokaozhishi" size="32" />
          <var-icon v-else namespace="my-icon3" name="a-gaokaozhishiweixuanzhong" size="32" />
        </template>
      </var-bottom-navigation-item>
      <var-bottom-navigation-item name="/PublicService" label="公共服务">
        <template #icon>
          <var-icon v-if="active == '/PublicService'" namespace="my-icon3" name="a-gonggongfuwuxuanzhong" size="32" />
          <var-icon v-else namespace="my-icon3" name="a-gonggongfuwuweixuanzhong1" size="32" />
        </template>
      </var-bottom-navigation-item>
      <var-bottom-navigation-item name="/PersonalCenter" label="个人中心">
        <template #icon>
          <div id="intro_titl" />
          <var-icon v-if="active == '/PersonalCenter'" namespace="my-icon3" name="geren" size="32" />
          <var-icon v-else namespace="my-icon3" name="a-gerenweixuanzhong" size="32" />
        </template>
      </var-bottom-navigation-item>
      <var-bottom-navigation-item label="标签" icon="account-circle" />
    </var-bottom-navigation>

**Comment by chouchouji** [comment]
今天晚上我看下

**Comment by chouchouji** [comment]
我感觉是你 icon 没有用对 ，这个插槽没问题的
![image](https://github.com/varletjs/varlet/assets/70570907/5c0092b1-e823-4097-8e2b-d8a3dc234f53)

**Comment by haoziqaq** [comment]
抛开 bottom navigation，直接使用自定义的 namespace icon 是否有效呢？

**Comment by zoujianliang1994** [comment]
> 我感觉是你 icon 没有用对 ，这个插槽没问题的 ![image](https://private-user-images.githubusercontent.com/70570907/287215687-5c0092b1-e823-4097-8e2b-d8a3dc234f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NDk1NzYsIm5iZiI6MTcwMTY0OTI3NiwicGF0aCI6Ii83MDU3MDkwNy8yODcyMTU2ODctNWMwMDkyYjEtZTgyMy00MDk3LThlMmItZDhhM2RjMjM0ZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAwMjExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMTVkYWNhODVmMWE4OGVhMzdjMWJlZDE3OWI4NDQ5YWNhMzc1NTZjYjkzZTA2ZDAwZjdiNWEzMWJhNDdlOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vwaDLbsYdICvqoUsO3GDQlGgJXAS8m4CttqlHlNzPBo)

我其他地方 用的是有效果得 而且安卓手机也没问题
