### ISSUE TITLE
pull-refresh 组件，可以自定义开始刷新、正在刷新、刷新完成的展示文案

### ISSUE THREAD

**Issue by David-TechNomad** [varletjs/varlet#1328]
# Bug report 🐞 pull-refresh 组件，可以自定义开始刷新、正在刷新、刷新完成的展示文案

## pull-refresh 组件，可以自定义开始刷新、正在刷新、刷新完成的展示文案
![image](https://github.com/varletjs/varlet/assets/23149356/f95dbb35-2ac9-46bb-aad3-101a0f3684a4)

**Comment by haoziqaq** [comment]
目前 material design 中少有这样的 UI 设计，可能需要后续深入讨论一下。
