### ISSUE TITLE
MD 风格的 层次感和 阴影似乎不太明显

### ISSUE THREAD

**Issue by cctyl** [varletjs/varlet#1342]
# About `styles` 🛠️
一点小建议，感觉部分组件的层次和阴影感觉不是很明显，偏平面化。（也可能是我对这个的理解不是很到位。。。）
参考资料[Material](https://www.mdui.org/design/material-design/elevation-shadows.html#elevation-shadows-shadows).

**Comment by chouchouji** [comment]
可以举个具体的组件例子吗？

目前据我所知，大多数组件的 elevation 的 默认值是 2 或者 3

![image](https://github.com/varletjs/varlet/assets/70570907/f6379141-8a6e-4e4e-bf7a-a4b3a00f340a)，值越大效果就越明显

[elevation](https://varlet.gitee.io/varlet-ui/#/en-US/styles)
