### ISSUE TITLE
包内容变了

### ISSUE THREAD

**Issue by jiarouy** [varletjs/varlet#1353]
# Bug report 🐞
![image](https://github.com/varletjs/varlet/assets/28084783/dde0d508-05f6-40b4-9c21-b2433d1b2e14)
兄弟 这包怎么变这样了（左边） 全报错了
## Version & Environment
2.20.*
## Expectation
无
## Actual results (or Errors)
无
## Reproduction link
无

**Comment by haoziqaq** [comment]
感谢反馈，似乎是周五晚上发布的 2.20.1 版本出现了发布中断的情况（但未出现报错日志）。 我又补发了一个 2.20.2 版本作为替代。2.20.1 版本将被打上 deprecated 标记。
