### ISSUE TITLE
希望popup组件在overlay属性为false的时候，鼠标点击能够穿透

### ISSUE THREAD

**Issue by cy99** [varletjs/varlet#1407]
<template>
  <var-button @click="click">弹出</var-button>
  <var-popup overlay="overlay" position="right" v-model:show="top">
    <div class="popup-example-block">
      素胚勾勒出青花笔锋浓转淡,
      瓶身描绘的牡丹一如你初妆,
      冉冉檀香透过窗心事我了然,
      宣纸上走笔至此搁一半。
    </div>
  </var-popup>
</template>

<script>
export default {
  data() {
    return {
      top: false,
      overlay: false
    };
  },
  methods: {
    click() {
      this.top = true
    }
  }
};
</script>

<style>
.popup-example-block {
  padding: 20px 24px;
  width: 250px;
}
</style>

**Comment by chouchouji** [comment]
这个估计要添加一个popup-style 属性，手动设置 `pointer-events: none`，[链接](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbiAgXG5jb25zdCBvdmVybGF5U3R5bGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLXNwYWNlIGRpcmVjdGlvbj1cImNvbHVtblwiIDpzaXplPVwiWzEwLCAwXVwiPlxuICAgIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgYmxvY2s+XG4gICAgICDpga7nvanlsYIgY2xhc3NcbiAgICA8L3Zhci1idXR0b24+XG4gICAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIiBibG9jayBAY2xpY2s9XCJvdmVybGF5U3R5bGUgPSB0cnVlXCI+XG4gICAgICDpga7nvanlsYIgc3R5bGVcbiAgICA8L3Zhci1idXR0b24+XG4gIDwvdmFyLXNwYWNlPlxuICBcbiAgPHZhci1wb3B1cFxuICAgIDpvdmVybGF5LXN0eWxlPVwie2JhY2tncm91bmRDb2xvcjogJ3JlZCcsIG9wYWNpdHk6ICcwLjEnIH1cIlxuICAgIHYtbW9kZWw6c2hvdz1cIm92ZXJsYXlTdHlsZVwiXG4gICAgOm92ZXJsYXk9XCJmYWxzZVwiXG4gID5cbiAgICA8ZGl2IGNsYXNzPVwicG9wdXAtZXhhbXBsZS1ibG9ja1wiPlxuICAgICAg57Sg6IOa5Yu+5YuS5Ye66Z2S6Iqx56yU6ZSL5rWT6L2s5rehLFxuICAgICAg55O26Lqr5o+P57uY55qE54mh5Li55LiA5aaC5L2g5Yid5aaGLFxuICAgICAg5YaJ5YaJ5qqA6aaZ6YCP6L+H56qX5b+D5LqL5oiR5LqG54S2LFxuICAgICAg5a6j57q45LiK6LWw56yU6Iez5q2k5pCB5LiA5Y2K44CCXG4gICAgPC9kaXY+XG4gIDwvdmFyLXBvcHVwPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLnBvcHVwLWV4YW1wbGUtYmxvY2sge1xuICBwYWRkaW5nOiAyMHB4IDI0cHg7XG4gIHdpZHRoOiAyNTBweDtcbn1cbjwvc3R5bGU+XG4iLCJBcHBXcmFwcGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YXJsZXRDc3MgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3N0eWxlLmNzcydcbmNvbnN0IHZhcmxldFRvdWNoRW11bGF0b3IgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3RvdWNoLWVtdWxhdG9yL2lpZmUuanMnXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGNvbnN0IHNjcmlwdCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3NjcmlwdCcpXG4gIHNjcmlwdC5zcmMgPSB2YXJsZXRUb3VjaEVtdWxhdG9yXG4gIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoc2NyaXB0KVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4ge1xuICAgIHdpbmRvdy5wYXJlbnQuZG9jdW1lbnQuZGlzcGF0Y2hFdmVudChuZXcgRXZlbnQoJ2NsaWNrJykpXG4gIH0pXG5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoVmFybGV0VUkpXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBhcHBlbmRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSB2YXJsZXRDc3NcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiQHZhcmxldC91aVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aS9lcy92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiLi92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJQcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufSJ9)
![image](https://github.com/varletjs/varlet/assets/70570907/d939e469-80c5-41f1-a6db-2915c0e26cb4)
