### ISSUE TITLE
var-bottom-navigation组件是怎么切换路由的

### ISSUE THREAD

**Issue by kuailingmin** [varletjs/varlet#1410]
# Bug report 🐞
var-bottom-navigation组件没有一个配置切换路由的操作
## Version & Environment
v2.20.0

**Comment by haoziqaq** [comment]
组件没有和 vue-router 耦合在一起。您可以通过监听 change 或 click 事件实现切换。

**Comment by chouchouji** [comment]
https://github.com/varletjs/varlet-app-template/blob/main/src/pages/layout.vue
