### ISSUE TITLE
在nuxt3中使用lazy指令报错

### ISSUE THREAD

**Issue by yapengsoft** [varletjs/varlet#1443]
# Bug report 🐞
https://stackblitz.com/edit/github-hxrjyc
请问如何在nuxt3中正确使用lazy指令？

**Comment by haoziqaq** [comment]
@zhangmo8

**Comment by zhangmo8** [comment]
> # Bug report 🐞
> 
> https://stackblitz.com/edit/github-hxrjyc
> 
> 请问如何在nuxt3中正确使用lazy指令？
> 
> 

指令暂时还没做，请等待下一个版本发布哈

**Comment by yapengsoft** [comment]
原来如此  辛苦你们了  静候佳音

**Comment by zhangmo8** [comment]
> 原来如此  辛苦你们了  静候佳音

暂时可以手动导入使用， 后续新版本发布我在回这个issue更新

**Comment by yapengsoft** [comment]
好的 谢谢

**Comment by zhangmo8** [comment]
已经好啦，升级到 [0.0.5](https://www.npmjs.com/package/@varlet/nuxt) 版本就好啦

@yapengsoft

**Comment by yapengsoft** [comment]
@haoziqaq @zhangmo8 谢谢
