### ISSUE TITLE
想自定义样式

### ISSUE THREAD

**Issue by cy920324** [varletjs/varlet#1445]
# About `styles` 🛠️
咱们的组件库质量很高，想基于咱们的组件库做定制样式，设计稿很多样式都不一样，请问有文章介绍这块吗？

想复用组件逻辑，部分样式对标公司内部的设计稿样式

**Comment by chouchouji** [comment]
varlet 提供了 [https://varlet.gitee.io/varlet-ui/#/zh-CN/style-provider](https://varlet.gitee.io/varlet-ui/#/zh-CN/style-provider) 组件，可对每个 组件 进行样式定制。组件同时提供了 插槽，方便使用者定制化。

**Comment by cy920324** [comment]
这是来自邮箱的自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
