### ISSUE TITLE
@varlet/touch-emulator和高德地图冲突

### ISSUE THREAD

**Issue by zzs89117920** [varletjs/varlet#1447]
# Bug report 🐞
@varlet/touch-emulator和高德地图冲突
## Version & Environment
2.22.0
## Expectation
 Cannot read properties of undefined (reading 'clientX')

## Reproduction link
![image](https://github.com/varletjs/varlet/assets/5515847/29adfe1c-fdd1-4971-94de-0ff38cef6f56)

**Comment by haoziqaq** [comment]
方便的话，能否提供一个 demo。或者更多的堆栈信息，目前在 touch-emulator 中未发现问题。

**Comment by zzs89117920** [comment]
> 方便的话，能否提供一个 demo。或者更多的堆栈信息，目前在 touch-emulator 中未发现问题。

[varlet-amap-test.zip](https://github.com/varletjs/varlet/files/14071219/varlet-amap-test.zip)
这是测试文件，地图代码在app.vue里，地图key不方便提供，main.js里引用了touch-emulator，运行起来点击地图就出现上述错误

**Comment by haoziqaq** [comment]
嗯好的，暂时定位到了问题。尝试修复之后会给你一个修复后的版本。

**Comment by haoziqaq** [comment]
可以提前尝试预览版本 2.22.1-alpha.1706370837642，该变更将包含在下一个正式 patch 版本中
