### ISSUE TITLE
上传组件在安卓13中丢失exif信息中的gps信息

### ISSUE THREAD

**Issue by zzs89117920** [varletjs/varlet#1453]
# Bug report 🐞

## Version & Environment
2.22.0
## Expectation
上传组件在安卓13中丢失exif信息中的gps信息
## Reproduction link
由于使用模拟点击方式触发input file，在一些手机中，由于安全原因导致exif中的gps信息在前端不能读取，返回NaN，而正常的input file，的onchange方式是可以读取的

**Comment by chouchouji** [comment]
方便提供下用于测试的图片吗？

**Comment by haoziqaq** [comment]
可能你需要使用手机照相机拍摄到的图片进行上传，pc 的照片不一定有 exif 信息。

**Comment by chouchouji** [comment]
> 可能你需要使用手机照相机拍摄到的图片进行上传，pc 的照片不一定有 exif 信息。

手机拍的照片我试了，没有相关信息
![image](https://github.com/varletjs/varlet/assets/70570907/425b4b27-936a-4223-9926-50a9e2a37dc3)

**Comment by zzs89117920** [comment]
用的exif-reader库，发现下列代码在安卓13中是可以获取到，而用上传组件却获取不到
  document.getElementById('btnChooseFile').addEventListener('click', e => {
    document.getElementById('upload').click()
  })

  document.getElementById('upload').addEventListener('change', async e => {
    const file = e.target.files[0]
    const tags = await ExifReader.load(file)
    for (let key of Object.keys(tags)) {
      if (key == 'GPSLatitude') {
        document.getElementById('content').innerHTML = key + ':' + JSON.stringify(tags[key]) + '<br>'
      }
    }
  })

**Comment by haoziqaq** [comment]
上传组件有相应的案例代码么，因为我看您提供的代码也是使用 click() 的方式使 input 触发上传

**Comment by zzs89117920** [comment]
> 上传组件有相应的案例代码么，因为我看您提供的代码也是使用 click() 的方式使 input 触发上传

一开始我以为是模拟点击的问题，后来发现用原生js可以用，稍等我下个简单的demo

**Comment by zzs89117920** [comment]
> 上传组件有相应的案例代码么，因为我看您提供的代码也是使用 click() 的方式使 input 触发上传

这是例子，上传组件和原生都有，又测试了一下，安卓13里原生是好使的
[varlet-test.zip](https://github.com/varletjs/varlet/files/14082032/varlet-test.zip)

**Comment by zzs89117920** [comment]
> > 可能你需要使用手机照相机拍摄到的图片进行上传，pc 的照片不一定有 exif 信息。
> 
> 手机拍的照片我试了，没有相关信息 ![image](https://private-user-images.githubusercontent.com/70570907/300390586-425b4b27-936a-4223-9926-50a9e2a37dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTkzNzQsIm5iZiI6MTcwNjUxOTA3NCwicGF0aCI6Ii83MDU3MDkwNy8zMDAzOTA1ODYtNDI1YjRiMjctOTM2YS00MjIzLTk5MjYtNTBhOWUyYTM3ZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZDdmNTBhMmUzZjAwMjEzYjA5YWE4ZjY4ZTYwNjZiODI4ZWFmOTFlNjBiOTA4ODBhYTA5ZjAwMDc0ZmI1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4xdhuFPDcGeFbkM6Cf0dNVmwDR5VjlTG6Ln2JFSh8pE)



> 方便提供下用于测试的图片吗？原生input框我也没能获取exif信息，不是很确定是不是我上传的图片有问题 ![image](https://private-user-images.githubusercontent.com/70570907/300388726-9dac5bf6-768e-4669-9281-caf986c5cc59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTkzNzQsIm5iZiI6MTcwNjUxOTA3NCwicGF0aCI6Ii83MDU3MDkwNy8zMDAzODg3MjYtOWRhYzViZjYtNzY4ZS00NjY5LTkyODEtY2FmOTg2YzVjYzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDIzMjhjZjkxY2JkOWJiN2ZiMmZkZTdjMzkxNTg3NGYxMjhhZjk3NzAzYzMzMTc3ZTgzYTVmZDFmNjU2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZfV69Aa1UUnWJMdc4O20lr6RcCWBlkyGz4Kgise9bb8) https://www.lilnong.top/static/html/exif.html



> 方便提供下用于测试的图片吗？原生input框我也没能获取exif信息，不是很确定是不是我上传的图片有问题 ![image](https://private-user-images.githubusercontent.com/70570907/300388726-9dac5bf6-768e-4669-9281-caf986c5cc59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTk1NDMsIm5iZiI6MTcwNjUxOTI0MywicGF0aCI6Ii83MDU3MDkwNy8zMDAzODg3MjYtOWRhYzViZjYtNzY4ZS00NjY5LTkyODEtY2FmOTg2YzVjYzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZWQ2NzRjYTI3ZmNhN2EzMzFkMzhmNWE1OGNjYjI0NWI4YTU2NDk0NmFiYTI4Y2EwODY1YzA0M2YwYmVjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p0jIyr0UJupVr-PmZX7HmYRZrLWgh9QxlD2EabrNAAg) https://www.lilnong.top/static/html/exif.html

不能用微信传图，只要用微信传图，微信就把exif信息删除了

**Comment by haoziqaq** [comment]
"原生是好使的"的意思是指，使用原生 input 的情况下，`click()` 和`正常用户点击触发选取文件`都是可以拿到 gps 信息的是吗？

**Comment by zzs89117920** [comment]
> "原生是好使的"的意思是指，使用原生 input 的情况下，`click()` 和`正常用户点击触发选取文件`都是可以拿到 gps 信息的是吗？

是的，点击按钮模拟input的click和用户点击触发选取文件在onchange里都能拿到gps信息

**Comment by zzs89117920** [comment]
找到问题了，在安卓13中，input的accept只要设置成image，就会丢失gps的经纬度，如果不限制类型就可以
