### ISSUE TITLE
can't auto import styles of var functions

### ISSUE THREAD

**Issue by LoTwT** [varletjs/varlet#1473]
# Bug report 🐞

can't auto import styles of var functions like `LoadingBar`、`Dialog`.

please check [here](https://github.com/varletjs/varlet/blob/d3e5c924b11dc1ada787794a03f8ceec6f167252/packages/varlet-import-resolver/src/index.ts#L62)

## Version & Environment

- System:
    - OS: Linux 5.0 undefined
    - CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    - Memory: 0 Bytes / 0 Bytes
    - Shell: 1.0 - /bin/jsh
- Binaries:
    - Node: 18.18.0 - /usr/local/bin/node
    - Yarn: 1.22.19 - /usr/local/bin/yarn
    - npm: 10.2.3 - /usr/local/bin/npm
    - pnpm: 8.14.0 - /usr/local/bin/pnpm
-  npmPackages:
    - vue: ^3.4.19 => 3.4.19 
    - "@varlet/ui": "^3.0.3"
    - "@varlet/import-resolver": "^3.0.3"
    - "unplugin-auto-import": "^0.17.5"
    - "unplugin-vue-components": "^0.26.0"
    - "vite": "^5.1.3"
    - "typescript": "^5.2.2"

## Expectation

succeed to auto import styles with `unplugin-auto-import` and `unplugin-vue-components`

## Actual results (or Errors)

miss imports of style files

## Reproduction link

https://stackblitz.com/edit/vitejs-vite-gvw1gd?file=src%2FApp.vue

**Comment by haoziqaq** [comment]
`unplugin-auto-import` does not support auto import of inline function in template.

you can change to

```html
<script setup>
function show() {
  Dialog('dialog content')
}
</script>

<template>
  <var-button type="primary" @click="show">dialog show</var-button>
</template>
```

**Comment by LoTwT** [comment]
> ```
> <var-button type="primary" @click="show">dialog show</var-button>
> ```

I change the repro with the codes shown above. It still doesn't work. 😢

**Comment by haoziqaq** [comment]
before

```
import { LoadingBar, Dialog } from '@varlet/ui';
```

after

```
import { LoadingBar } from '@varlet/ui';
```

**Comment by LoTwT** [comment]
🤣 Without explicit imports, my vs code will show errors. After waiting for more seconds, it works.
♥️ Thank you.
