### ISSUE TITLE
关于按钮在pc端的样式问题

### ISSUE THREAD

**Issue by kdreaming** [varletjs/varlet#1486]
# question
按钮在PC端浏览器点击后总会保持在悬浮状态的样式，有没有办法避免这一点，与移动端的表现一致
## Version & Environment
windows10 edge浏览器

**Comment by haoziqaq** [comment]
我们最近在做对 pc 的交互性优化，pc 的按钮点击之后按钮将保持 focus 的状态是预期行为。如果不希望有 ui 上的 focus 反馈，可以尝试设置 --opacity-focus 这个变量。

**Comment by haoziqaq** [comment]
两种方案
1. 只希望按钮禁用 focus 的 ui 反馈
```html
<var-button style="--hover-overlay-focusing-opacity: 0">按钮</var-button>
```

3.整个组件库都禁用 focus 的 ui 反馈
```js
StyleProvider({
  ...Themes.md3Dark,
  '--opacity-focus': '0'
})
```

**Comment by kdreaming** [comment]
> 两种方案
> 
> 1. 只希望按钮禁用 focus 的 ui 反馈
> 
> ```
> <var-button style="--hover-overlay-focusing-opacity: 0">按钮</var-button>
> ```
> 
> 2.整个组件库都禁用 focus 的 ui 反馈
> 
> ```js
> StyleProvider({
>   ...Themes.md3Dark,
>   '--opacity-focus': '0'
> })
> ```

感谢你的回复，这样就解决了。
但是又遇到了两个新的问题
1. 我在main.js中引入了项目自定义的css文件，内部定义了:root { '--color-primary': '#3afe3d' },但是会被varlet的默认样式覆盖掉
2. 当button设置属性outline的时候好像没有属性设置一个背景颜色

再次感谢

**Comment by haoziqaq** [comment]
1. 可以通过下面的方式增加权重
```css
:root:root {
  '--color-primary': '#3afe3d'
}
```
2. outline 按钮本质是文字加外边框，不属于有背景颜色的按钮，这个可能超出了 css-var 定制的范畴，建议使用 css 样式覆盖的方式进行定制。

**Comment by kdreaming** [comment]
> 1. 可以通过下面的方式增加权重
> 
> ```css
> :root:root {
>   '--color-primary': '#3afe3d'
> }
> ```
> 
> 2. outline 按钮本质是文字加外边框，不属于有背景颜色的按钮，这个可能超出了 css-var 定制的范畴，建议使用 css 样式覆盖的方式进行定制。

感谢，我将关闭这个issue
