### ISSUE TITLE
升级@varlet/nuxt 版本至0.0.5后样式错乱

### ISSUE THREAD

**Issue by yapengsoft** [varletjs/varlet#1511]
# Bug report 🐞
将@varlet/nuxt 版本至0.0.5后样式组件样式全乱套，@varlet/ui 使用版本为2.22.3
改用0.0.4版本正常
找了一上午的问题...

**Comment by zhangmo8** [comment]
fixing

**Comment by zhangmo8** [comment]
Hi @yapengsoft ，我没法复现，这个样式问题，方便提供一个最小的可复现repo嘛，或者可以加入社区群联系我

**Comment by zhangmo8** [comment]
> Hi @yapengsoft ，我没法复现，这个样式问题，方便提供一个最小的可复现repo嘛，或者可以加入社区群联系我

我在 Appbar 以及 bottom navigation 组件上复现了它，如果你有其他组件有同样的问题，请更新在这个 issues 里

**Comment by zhangmo8** [comment]
fixed. 升级到 最新版本则可。

感谢你的反馈，同时欢迎参与贡献 @yapengsoft

**Comment by yapengsoft** [comment]
好  非常感觉  辛苦你了
