### ISSUE TITLE
button 按钮报错

### ISSUE THREAD

**Issue by 4zzzzr** [varletjs/varlet#1525]
# Bug report 🐞

## Version & Environment
    "@varlet/ui": "^3.0.7",
    "vue": "^3.3.11",
## Expectation

使用 button 按钮组件后 报错
https://varlet.gitee.io/varlet-ui/#/zh-CN/button

![image](https://github.com/varletjs/varlet/assets/113667994/43c65d5f-7ce1-4817-a27c-d1a4ec07144f)
![image](https://github.com/varletjs/varlet/assets/113667994/c71c9f0c-7687-428b-a2a6-d2ab5d75eb85)

头都大了

**Comment by 4zzzzr** [comment]
[Vue warn] Write operation failed: computed value is readonly

**Comment by haoziqaq** [comment]
dismiss it. next version will be fixed



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [varletjs/varlet] button 按钮报错 (Issue #1525)




 
[Vue warn] Write operation failed: computed value is readonly

**Comment by 4zzzzr** [comment]
Thank🥰

**Comment by haoziqaq** [comment]
if you want to experience the version early. 3.1.0 alpha version can be installed.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 晚上7:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] button 按钮报错 (Issue #1525)




 
Thank🥰
