### ISSUE TITLE
cdn  var-table不能渲染

### ISSUE THREAD

**Issue by kinbod** [varletjs/varlet#1531]
# Bug report 🐞
用script在页面通过CDN引入varlet.js,,,,var-table组件不能正常渲染展示

**Comment by haoziqaq** [comment]
![image](https://github.com/varletjs/varlet/assets/24223652/d22eeaaf-2bb2-43bf-b888-8720ae35ea9e)
![image](https://github.com/varletjs/varlet/assets/24223652/01056145-2891-4e2a-b15e-19c889221794)
未能复现，建议提供一个最小化可复现的 demo。

**Comment by kinbod** [comment]
> ![image](https://private-user-images.githubusercontent.com/24223652/313211379-d22eeaaf-2bb2-43bf-b888-8720ae35ea9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjgxNjYsIm5iZiI6MTcxMDcyNzg2NiwicGF0aCI6Ii8yNDIyMzY1Mi8zMTMyMTEzNzktZDIyZWVhYWYtMmJiMi00M2JmLWI4ODgtODcyMGFlMzVlYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAyMTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNTgwODQ4MzdiMzcwODJlZDBjNzVkMTBiYjEwZDQxZjQ5ZmE0YWVmYjM4NThmZGUzMjcwODUzZThkMWQzODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYeYc7KndHHvYc0yTmnNmXE77S705zqUsMlf-i9urVI) ![image](https://private-user-images.githubusercontent.com/24223652/313211426-01056145-2891-4e2a-b15e-19c889221794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjgxNjYsIm5iZiI6MTcxMDcyNzg2NiwicGF0aCI6Ii8yNDIyMzY1Mi8zMTMyMTE0MjYtMDEwNTYxNDUtMjg5MS00ZTJhLWIxNWUtMTljODg5MjIxNzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAyMTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTYyNGJiNzYzYzZlODNkOTA5ZjljMTFhMmE4YTIxNWZkYzQ3NGJiMGUxNDE5YmIxNDUwNjk1MGRjYTE0Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nK1O13DqvtlC6oCJhdXqPTnez4RZr88Xyo69pTq_ie8) 未能复现，建议提供一个最小化可复现的 demo。

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://"
            + request.getServerName() + ":" + request.getServerPort()
            + path + "/";
%>
<!DOCTYPE html>
<html>
<head>
    <base href="<%=basePath%>">
    
    <script src="static/varlet/js/vue-v3.4.21.js"></script>
    <script src="static/varlet/js/iife.js"></script>
    <script src="static/varlet/js/varlet.js"></script>
    <script src="static/quasar/js/axios.js"></script>
    <script src="static/js/jquery-3.1.1.min.js"></script>
</head>
<body>
<div id="app">
    <var-row :gutter="[10,10]">
        <%--        <var-col :span="8" direction="row">--%>
        <%--            <var-button type="primary">b1</var-button>--%>
        <%--            <var-button type="info">b1</var-button>--%>
        <%--            <var-button type="success">b1</var-button>--%>
        <%--            <var-button type="warning">b1</var-button>--%>
        <%--            <var-button type="danger">b1</var-button>--%>
        <%--            <var-button loading type="primary">b1</var-button>--%>
        <%--            <var-button loading loading-type="wave" type="primary">b1</var-button>--%>
        <%--        </var-col>--%>
        <var-divider></var-divider>
        <var-col :span="16" direction="row">
            <var-space :size="[10,10]" direction="row">
                <var-input variant="outlined" placeholder="查询1" v-model="userName"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionType"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionNo"></var-input>
                <var-input variant="outlined" placeholder="查询3" v-model="createTime"></var-input>
                <var-button type="primary" style="margin-top: 18px;">查询</var-button>
                <var-button type="danger" style="margin-top: 18px;">重置</var-button>
            </var-space>
        </var-col>
        <var-divider></var-divider>
    </var-row>
    <var-table>
        <thead>
        <tr>
            <th>姓名</th>
            <th>数学</th>
            <th>英语</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>耗子君</td>
            <td>124</td>
            <td>38</td>
        </tr>
        <tr>
            <td>火猫桑</td>
            <td>100</td>
            <td>135</td>
        </tr>
        </tbody>
    </var-table>

</div>

</body>


<script src="plugins/echarts/echarts.js"></script>
<script src="plugins/echarts/vue-echarts-v6.6.5.js"></script>
<script>
    $(top.hangge());
    const API = axios.create({
        baseURL: "<%=basePath%>",
        timeout: 5000
    });

    
    const app = Vue.createApp({
        setup() {
            let userName = Vue.ref(null);
            let versionNo = Vue.ref(null);
            let versionType = Vue.ref(null);
            let createTime = Vue.ref(null);
            debugger
            return {userName, versionType, versionNo, createTime}
        },
        data() {
            return {}
        },
        methods: {},
        mounted() {
        }
    })

    // Varlet.Locale.add('zh-CN','Locale.zhCN');
    // Varlet.Locale.use('zh-CN');
    app.use(Varlet).mount('#app')
</script>
</html>


我这个是用在了jsp的界面中，udm的方式

**Comment by kinbod** [comment]
`<%--
  Created by IntelliJ IDEA.
  User: QUANBQ
  Date: 2024/3/14
  Time: 9:46
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://"
            + request.getServerName() + ":" + request.getServerPort()
            + path + "/";
%>
<!DOCTYPE html>
<html>
<head>
    <base href="<%=basePath%>">
    
    <script src="static/varlet/js/vue-v3.4.21.js"></script>
    <script src="static/varlet/js/iife.js"></script>
    <script src="static/varlet/js/varlet.js"></script>
    <script src="static/quasar/js/axios.js"></script>
    <script src="static/js/jquery-3.1.1.min.js"></script>
</head>
<body>
<div id="app">
    <var-row :gutter="[10,10]">
        <%--        <var-col :span="8" direction="row">--%>
        <%--            <var-button type="primary">b1</var-button>--%>
        <%--            <var-button type="info">b1</var-button>--%>
        <%--            <var-button type="success">b1</var-button>--%>
        <%--            <var-button type="warning">b1</var-button>--%>
        <%--            <var-button type="danger">b1</var-button>--%>
        <%--            <var-button loading type="primary">b1</var-button>--%>
        <%--            <var-button loading loading-type="wave" type="primary">b1</var-button>--%>
        <%--        </var-col>--%>
        <var-divider></var-divider>
        <var-col :span="16" direction="row">
            <var-space :size="[10,10]" direction="row">
                <var-input variant="outlined" placeholder="查询1" v-model="userName"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionType"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionNo"></var-input>
                <var-input variant="outlined" placeholder="查询3" v-model="createTime"></var-input>
                <var-button type="primary" style="margin-top: 18px;">查询</var-button>
                <var-button type="danger" style="margin-top: 18px;">重置</var-button>
            </var-space>
        </var-col>
        <var-divider></var-divider>
    </var-row>
    <var-table>
        <thead>
        <tr>
            <th>姓名</th>
            <th>数学</th>
            <th>英语</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>耗子君</td>
            <td>124</td>
            <td>38</td>
        </tr>
        <tr>
            <td>火猫桑</td>
            <td>100</td>
            <td>135</td>
        </tr>
        </tbody>
    </var-table>

</div>

</body>


<script src="plugins/echarts/echarts.js"></script>
<script src="plugins/echarts/vue-echarts-v6.6.5.js"></script>
<script>
    $(top.hangge());
    const API = axios.create({
        baseURL: "<%=basePath%>",
        timeout: 5000
    });

    
    const app = Vue.createApp({
        setup() {
            let userName = Vue.ref(null);
            let versionNo = Vue.ref(null);
            let versionType = Vue.ref(null);
            let createTime = Vue.ref(null);
            debugger
            return {userName, versionType, versionNo, createTime}
        },
        data() {
            return {}
        },
        methods: {},
        mounted() {
        }
    })

    // Varlet.Locale.add('zh-CN','Locale.zhCN');
    // Varlet.Locale.use('zh-CN');
    app.use(Varlet).mount('#app')
</script>
</html>
`

**Comment by kinbod** [comment]
[Uploading demo.txt…]()

**Comment by haoziqaq** [comment]
实在有点难以阅读。。

**Comment by kinbod** [comment]
这个是在jsp里面加入的。我在试试其他方式

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: haoziqaq ***@***.***>
发送时间: Tuesday, March 19, 2024 2:45:36 PM
收件人: varletjs/varlet ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [varletjs/varlet] cdn var-table不能渲染 (Issue #1531)


实在有点难以阅读。。

―

**Comment by haoziqaq** [comment]
理论上 jsp 也应该没有太大问题，可以看下最终渲染出的 html 长什么样子。

**Comment by kinbod** [comment]
> ![image](https://private-user-images.githubusercontent.com/24223652/313211379-d22eeaaf-2bb2-43bf-b888-8720ae35ea9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDEyODcsIm5iZiI6MTcxMTk0MDk4NywicGF0aCI6Ii8yNDIyMzY1Mi8zMTMyMTEzNzktZDIyZWVhYWYtMmJiMi00M2JmLWI4ODgtODcyMGFlMzVlYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMzE1OTMxY2NhNjcxMGRkM2E0OTNlM2JmNzdhNTUyZDJlNjVmNWY3MzRmOTNhZWFmZjcyMTgzNzMxNmI2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YsZTNW8ojYDeY1PcPajj2TjXAqEUBy6nFuTJBOwqcJk) ![image](https://private-user-images.githubusercontent.com/24223652/313211426-01056145-2891-4e2a-b15e-19c889221794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDEyODcsIm5iZiI6MTcxMTk0MDk4NywicGF0aCI6Ii8yNDIyMzY1Mi8zMTMyMTE0MjYtMDEwNTYxNDUtMjg5MS00ZTJhLWIxNWUtMTljODg5MjIxNzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYjIzMDU2OTI0YTlhMDAyMWE0YmRmYjI1YjM5OTNkMjNjMTYzMWNiZjAzMGE2OTNkYjNkNWUyMWNkOTc0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wJnDQOrVcuJr-pQWOJKx7ImvEPkt_3J-ZLjbEHpDJt8) 未能复现，建议提供一个最小化可复现的 demo。

`<!DOCTYPE html>
<html>
<head>
    

</head>
<body>
<div id="app">
 <var-row :gutter="[10,10]">
                <var-col :span="8" direction="row">
                    <var-button type="primary">b1</var-button>
                    <var-button type="info">b1</var-button>
                    <var-button type="success">b1</var-button>
                    <var-button type="warning">b1</var-button>
                    <var-button type="danger">b1</var-button>
                    <var-button loading type="primary">b1</var-button>
                    <var-button loading loading-type="wave" type="primary">b1</var-button>
                </var-col>
        <var-divider></var-divider>
        <var-col :span="16" direction="row">
            <var-space :size="[10,10]" direction="row">
                <var-input variant="outlined" placeholder="查询1" v-model="userName"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionType"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionNo"></var-input>
                <var-input variant="outlined" placeholder="查询3" v-model="createTime"></var-input>
                <var-button type="primary" style="margin-top: 18px;">查询</var-button>
                <var-button type="danger" style="margin-top: 18px;">重置</var-button>
            </var-space>
        </var-col>
        <var-divider></var-divider>
    </var-row>
    <var-table :full-width="100">
        <thead>
        <tr>
            <th>姓名</th>
            <th>数学</th>
            <th>英语</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>耗子君</td>
            <td>124</td>
            <td>38</td>
        </tr>
        <tr>
            <td>火猫桑</td>
            <td>100</td>
            <td>135</td>
        </tr>
        </tbody>
    </var-table>

</div>

</body>



<script src="./vue-v3.4.21.js"></script>
<script src="./iife.js"></script>
<script src="./varlet.js"></script>


<script>
    

    
    const app = Vue.createApp({
        setup() {
             let userName = Vue.ref(null);
             let versionNo = Vue.ref(null);
             let versionType = Vue.ref(null);
             let createTime = Vue.ref(null);
             debugger
             return {userName, versionType, versionNo, createTime}
        },
        data() {
            return {}
        },
        methods: {},
        mounted() {
        },
    })

    // Varlet.Locale.add('zh-CN','Locale.zhCN');
    // Varlet.Locale.use('zh-CN');
    app.use(Varlet).mount('#app')
</script>
</html>


融信云银行云事业部.交付二中心 权宝强
电话：029-81120099-5140     
传真：029-81022895
手机：18991846687
邮箱：quanbq[@dcfcs.com](mailto:ITCODE@dcfcs.com)
企业官网：[www.dcfcs.com](http://www.dcfcs.com/)
地址：陕西省西安市丈八四路20号神州数码科技园5号楼24层

 
发件人： [quanbq@dcfcs.com](mailto:quanbq@dcfcs.com)
发送时间： 2024-04-01 10:46
收件人： [权宝强](mailto:quanbq@dcfcs.com)
主题： fs


融信云银行云事业部.交付二中心 权宝强
电话：029-81120099-5140     
传真：029-81022895
手机：18991846687
邮箱：quanbq[@dcfcs.com](mailto:ITCODE@dcfcs.com)
企业官网：[www.dcfcs.com](http://www.dcfcs.com/)
地址：陕西省西安市丈八四路20号神州数码科技园5号楼24层`

**Comment by kinbod** [comment]
> 理论上 jsp 也应该没有太大问题，可以看下最终渲染出的 html 长什么样子。

```<!DOCTYPE html>
<html>
<head>
    

</head>
<body>
<div id="app">
 <var-row :gutter="[10,10]">
                <var-col :span="8" direction="row">
                    <var-button type="primary">b1</var-button>
                    <var-button type="info">b1</var-button>
                    <var-button type="success">b1</var-button>
                    <var-button type="warning">b1</var-button>
                    <var-button type="danger">b1</var-button>
                    <var-button loading type="primary">b1</var-button>
                    <var-button loading loading-type="wave" type="primary">b1</var-button>
                </var-col>
        <var-divider></var-divider>
        <var-col :span="16" direction="row">
            <var-space :size="[10,10]" direction="row">
                <var-input variant="outlined" placeholder="查询1" v-model="userName"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionType"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionNo"></var-input>
                <var-input variant="outlined" placeholder="查询3" v-model="createTime"></var-input>
                <var-button type="primary" style="margin-top: 18px;">查询</var-button>
                <var-button type="danger" style="margin-top: 18px;">重置</var-button>
            </var-space>
        </var-col>
        <var-divider></var-divider>
    </var-row>
    <var-table :full-width="100">
        <thead>
        <tr>
            <th>姓名</th>
            <th>数学</th>
            <th>英语</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>耗子君</td>
            <td>124</td>
            <td>38</td>
        </tr>
        <tr>
            <td>火猫桑</td>
            <td>100</td>
            <td>135</td>
        </tr>
        </tbody>
    </var-table>

</div>

</body>
<!-- 页面底部js¨ -->

<!-- Add the following at the end of your body tag -->
<script src="./vue-v3.4.21.js"></script>
<script src="./iife.js"></script>
<script src="./varlet.js"></script>


<script>
    

    <!-- 数据操作区域 -->
    const app = Vue.createApp({
        setup() {
             let userName = Vue.ref(null);
             let versionNo = Vue.ref(null);
             let versionType = Vue.ref(null);
             let createTime = Vue.ref(null);
             debugger
             return {userName, versionType, versionNo, createTime}
        },
        data() {
            return {}
        },
        methods: {},
        mounted() {
        },
    })

    // Varlet.Locale.add('zh-CN','Locale.zhCN');
    // Varlet.Locale.use('zh-CN');
    app.use(Varlet).mount('#app')
</script>
</html>```

**Comment by kinbod** [comment]
> 理论上 jsp 也应该没有太大问题，可以看下最终渲染出的 html 长什么样子。

cdn直接使用var-table标签根本就不显示表格
