### ISSUE TITLE
floating-panel 自定义锚点的时候没有向上的一个动画效果了

### ISSUE THREAD

**Issue by Bolin-Sun** [varletjs/varlet#1535]
# Bug report 🐞
 floating-panel 自定义锚点的时候没有向上的一个过渡动画效果了，如果不使用自定义锚点就会有过渡动画
## Version & Environment
 "vite": "^4.4.5"
 "@varlet/ui": "^3.0.7",

**Comment by chouchouji** [comment]
能提供一个复现链接嘛？

**Comment by chouchouji** [comment]
能提供一个复现链接嘛？

**Comment by Bolin-Sun** [comment]
> 能提供一个复现链接嘛？

http://124.71.151.3:8457/#/base

**Comment by chouchouji** [comment]
https://github.com/varletjs/varlet/assets/70570907/032ae407-207e-4f07-870f-b523f5ca1ce2

看着是没问题的

**Comment by Bolin-Sun** [comment]
> 20240317201644_rec_.mp4 
> 看着是没问题的

不是这个问题，是floating-panel初始化展示在页面的时候，自定义锚点没有一个向上的过渡动画 ，你可以来回切换 （`默认锚点` 和 `自定义锚点`）看一下

**Comment by chouchouji** [comment]
> http://124.71.151.3:8457/#/base

理解了

**Comment by wangKBweb** [comment]
已修复 会在下个版本更新 现同步为初始化都无动画
