### ISSUE TITLE
组件库支持 uniapp 开发app 吗？

### ISSUE THREAD

**Issue by JamesLi-dev** [varletjs/varlet#1549]
组件库支持 uniapp 开发app 吗？

**Comment by haoziqaq** [comment]
varlet 是 web 组件库，所以 webapp 是可以的，native 小程序不行～

**Comment by elarbor** [comment]
> varlet 是 web 组件库，所以 webapp 是可以的，native 小程序不行～

uniapp开发小程序，可以用吗？
