### ISSUE TITLE
var-checkbox从父组件修改modelValue时同时也触发@update:modelValue

### ISSUE THREAD

**Issue by Bob0911** [varletjs/varlet#1566]
# Bug report 🐞
实现全选逻辑时出现问题
## Version & Environment
v3.2.2
## Expectation
取消单个选项 时全选按钮也取消
## Actual results (or Errors)
取消单个选项时 所有按钮都取消了
## Reproduction link
[varlet-ui-playground](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgY29tcHV0ZWQgfSBmcm9tICd2dWUnXG5jb25zdCBzdGF0ZTEgPSByZWYoQXJyYXkuZnJvbSh7IGxlbmd0aDogMyB9KS5tYXAoKF8sIGkpID0+ICh7XG4gIHNlbGVjdGVkOiBmYWxzZSxcbiAgaWQ6IGksXG59KSkpXG5jb25zdCBzZWxlY3RlZEFsbCA9IGNvbXB1dGVkKCgpID0+IHN0YXRlMS52YWx1ZS5ldmVyeShlID0+IGUuc2VsZWN0ZWQpKTtcbmNvbnN0IG9uVG9nZ2xlQWxsID0gKHY6IGJvb2xlYW4pID0+IHtcbiAgY29uc29sZS5sb2coXCJvblRvZ2dsZUFsbFwiKTtcbiAgc3RhdGUxLnZhbHVlLmZvckVhY2goZSA9PiBlLnNlbGVjdGVkID0gdilcbn1cbmNvbnN0IHN0YXRlMiA9IHJlZihBcnJheS5mcm9tKHsgbGVuZ3RoOiA0IH0pLm1hcCgoXywgaSkgPT4gKHtcbiAgc2VsZWN0ZWQ6IGZhbHNlLFxuICBpZDogaSxcbn0pKSlcbmNvbnN0IHNlbGVjdGVkQWxsMiA9IGNvbXB1dGVkKCgpID0+IHN0YXRlMi52YWx1ZS5ldmVyeShlID0+IGUuc2VsZWN0ZWQpKTtcbmNvbnN0IG9uVG9nZ2xlQWxsMiA9IChldmVudDpJbnB1dEV2ZW50KSA9PiB7XG4gIGNvbnN0IHYgPSAoZXZlbnQudGFyZ2V0IGFzIEhUTUxJbnB1dEVsZW1lbnQpLmNoZWNrZWRcbiAgY29uc29sZS5sb2coXCJvblRvZ2dsZUFsbDJcIik7XG4gIHN0YXRlMi52YWx1ZS5mb3JFYWNoKGUgPT4gZS5zZWxlY3RlZCA9IHYpXG59XG5cblxuPC9zY3JpcHQ+XG48dGVtcGxhdGU+XG4gIDx2YXItY2VsbD5cbiAgICA8dmFyLWNoZWNrYm94IDptb2RlbC12YWx1ZT1cInNlbGVjdGVkQWxsXCIgQHVwZGF0ZTptb2RlbC12YWx1ZT1cIm9uVG9nZ2xlQWxsXCI+5YWo6YCJPC92YXItY2hlY2tib3g+XG4gIDwvdmFyLWNlbGw+XG4gIDx2YXItY2VsbCB2LWZvcj1cIml0ZW0gaW4gc3RhdGUxXCIgOmtleT1cIml0ZW0uaWRcIj5cbiAgICA8dmFyLWNoZWNrYm94IHYtbW9kZWw9XCJpdGVtLnNlbGVjdGVkXCI+6YCJ6aG5e3sgaXRlbS5pZCB9fTwvdmFyLWNoZWNrYm94PlxuICA8L3Zhci1jZWxsPlxuICA8dmFyLWNlbGw+XG4gICAgPGlucHV0IHR5cGU9XCJjaGVja2JveFwiIDpjaGVja2VkPVwic2VsZWN0ZWRBbGwyXCIgQGNoYW5nZT1cIm9uVG9nZ2xlQWxsMlwiIC8+5YWo6YCJXG4gIDwvdmFyLWNlbGw+XG4gIDx2YXItY2VsbCB2LWZvcj1cIml0ZW0gaW4gc3RhdGUyXCIgOmtleT1cIml0ZW0uaWRcIj5cbiAgICA8aW5wdXQgdHlwZT1cImNoZWNrYm94XCIgdi1tb2RlbD1cIml0ZW0uc2VsZWN0ZWRcIiAvPumAiemhuXt7IGl0ZW0uaWQgfX1cbiAgPC92YXItY2VsbD5cbjwvdGVtcGxhdGU+XG4iLCJBcHBXcmFwcGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YXJsZXRDc3MgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3N0eWxlLmNzcydcbmNvbnN0IHZhcmxldFRvdWNoRW11bGF0b3IgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3RvdWNoLWVtdWxhdG9yL2lpZmUuanMnXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGNvbnN0IHNjcmlwdCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3NjcmlwdCcpXG4gIHNjcmlwdC5zcmMgPSB2YXJsZXRUb3VjaEVtdWxhdG9yXG4gIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoc2NyaXB0KVxuXG4gIGNvbnN0IHRoZW1lTWFwID0ge1xuICAgIGxpZ2h0VGhlbWU6IG51bGwsXG4gICAgZGFya1RoZW1lOiBWYXJsZXRVSS5UaGVtZXMuZGFyayxcbiAgICBtZDNMaWdodFRoZW1lOiBWYXJsZXRVSS5UaGVtZXMubWQzTGlnaHQsXG4gICAgbWQzRGFya1RoZW1lOiBWYXJsZXRVSS5UaGVtZXMubWQzRGFyayxcbiAgfVxuXG4gIGNvbnN0IHRoZW1lID0gcGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5nZXRBdHRyaWJ1dGUoJ3RoZW1lJylcblxuICBpZiAodGhlbWUpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKHRoZW1lTWFwW3RoZW1lXSlcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcih0aGVtZU1hcFtkYXRhLnZhbHVlXSlcbiAgICB9XG4gIH0pXG5cbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gICAgd2luZG93LnBhcmVudC5kb2N1bWVudC5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnY2xpY2snKSlcbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9IHZhcmxldENzc1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJAdmFybGV0L3VpXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcIlByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59In0=)

**Comment by chouchouji** [comment]
感谢反馈，会在下个版本修复
