### ISSUE TITLE
<var-tabs>

### ISSUE THREAD

**Issue by logoho** [varletjs/varlet#1570]
# question

![Snipaste_2024-04-05_18-55-27](https://github.com/varletjs/varlet/assets/110022379/d449c32c-2fd9-4423-abf6-d49df24178b5)

请问可以如何解决？谢谢

**Comment by chouchouji** [comment]
是说滚动包装那个地方，其实包装tab那里没有效果，滚动的是月计划周计划那个tab嘛？

**Comment by logoho** [comment]
> 是说滚动包装那个地方，其实包装tab那里没有效果，滚动的是月计划周计划那个tab嘛？

一个页面用了两个tabs选项卡，一个是(父组件)月计划周计划，一个是(子组件)包装N组。子组件的包装N组的tab数量超出可以横向滚动选择，但是横向滑动只能滑动父组件的左右切换月计划周计划的内容页

**Comment by logoho** [comment]
> .stop

请问是可以在<var-tabs v-model:active="active"></var-tabs>标签内加么？

**Comment by logoho** [comment]
目前只能 在(父组件)月计划周计划的TabsItems Props里面设置can-swipe | 是否允许滑动切换 为false

**Comment by haoziqaq** [comment]
```html
<var-tabs @touchmove.stop v-model:active="category">
    <var-tab :name="i.id" v-for="i in categories?.data ?? []" :key="i.id">{{ i.name }}</var-tab>
</var-tabs>
```
