### ISSUE TITLE
table not work

### ISSUE THREAD

**Issue by kinbod** [varletjs/varlet#1576]
# Bug report 🐞

## Version & Environment
```
<!DOCTYPE html>
<html>
<head>
    

</head>
<body>
<div id="app">
 <var-row :gutter="[10,10]">
                <var-col :span="8" direction="row">
                    <var-button type="primary">b1</var-button>
                    <var-button type="info">b1</var-button>
                    <var-button type="success">b1</var-button>
                    <var-button type="warning">b1</var-button>
                    <var-button type="danger">b1</var-button>
                    <var-button loading type="primary">b1</var-button>
                    <var-button loading loading-type="wave" type="primary">b1</var-button>
                </var-col>
        <var-divider></var-divider>
        <var-col :span="16" direction="row">
            <var-space :size="[10,10]" direction="row">
                <var-input variant="outlined" placeholder="查询1" v-model="userName"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionType"></var-input>
                <var-input variant="outlined" placeholder="查询2" v-model="versionNo"></var-input>
                <var-input variant="outlined" placeholder="查询3" v-model="createTime"></var-input>
                <var-button type="primary" style="margin-top: 18px;">查询</var-button>
                <var-button type="danger" style="margin-top: 18px;">重置</var-button>
            </var-space>
        </var-col>
        <var-divider></var-divider>
    </var-row>
    <var-table :full-width="100">
        <thead>
        <tr>
            <th>姓名</th>
            <th>数学</th>
            <th>英语</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>耗子君</td>
            <td>124</td>
            <td>38</td>
        </tr>
        <tr>
            <td>火猫桑</td>
            <td>100</td>
            <td>135</td>
        </tr>
        </tbody>
    </var-table>

</div>

</body>
<!-- 页面底部js¨ -->

<!-- Add the following at the end of your body tag -->
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://cdn.jsdelivr.net/npm/@varlet/ui/umd/varlet.js"></script>

<script>
    

    <!-- 数据操作区域 -->
    const app = Vue.createApp({
        setup() {
             let userName = Vue.ref(null);
             let versionNo = Vue.ref(null);
             let versionType = Vue.ref(null);
             let createTime = Vue.ref(null);
             debugger
             return {userName, versionType, versionNo, createTime}
        },
        data() {
            return {}
        },
        methods: {},
        mounted() {
        },
    })

    // Varlet.Locale.add('zh-CN','Locale.zhCN');
    // Varlet.Locale.use('zh-CN');
    app.use(Varlet).mount('#app')
</script>
</html>
```
## Expectation
![1712470528599](https://github.com/varletjs/varlet/assets/8268021/c8f2acb9-b3b5-4242-9a46-994a99c9fb9a)

## Actual results (or Errors)
![1712470528599](https://github.com/varletjs/varlet/assets/8268021/e2d4f047-ed66-4c60-b838-7ea6acc4231e)

**Comment by haoziqaq** [comment]
![image](https://github.com/varletjs/varlet/assets/24223652/3636e670-7f87-4edc-90eb-8d53453aeb8f)

这是由于 vue 的限制，写在 dom 中的模板必须是标准的 html 语法，所以只能放在 template 选项里。

**Comment by kinbod** [comment]
> ![image](https://private-user-images.githubusercontent.com/24223652/320258413-3636e670-7f87-4edc-90eb-8d53453aeb8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzM1NTIsIm5iZiI6MTcxMjQ3MzI1MiwicGF0aCI6Ii8yNDIyMzY1Mi8zMjAyNTg0MTMtMzYzNmU2NzAtN2Y4Ny00ZWRjLTkwZWItOGQ1MzQ1M2FlYjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3MDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzkzNDc1NzQwMjY0ZTg2YjhlMmZkNjE1MmQ0MDNiMDliOTE2ODVmZGFkYTZjYTQyZjZjZTBkMjFlZjFiZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NBqQJKA0y2mZjebRcqXSjQlMhcNrp-0vGsS7mlU0IYk)
> 
> 这是由于 vue 的限制，写在 dom 中的模板必须是标准的 html 语法，所以只能放在 template 选项里。

那var-button和其他标签为什么可以识别呢？

**Comment by kinbod** [comment]
那里面的var-button为什么可以正常识别

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: haoziqaq ***@***.***>
发送时间: Sunday, April 7, 2024 2:54:07 PM
收件人: varletjs/varlet ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [varletjs/varlet] table not work (Issue #1576)


image.png (view on web)<https://github.com/varletjs/varlet/assets/24223652/3636e670-7f87-4edc-90eb-8d53453aeb8f>

这是由于 vue 的限制，写在 dom 中的模板必须是标准的 html 语法，所以只能放在 template 选项里。

―

**Comment by haoziqaq** [comment]
因为在 html 中，tbody 和 thead 必须在 table 元素中，所以这样的模板不属于标准的 html 模板。包括自闭合标签，一样也是无效的。var-button 因为符合标准 html 标签的规则，它会被认为是自定义元素存在。

**Comment by haoziqaq** [comment]
建议就是所有的 vue 模板都写在 template 选项里，这样可以保证 vue 的所有模板编译器特性都能被使用。字符串高亮可以参考官方的推荐，使用 es6-string-html 插件。
![image](https://github.com/varletjs/varlet/assets/24223652/3042f174-1322-4d87-9882-9ec6c005044e)

**Comment by kinbod** [comment]
好的，感谢，这下明白了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: haoziqaq ***@***.***>
发送时间: Sunday, April 7, 2024 3:06:08 PM
收件人: varletjs/varlet ***@***.***>
抄送: Bodkin Quan ***@***.***>; Author ***@***.***>
主题: Re: [varletjs/varlet] table not work (Issue #1576)


因为在 html 中，tbody 和 thead 必须在 table 元素中，所以这样的模板不属于标准的 html 模板。包括自闭合标签，一样也是无效的。var-button 因为符合标准 html 标签的规则，它会被认为是自定义元素存在。

―

**Comment by haoziqaq** [comment]
不客气
