### ISSUE TITLE
为什么在v-show状态下，input框的placeholder消失了？

### ISSUE THREAD

**Issue by maxiaop** [varletjs/varlet#1596]
#首次进来页面时placeholder不显示，点击input框时才显示
![image](https://github.com/varletjs/varlet/assets/125235283/1f91290d-9e08-45cf-aba2-39c1ceaa19ff)
![image](https://github.com/varletjs/varlet/assets/125235283/4f069daf-59fe-4a50-93ac-622febeebdd6)
![image](https://github.com/varletjs/varlet/assets/125235283/57cb0bed-fc9c-4e05-9dba-69fe0c71fbbb)

**Comment by nonzzz** [comment]
请提供最小复现

**Comment by maxiaop** [comment]
![动画](https://github.com/varletjs/varlet/assets/125235283/c0e40087-210b-4fb9-93c6-34a015145d26)

**Comment by haoziqaq** [comment]
v-if 有这个问题么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月17日(周三) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [varletjs/varlet] 为什么在v-show状态下，input框的placeholder消失了？ (Issue #1596)




 
default.gif (view on web)

**Comment by maxiaop** [comment]
v-if没有

**Comment by haoziqaq** [comment]
placeholder 涉及位置计算，有可能受 v-show display none 的影响。建议你使用 v-if。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月17日(周三) 下午3:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] 为什么在v-show状态下，input框的placeholder消失了？ (Issue #1596)




 
v-if没有

**Comment by maxiaop** [comment]
> placeholder 涉及位置计算，有可能受 v-show display none 的影响。建议你使用 v-if。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月17日(周三) 下午3:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [varletjs/varlet] 为什么在v-show状态下，input框的placeholder消失了？ (Issue #1596) v-if没有 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

嗯嗯
