### ISSUE TITLE
官方文档非常卡顿

### ISSUE THREAD

**Issue by zmqcherish** [varletjs/varlet#1598]
[# About `docs`](https://varlet.gitee.io/varlet-ui/#/zh-CN/home) 页面非常卡顿，总是未响应

![image](https://github.com/varletjs/varlet/assets/6880848/cd719049-d162-4be9-863f-27a6ed7b83a0)

**Comment by chouchouji** [comment]
[20240419104013_rec_.mp4.zip](https://github.com/varletjs/varlet/files/15032412/20240419104013_rec_.mp4.zip)

没发现有这个问题，可能是你浏览器的问题

**Comment by zmqcherish** [comment]
好吧，目前我的情况：
使用chrome，只有 [https://varlet.gitee.io/varlet-ui/#/zh-CN/home](https://varlet.gitee.io/varlet-ui/) 的tab非常卡顿，其它tab正常；
使用edge正常
十分诡异

**Comment by zmqcherish** [comment]
原来是因为某东方神秘力量
