### ISSUE TITLE
希望有一个AutoComplete 组件

### ISSUE THREAD

**Issue by zmqcherish** [varletjs/varlet#1599]
参考 [https://www.antdv.com/components/auto-complete-cn](https://www.antdv.com/components/auto-complete-cn)

**Comment by chouchouji** [comment]
感谢反馈，最近我们会讨论下这个新组件。

**Comment by chouchouji** [comment]
目标前讨论的结果是，先支持menu和select等组件的options模式，再去实现这个组件。
