### ISSUE TITLE
是否有docs右侧演示部分的源代码

### ISSUE THREAD

**Issue by zmqcherish** [varletjs/varlet#1601]
想在PC上直接跑起这个效果
![image](https://github.com/varletjs/varlet/assets/6880848/0fcf5efe-9c8a-409b-97cf-6fc73ffb78c6)

**Comment by haoziqaq** [comment]
https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/button/example/index.vue

每个组件文件夹中 example 就是

**Comment by chouchouji** [comment]
![image](https://github.com/varletjs/varlet/assets/70570907/2b3e5cf4-cad2-48e0-86d8-010070881bcc)
