### ISSUE TITLE
pnpm run dev 报错哎，什么原因呢

### ISSUE THREAD

**Issue by zhangtaouc** [varletjs/varlet#1607]
我把项目克隆下来了，好像运行不了，大佬指导一下
![image](https://github.com/varletjs/varlet/assets/39691213/cbd34a37-c5f5-47db-aabc-204010104ee6)

**Comment by haoziqaq** [comment]
先执行 pnpm bootstrap。参考 https://github.com/varletjs/varlet/blob/dev/.github/CONTRIBUTING.md
