### ISSUE TITLE
是否能给appBar添加固定在顶部的api

### ISSUE THREAD

**Issue by Jxells** [varletjs/varlet#1610]
# About `styles` 🛠️
BottomNavigation 有一个是否固定在底部的属性，个人觉得appBar也可以搞一个固定在顶部的属性。

**Comment by haoziqaq** [comment]
节后可以增加一下～

**Comment by haoziqaq** [comment]
目前 app bar 是有 fixed 这个 api 可以固定到顶部的。

**Comment by Jxells** [comment]
> 目前app bar是有固定的这个api可以固定到顶部的。

在文档中没看到呀

**Comment by haoziqaq** [comment]
<img width="753" alt="image" src="https://github.com/varletjs/varlet/assets/24223652/3dca1f44-1a6c-42c6-8c03-d6bd6a5adbdc">

**Comment by Jxells** [comment]
加上fixed 属性后下拉刷新的图标会顶到app bar上面
![image](https://github.com/varletjs/varlet/assets/94813798/8506b82c-bff8-4ad6-a073-22bbf69ddc18)

**Comment by haoziqaq** [comment]
和 bottom navigation 一样，需要自行空出 app-bar 的位置。比如设置给主要容器设置 padding-top
