### ISSUE TITLE
为什么相邻的input 的底部边框粗细不一样

### ISSUE THREAD

**Issue by MaiShe** [varletjs/varlet#1611]
# About `styles` 🛠️
![image](https://github.com/varletjs/varlet/assets/5570264/664c1ef0-5d75-44ab-964d-d48fe4dff347)
![image](https://github.com/varletjs/varlet/assets/5570264/dd795ced-d2e8-41a0-9d9f-b1633bc7afb5)

**Comment by haoziqaq** [comment]
没能复现这个问题。

**Comment by chouchouji** [comment]
这个issue先关闭了，如果有进一步的疑问或反馈，可以在这里或者社区群留言。
