### ISSUE TITLE
希望骨架屏组件的正文能跟其他属性一样变得可控

### ISSUE THREAD

**Issue by JayChen953641513** [varletjs/varlet#1623]
### 目前使用骨架屏组件的时候 希望单独显示上方的这个卡片card 但是绿色框框的这个正文却是默认显示的 没有属性可以控制其显示隐藏 能且只能使用样式穿透去将他去掉 十分不灵活

![Uploading _20240512135630.png…](http://175.178.148.145/images/_20240512135630.png)

**Comment by haoziqaq** [comment]
```html
<var-skeleton card :rows="3" :loading="loading"></var-skeleton>
```

可以尝试这样
