### ISSUE TITLE
var-input 左边没有直接的api去显示一个输入框标题啊 例如 手机号 姓名 年龄。。。

### ISSUE THREAD

**Issue by scallopsF** [varletjs/varlet#1629]
# About `styles` 🛠️

**Comment by haoziqaq** [comment]
可以用 prepend-icon 插槽

**Comment by chouchouji** [comment]
![image](https://github.com/varletjs/varlet/assets/70570907/ec1457dd-7c8d-4871-8a26-45e5cde46c43)

**Comment by chouchouji** [comment]
这个issue我先关闭了，如果还有问题可以在此或者社区群留言。
