### ISSUE TITLE
var-card 插槽样式 ？

### ISSUE THREAD

**Issue by CNChestnut** [varletjs/varlet#1661]
# Bug report 🐞

**可能是我的使用问题？**如果是那就抱歉了，但是我已经尽力去理解文档了

`var-card` 在使用插槽添加内容时部分插槽没有正常的样式。

我在 Playground 和自己的开发环境都碰到了这个问题。

![屏幕截图 2024-06-08 001301](https://github.com/varletjs/varlet/assets/98728485/10384e92-773a-4deb-be17-18bf98e77950)

[Code in Playground](https://varlet.pages.dev/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItY2FyZD5cbiAgICA8dGVtcGxhdGUgI2ltZz5cbiAgICAgIDxpbWcgc3JjPVwiaHR0cHM6Ly92YXJsZXQucGFnZXMuZGV2L2NhdC5qcGdcIj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDx0ZW1wbGF0ZSAjdGl0bGU+XG4gICAgICBUaXRsZVxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNzdWJ0aXRsZT5cbiAgICAgIFN1YnRpdGxlXG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8dGVtcGxhdGUgI2Rlc2NyaXB0aW9uPlxuICAgICAgQ29udGVudFxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNleHRyYT5cbiAgICAgIEV4dHJhXG4gICAgPC90ZW1wbGF0ZT5cbiAgPC92YXItY2FyZD5cbjwvdGVtcGxhdGU+XG4iLCJBcHBXcmFwcGVyLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YXJsZXRDc3MgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3N0eWxlLmNzcydcbmNvbnN0IHZhcmxldFRvdWNoRW11bGF0b3IgPSAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3RvdWNoLWVtdWxhdG9yL2lpZmUuanMnXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGNvbnN0IHNjcmlwdCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3NjcmlwdCcpXG4gIHNjcmlwdC5zcmMgPSB2YXJsZXRUb3VjaEVtdWxhdG9yXG4gIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoc2NyaXB0KVxuXG4gIGNvbnN0IHRoZW1lTWFwID0ge1xuICAgIGxpZ2h0VGhlbWU6IG51bGwsXG4gICAgZGFya1RoZW1lOiBWYXJsZXRVSS5UaGVtZXMuZGFyayxcbiAgICBtZDNMaWdodFRoZW1lOiBWYXJsZXRVSS5UaGVtZXMubWQzTGlnaHQsXG4gICAgbWQzRGFya1RoZW1lOiBWYXJsZXRVSS5UaGVtZXMubWQzRGFyayxcbiAgfVxuXG4gIGNvbnN0IHRoZW1lID0gcGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5nZXRBdHRyaWJ1dGUoJ3RoZW1lJylcblxuICBpZiAodGhlbWUpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKHRoZW1lTWFwW3RoZW1lXSlcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcih0aGVtZU1hcFtkYXRhLnZhbHVlXSlcbiAgICB9XG4gIH0pXG5cbiAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7XG4gICAgd2luZG93LnBhcmVudC5kb2N1bWVudC5kaXNwYXRjaEV2ZW50KG5ldyBFdmVudCgnY2xpY2snKSlcbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9IHZhcmxldENzc1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJAdmFybGV0L3VpXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdmFybGV0L3VpL2VzL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcIlByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59In0=)

## Version & Environment

- Varlet Playground
- Neweast Chrome

## 题外话

> 关于[之前在某个 issue 下的讨论](https://github.com/varletjs/varlet/issues/1050#issuecomment-2094906319)的后续？

**Comment by haoziqaq** [comment]
当用户使用插槽的时候，我们会认为用户希望完全定制某一个区域的内容，所以不会另外设置样式。另外 `#img` 应该是拼写有误，正确的应该是 `#image`。

源码设计参考如下，如果希望携带样式也可以直接复用组件使用的 `var-card__title` class。
![image](https://github.com/varletjs/varlet/assets/24223652/b66e0ae6-eb7c-49cf-8b3e-5ce1fd638001)

关于图标库扩展：
我们提供了一个插件尽可能简单的对图标库扩展，详情见[这里](https://varlet.pages.dev/#/zh-CN/icon#zi4ding4yi4tu2biao1ku4(cha1jian4ding4yi4))。

感谢您利用宝贵的时间给予我们反馈。

**Comment by haoziqaq** [comment]
对于您或者部分用户可能需要的定制插槽并携带样式的需要。我们后续可能会加入插槽作用域参数来解决。例如

```html
<var-card>
  <template #titile="{ class }">
     <div :class="class"></div>
  </template>
</var-card>
```

或许可以提升一些体验

**Comment by chouchouji** [comment]
> 对于您或者部分用户可能需要的定制插槽并携带样式的需要。我们后续可能会加入作用域插槽参数来解决。例如
> 
> ```
> <var-card>
>   <template #title="{ class }">
>      <div :class="class"></div>
>   </template>
> </var-card>
> ```
> 
> 或许可以提升一些体验。

已提pr
