### ISSUE TITLE
Nuxt3中DatePicker组件国际化无效

### ISSUE THREAD

**Issue by cbh24kcs** [varletjs/varlet#1674]
# Bug report 🐞
DatePicker组件使用国际化时无效
## Version & Environment
nuxt3.11.2 @varlet/ui3.2.9  @varlet/nuxt0.1.2
## Expectation
国际化为英文
## Actual results (or Errors)
放在layouts文件中，国际化无效，无keep alive（其他组件生效）  
![C6468445D0B745F49B9CC37B203B56CC.png](https://s2.loli.net/2024/06/12/afb3CKldJs7XZcj.png)  
![263C10FDF8CC95012D2393C91E1EC59C.png](https://s2.loli.net/2024/06/12/yCQLGYmtU941KIV.png) <br/>仅服务端渲染组件中一样无效<br/>![04FF6AE7A528BC2C835A1876628D70F9.png](https://s2.loli.net/2024/06/12/InlGVA3OhNYfDuZ.png)<br/>![0876BD390F5FB7707B3DB6FD38B644B3.png](https://s2.loli.net/2024/06/12/lbsRQ1DHBhjNW9I.png)

**Comment by zhangmo8** [comment]
Link https://github.com/varletjs/varlet/commit/961746880067608d48d03b0faa72e7a9cc9f3385
