### ISSUE TITLE
Use `v-model.trim="value"` in `input`, can't enter space.

### ISSUE THREAD

**Issue by coderwyd** [varletjs/varlet#1692]
# Bug report 🐞
When I use the `v-model.trim` modifier on the `input` box, I cannot enter a space after the last character.

## Version & Environment
latest

## Expectation
Spaces can be input normally, and spaces are removed only when the focus is lost.

## Actual results (or Errors)
...

## Reproduction link
https://varlet.pages.dev/playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbmNvbnN0IHZhbHVlID0gcmVmKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+e3sgbXNnIH19PC92YXItYnV0dG9uPlxuICA8dmFyLWlucHV0IHYtbW9kZWwudHJpbT1cInZhbHVlXCIvPlxuPC90ZW1wbGF0ZT5cbiIsIkFwcFdyYXBwZXIudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJIGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhcmxldENzcyA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvc3R5bGUuY3NzJ1xuY29uc3QgdmFybGV0VG91Y2hFbXVsYXRvciA9ICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdG91Y2gtZW11bGF0b3IvaWlmZS5qcydcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgY29uc3Qgc2NyaXB0ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0JylcbiAgc2NyaXB0LnNyYyA9IHZhcmxldFRvdWNoRW11bGF0b3JcbiAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChzY3JpcHQpXG5cbiAgY29uc3QgdGhlbWVNYXAgPSB7XG4gICAgbGlnaHRUaGVtZTogbnVsbCxcbiAgICBkYXJrVGhlbWU6IFZhcmxldFVJLlRoZW1lcy5kYXJrLFxuICAgIG1kM0xpZ2h0VGhlbWU6IFZhcmxldFVJLlRoZW1lcy5tZDNMaWdodCxcbiAgICBtZDNEYXJrVGhlbWU6IFZhcmxldFVJLlRoZW1lcy5tZDNEYXJrLFxuICB9XG5cbiAgY29uc3QgdGhlbWUgPSBwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmdldEF0dHJpYnV0ZSgndGhlbWUnKVxuXG4gIGlmICh0aGVtZSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIodGhlbWVNYXBbdGhlbWVdKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKHRoZW1lTWFwW2RhdGEudmFsdWVdKVxuICAgIH1cbiAgfSlcblxuICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0+IHtcbiAgICB3aW5kb3cucGFyZW50LmRvY3VtZW50LmRpc3BhdGNoRXZlbnQobmV3IEV2ZW50KCdjbGljaycpKVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gdmFybGV0Q3NzXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcIkB2YXJsZXQvdWlcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2YXJsZXQvdWkvZXMvdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwiUHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn0ifQ==

**Comment by haoziqaq** [comment]
3.3.5-alpha.1720530125141
