### ISSUE TITLE
设置了input  为readonly 导致无法正确校验

### ISSUE THREAD

**Issue by chouchouji** [varletjs/varlet#1701]
# Bug report 🐞

## Version & Environment

**Varlet UI 3.3.3**

## Reproduction link

[link](https://varletjs.org/playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dmFyLXNwYWNlIDpzaXplPVwiWzQwLDBdXCIgICBkaXJlY3Rpb249XCJjb2x1bW5cIiAgc3R5bGU9XCJtYXJnaW4tdG9wOiA0MHB4O1wiPlxuICAgIDx2YXItZm9ybSByZWY9XCJmb3JtUmVmXCIgc2Nyb2xsLXRvLWVycm9yPVwic3RhcnRcIj5cbiAgICA8dmFyLWlucHV0XG4gICAgICBzaXplPVwic21hbGxcIlxuICAgICAgdmFyaWFudD1cIm91dGxpbmVkXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwi5rWL6K+V6aqM6K+BXCJcbiAgICAgIHJlYWRvbmx5XG4gICAgICBAY2xpY2s9XCJvbkRlcHRJbnB1dFwiXG4gICAgICByZWY9XCJkZXB0SW5wdXRSZWZcIlxuICAgICAgdi1tb2RlbD1cImZvcm1EYXRhLmRlcHROYW1lXCJcbiAgICAgIDpydWxlcz1cImRlcHRSdWxlXCJcbiAgICAvPlxuICA8L3Zhci1mb3JtPlxuXG4gIDx2YXItYnV0dG9uXG4gICAgOmRpc2FibGVkPVwiaXNEZXRhaWxcIlxuICAgIGJsb2NrXG4gICAgdHlwZT1cInByaW1hcnlcIlxuICAgIHNpemU9XCJsYXJnZVwiXG4gICAgQGNsaWNrPVwic3VibWl0XCJcbiAgPlxuICAgIOaPkOS6pFxuICA8L3Zhci1idXR0b24+XG4gIDwvdmFyLXNwYWNlPlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQge1BpY2tlciB9IGZyb20gJ0B2YXJsZXQvdWknO1xuIFxuY29uc3QgaXNEZXRhaWwgPSByZWYoZmFsc2UpOyBcbmNvbnN0IGZvcm1EYXRhID0gcmVhY3RpdmUoe1xuICBwcm9qZWN0OiBcIlwiLFxuICBkZXB0SWQ6IFwiXCIsXG4gIGRlcHROYW1lOiBcIlwiLFxuICBhdHRhY2htZW50TGlzdDogW10sXG4gIHRvdGFsQW1vdW50OiBcIlwiLFxuICBkZXRhaWw6IFtcbiAgICB7XG4gICAgICBhbW91bnQ6IFwiXCIsXG4gICAgICByZW1hcms6IFwiXCIsXG4gICAgICB0eXBlOiBcIlwiLFxuICAgICAgdHlwZU5hbWU6IFwiXCIsXG4gICAgICB1c2VEYXk6IG51bGwsXG4gICAgfSxcbiAgXSxcbn0pO1xuIFxuIFxuIFxuY29uc3QgZm9ybVJlZiA9IHJlZihudWxsKTtcbiBcbmNvbnN0IGRlcHRJbnB1dFJlZiA9IHJlZihudWxsKTtcbmNvbnN0IGRlcHRSdWxlID0gW1xuICAodikgPT4ge1xuICAgIGNvbnNvbGUubG9nKHYsICd2Jyk7XG4gICAgaWYgKGZvcm1EYXRhLmRlcHROYW1lKSB7XG4gICAgICByZXR1cm4gdHJ1ZTtcbiAgICB9XG4gICAgcmV0dXJuIFwi5oql6ZSA6YOo6Zeo5LiN6IO95Li656m6XCI7XG4gIH0sXG5dO1xuXG5jb25zdCBzdWJtaXQgPSBhc3luYyAoKSA9PiB7XG4gIGRlcHRJbnB1dFJlZi52YWx1ZS52YWxpZGF0ZSgpLnRoZW4oKHJlcykgPT4ge1xuICAgIGNvbnNvbGUubG9nKHJlcywgJ3JlcycpO1xuIFxuICB9KTsgXG4gIHRyeSB7XG4gICAgY29uc3QgdmFsaWQgPSBhd2FpdCBmb3JtUmVmLnZhbHVlLnZhbGlkYXRlKCk7XG4gICAgY29uc29sZS5sb2codmFsaWQsICd2YWxpZCcpO1xuXG4gICAgaWYgKHZhbGlkKSB7XG4gICAgIFxuICAgIH1cbiAgfSBjYXRjaCAoZXJyKSB7XG4gICAgY29uc29sZS5lcnJvcihlcnIpO1xuICB9IGZpbmFsbHkgeyBcbiAgfVxufTtcblxuY29uc3Qgb25EZXB0SW5wdXQgPSBhc3luYyAoKSA9PiB7IFxuICBhd2FpdCBQaWNrZXIoeyBcbiAgICBjb2x1bW5zOiBbXG4gICAgICBbXG4gICAgICAgIHsgdGV4dDogJ0EnIH0sIFxuICAgICAgICB7IHRleHQ6ICdCJyB9LCBcbiAgICAgICAgeyB0ZXh0OiAnQycgfSwgXG4gICAgICAgIHsgdGV4dDogJ0QnIH0sIFxuICAgICAgICB7IHRleHQ6ICdFJyB9XG4gICAgICBdLFxuICAgICAgIFtcbiAgICAgICAgeyB0ZXh0OiAnQScgfSwgXG4gICAgICAgIHsgdGV4dDogJ0InIH0sIFxuICAgICAgICB7IHRleHQ6ICdDJyB9LCBcbiAgICAgICAgeyB0ZXh0OiAnRCcgfSwgXG4gICAgICAgIHsgdGV4dDogJ0UnIH1cbiAgICAgIF0sXG4gICAgICAgW1xuICAgICAgICB7IHRleHQ6ICdBJyB9LCBcbiAgICAgICAgeyB0ZXh0OiAnQicgfSwgXG4gICAgICAgIHsgdGV4dDogJ0MnIH0sIFxuICAgICAgICB7IHRleHQ6ICdEJyB9LCBcbiAgICAgICAgeyB0ZXh0OiAnRScgfVxuICAgICAgXVxuICAgIF0sXG4gICAgb25Db25maXJtOiAodmFsdWVzLCBpbmRleGVzLCBvcHRpb25zKSA9PiB7XG4gICAgICBjb25zb2xlLmxvZyh2YWx1ZXMsIGluZGV4ZXMsIG9wdGlvbnMpO1xuICAgICAgLy8gZm9ybURhdGEuZGVwdE5hbWUgPSBvcHRpb25zW29wdGlvbnMubGVuZ3RoIC0gMV0udGV4dDtcbiAgICAgIGZvcm1EYXRhLmRlcHROYW1lID0gdmFsdWVzWzBdXG5cbiAgICAgIGNvbnNvbGUubG9nKGZvcm1EYXRhLCAnZGF5YWEnKTtcbiAgICB9LFxuICB9KTtcbn07XG48L3NjcmlwdD5cblxuIiwiQXBwV3JhcHBlci52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUkgZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFybGV0Q3NzID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aUAzLjMuMy9lcy9zdHlsZS5jc3MnXG5jb25zdCB2YXJsZXRUb3VjaEVtdWxhdG9yID0gJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC90b3VjaC1lbXVsYXRvckAzLjMuMy9paWZlLmpzJ1xuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBjb25zdCBzY3JpcHQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKVxuICBzY3JpcHQuc3JjID0gdmFybGV0VG91Y2hFbXVsYXRvclxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHNjcmlwdClcblxuICBjb25zdCB0aGVtZU1hcCA9IHtcbiAgICBsaWdodFRoZW1lOiBudWxsLFxuICAgIGRhcmtUaGVtZTogVmFybGV0VUkuVGhlbWVzLmRhcmssXG4gICAgbWQzTGlnaHRUaGVtZTogVmFybGV0VUkuVGhlbWVzLm1kM0xpZ2h0LFxuICAgIG1kM0RhcmtUaGVtZTogVmFybGV0VUkuVGhlbWVzLm1kM0RhcmssXG4gIH1cblxuICBjb25zdCB0aGVtZSA9IHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuZ2V0QXR0cmlidXRlKCd0aGVtZScpXG5cbiAgaWYgKHRoZW1lKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcih0aGVtZU1hcFt0aGVtZV0pXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIodGhlbWVNYXBbZGF0YS52YWx1ZV0pXG4gICAgfVxuICB9KVxuXG4gIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4ge1xuICAgIHdpbmRvdy5wYXJlbnQuZG9jdW1lbnQuZGlzcGF0Y2hFdmVudChuZXcgRXZlbnQoJ2NsaWNrJykpXG4gIH0pXG5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoVmFybGV0VUkpXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBhcHBlbmRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSB2YXJsZXRDc3NcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiQHZhcmxldC91aVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZhcmxldC91aUAzLjMuMy9lcy92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiLi92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJQcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufSJ9)

**Comment by flyhyy** [comment]
先执行提交操作，会触发表单验证，然后在选择值，在点击提交，还是会显示错误表单验证信息

**Comment by haoziqaq** [comment]
解决方法：先 resetValidation 然后 validate(), 下个版本我们会优化这一行为，不需要用户手动清除错误信息。

**Comment by chouchouji** [comment]
这两天我会修复

**Comment by haoziqaq** [comment]
3.3.6-alpha.1720620017198
