### ISSUE TITLE
3.3.8 版本Popup.mjs:33:21提示ReferenceError: defineComponent is not defined

### ISSUE THREAD

**Issue by MarkGor** [varletjs/varlet#1718]
# Bug report 🐞

## Version & Environment
3.3.8

  "dependencies": {
    "@varlet/touch-emulator": "^3.3.8",
    "@varlet/ui": "^3.3.8",
    "axios": "^1.7.2",
    "dayjs": "^1.11.12",
    "less": "^4.2.0",
    "less-loader": "^12.2.0",
    "normalize.css": "^8.0.1",
    "pinia": "^2.1.6",
    "pinia-plugin-persistedstate": "^3.2.1",
    "postcss-px-to-viewport-8-plugin": "^1.2.5",
    "qs": "^6.12.3",
    "vue": "^3.4.33",
    "vue-router": "^4.4.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "fast-glob": "^3.3.2",
    "vite": "^5.3.1",
    "vite-plugin-svg-icons": "^2.0.1"
  }
## Actual results (or Errors)
Popup.mjs:33  Uncaught ReferenceError: defineComponent is not defined

**Comment by MarkGor** [comment]
pnpm run dev
打開瀏覽器后，控制台就輸出這個錯誤了

**Comment by MarkGor** [comment]
好像是其他組件也是這樣，defineComponent沒引入，目前恢復3.3.7使用正常

**Comment by haoziqaq** [comment]
似乎是 jsx 编译出现了问题，编译后的内容直接覆盖了源代码从 vue 中导入的 api。如 defineComponent, ref, computed 等等，目前还不确定是什么原因导致的，很长时间没有对这部分的代码做变更了，并且切换至 3.3.7 依然有这个问题。正在排查相关依赖最近有没有什么隐含的改动。

**Comment by haoziqaq** [comment]
3.3.9 已修复，3.3.8 版本将被废弃。

**Comment by MarkGor** [comment]
> 似乎是 jsx 编译出现了问题，编译后的内容直接覆盖了源代码从 vue 中导入的 api。如 defineComponent, ref, computed 等等，目前还不确定是什么原因导致的，很长时间没有对这部分的代码做变更了，并且切换至 3.3.7 依然有这个问题。正在排查相关依赖最近有没有什么隐含的改动。

贊！真迅速.....
