### ISSUE TITLE
xxx 不是 v-model:show 的有效值。预期值: v-model:show

### ISSUE THREAD

**Issue by peiyanlu** [varletjs/varlet#1723]
# Bug report 🐞
WebStorm 中 v-model:show 会被编译器提示，虽然不影响运行，但是想知道为什么

![image](https://github.com/user-attachments/assets/6b05c46d-cda9-42d8-9dff-6eda6cb37771)

## Version & Environment

  System:
    OS: Windows 11 10.0.26100
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13980HX
    Memory: 35.12 GB / 63.63 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.26100.1

![image](https://github.com/user-attachments/assets/a1fb7303-547d-4716-a207-641272b1ae36)

## Expectation
提示消失

**Comment by haoziqaq** [comment]
varlet 什么版本

**Comment by peiyanlu** [comment]
> varlet 什么版本

3.3.10

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/b2f05268-1180-400e-8539-219cef96bc20)

同样的版本，并没有复现这个警告

**Comment by peiyanlu** [comment]
> ![image](https://private-user-images.githubusercontent.com/70570907/365198307-b2f05268-1180-400e-8539-219cef96bc20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTgyNjQsIm5iZiI6MTcyNTk1Nzk2NCwicGF0aCI6Ii83MDU3MDkwNy8zNjUxOTgzMDctYjJmMDUyNjgtMTE4MC00MDBlLTg1MzktMjE5Y2VmOTZiYzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA4NDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDFhY2NmOWI0ZTI5OWJhMWJjOTUyMGNiMTFhNzgwODg1OTgxZDk3ZDcyOWY1NWUyNTVjODBkMTFhZDQ1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1HFnoRq9o4h-zSrZkbo8tJh0RildjKCzgv7HNAm7eJk)
> 
> 同样的版本，并没有复现这个警告

现在没有了
