### ISSUE TITLE
[menu]: 是否只被`show`控制显示

### ISSUE THREAD

**Issue by RSS1102** [varletjs/varlet#1724]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:
菜单触发方式，可选值为 click hover, auto click 为点击时触发, hover 为悬停时触发 auto用户使用show进行控制

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/b94ea4e9-fd8c-4b55-90f8-8d4240eb8660)

直接使用双向绑定好像也能实现

**Comment by RSS1102** [comment]
即使使用`show`的双向绑定，无论`trigger`在 `click` 或 `hover` 的时候，`show`的状态都会被改变。
我想的是完全有第三方进行控制。

**Comment by haoziqaq** [comment]
ref #1725
