### ISSUE TITLE
I used pnpm run dev to run, and the web page was blank, and then an error was reported.

### ISSUE THREAD

**Issue by immortalts** [varletjs/varlet#1727]
# Bug report 🐞

## Version & Environment
"@varlet/cli": "^3.3.11"
node：V18.20.2
![image](https://github.com/user-attachments/assets/18aaae0b-e98f-4034-b127-4ac12e800b5b)

**Comment by immortalts** [comment]
varlet/CLI

**Comment by haoziqaq** [comment]
Fixed in 3.3.12
