### ISSUE TITLE
LoadingBar用在vue3中路由守卫失效

### ISSUE THREAD

**Issue by magnificent007** [varletjs/varlet#1728]
# Bug report 🐞
LoadingBar用在vue3中路由守卫， beforeEach内start()；afterEach内finish()；只有在第一次切换tabbar栏时有加载态，后面则完全没有动效加载

## Version & Environment
"vue-router": "^4.3.3"
"@varlet/ui": "^3.3.11"

## Expectation
切换tabbar栏时，可以在appBar底下有加载动效而不是一次性的

## Actual results (or Errors)
![](https://i0.hdslb.com/bfs/article/3cfa8579013f41e5387b94f997593e8c322437210.png)
![](https://i0.hdslb.com/bfs/article/bab582e0c0787e9c9c517d8bf00fa37c322437210.png)
![](https://i0.hdslb.com/bfs/article/6d570a4b061e858c0d133415738c3319322437210.png)

**Comment by haoziqaq** [comment]
方便提供一个最小化的复现 demo 吗？

**Comment by magnificent007** [comment]
> 另外说明一下，`LoadingBar` 有 `200ms` 的启动时间，如果在这个时间内已经 `finish` 了是不会出现动画的，如果是受这个原因影响的话，我们可以提供配置启动时间的选项。

很抱歉，目前无法提供片段；但可能是这个原因，我在beforeEach里start()，但在afterEach里使用LoadingBar.error()是正常的，唯独换成finish没有再出现动效了

**Comment by magnificent007** [comment]
也试过在afterEach里不写任何的LoadingBar，只在beforeEach中LoadingBar.start()，切换tabbar的时候是有重新开始加载的动效，但一旦在afterEach内finish()则不会再出现动效表现了

**Comment by haoziqaq** [comment]
你可以尝试在 afterEach 里加入 300ms 的延迟

```
router.afterEach(() => {
  setTimeout(() => {
    LoadingBar.finish()
  }, 300)
})
```

**Comment by magnificent007** [comment]
> 你可以尝试在 afterEach 里加入 300ms 的延迟
> 
> ```
> router.afterEach(() => {
>   setTimeout(() => {
>     LoadingBar.finish()
>   }, 300)
> })
> ```

成功解决，看来确实是这个问题在影响着；请问后期会把这个配置开放出来吗？

**Comment by haoziqaq** [comment]
嗯，会的。不过还是建议保持默认配置，因为对于速度比较快的网页加载来说，不显示一闪而过的加载动画可能是一种体验更好的做法。
