### ISSUE TITLE
发布到npm，无法使用

### ISSUE THREAD

**Issue by immortalts** [varletjs/varlet#1729]
# Bug report 🐞

## Version & Environment
"@varlet/cli": "^3.3.11",
node：18.2.0
## Expectation
varlet-cli compile后，进行 varlet-cli release发布到npm，完全没有动的初始环境（@varlet/cli和引用组件的vue3环境都为初始化）。但是install后引用，报错，找不到路径
## Reproduction link
![image](https://github.com/user-attachments/assets/b2ebd0c0-0019-4b7a-a8ce-16527cfda447)

**Comment by haoziqaq** [comment]
"@varlet/shared" 调整到 dependencies 里，或者从项目中移除 "@varlet/shared"。下个 patch 版本我们也会对该依赖进行调整。

**Comment by haoziqaq** [comment]
https://github.com/varletjs/varlet/commit/fb9c67dfb1f22aff99719ed0ff290edf342abceb
