### ISSUE TITLE
可否增加侧滑界面，方便将一些交互收到这里

### ISSUE THREAD

**Issue by heirychen** [varletjs/varlet#1730]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

![demo](https://github.com/user-attachments/assets/e462caf0-cadf-4603-8427-40a55cb4b772)

**Comment by haoziqaq** [comment]
Popup 组件就是



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 中午11:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 可否增加侧滑界面，方便将一些交互收到这里 (Issue #1730)




 
Feature request 🚀
 
Expected:
  
No breaking changes
  
Examples:
 
11.jpg (view on web)

**Comment by heirychen** [comment]
太粗心了，感谢。。

**Comment by elarbor** [comment]
web端可以用吗？我只想要表单组件
