### ISSUE TITLE
build后，from包含 space 中，动态添加input，导致数据异常

### ISSUE THREAD

**Issue by Kunoky** [varletjs/varlet#1731]
# Bug report 🐞

## Reproduction link
[reproduction.zip](https://github.com/user-attachments/files/16579806/reproduction.zip)

**Comment by Kunoky** [comment]
此外，label的for属性时常出现空

**Comment by haoziqaq** [comment]
看起来是 vue diff 列表产生了错误的 patch，可以先通过给 space 组件内的 item 标记唯一的 key 解决。

**Comment by haoziqaq** [comment]
v3.3.14 修复了这个问题。
