### ISSUE TITLE
form扩展验证

### ISSUE THREAD

**Issue by magnificent007** [varletjs/varlet#1747]
### 关于form扩展验证问题，文档内只有单个字段，我想扩展多个字段的验证，rules 和 validateData 该以什么样的形式传入进行验证呢？

**Comment by chouchouji** [comment]
可以参考这里 [https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/form/example/index.vue](https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/form/example/index.vue)

**Comment by haoziqaq** [comment]
`:rules="[() => model.name.length > 6 || 'Error', () => model.age > 10 || 'Error']"`
也是一样的～

**Comment by magnificent007** [comment]
> `:rules="[() => model.name.length > 6 || 'Error', () => model.age > 10 || 'Error']"` 也是一样的～

可以确定rules是个数组函数，我就是不清楚验证的数据要用什么格式？对象数组形式还是什么其它的格式？

**Comment by magnificent007** [comment]
> 可以参考这里 https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/form/example/index.vue
> 
> 里面有个 `VarCustomFormComponent` 组件，拓展多个可以参考这个组件封装

查看了，但是还是不清楚，验证的数据需要什么格式？可以确定rules是个函数数组，验证的数据是否也要用对象数组？

**Comment by magnificent007** [comment]
> 可以参考这里 https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/form/example/index.vue
> 
> 里面有个 `VarCustomFormComponent` 组件，拓展多个可以参考这个组件封装

查看了，但是还是不清楚，验证的数据需要什么格式？可以确定rules是个函数数组，验证的数据是否也要用对象数组？

**Comment by haoziqaq** [comment]
不对验证数据格式有要求呀？本质 rules 是一个验证函数数组，组件自行判断验证时机，验证的时候只是执行函数，用户怎么写的就怎么执行。

**Comment by magnificent007** [comment]
> 不对验证数据格式有要求呀。本质 rules 是一个验证函数数组，组件自动判断验证时机，验证的时候只是执行函数，用户怎么写的就怎么执行。

不是的，您可能没理解我的意思。rules是个函数数组，我理解没有问题；我想知道的是需要验证的数据需要传入什么格式？

**Comment by haoziqaq** [comment]
没有格式要求。input 绑定的是什么值就验证什么值。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月5日(周四) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] form扩展验证 (Issue #1747)




  
不对验证数据格式有要求呀。本质 rules 是一个验证函数数组，组件自动判断验证时机，验证的时候只是执行函数，用户怎么写的就怎么执行。
  
不是的，您可能没理解我的意思。rules是个函数数组，我理解没有问题；我想知道的是需要验证的数据需要传入什么格式？

**Comment by magnificent007** [comment]
> 没有格式要求。input 绑定的是什么值就验证什么值。

没有用input哦，里面是我自定义的输入操作，下面我提供下代码片段

**Comment by haoziqaq** [comment]
![image](https://github.com/user-attachments/assets/b27ebffa-ea91-4ff0-a413-15e0edd423e8)
![image](https://github.com/user-attachments/assets/e18a5594-5916-4d59-88c1-28ba43b20c69)
我这边没问题，你这边提供的 tsx 代码可能存在问题，可以尝试按照图2修复。
