### ISSUE TITLE
表单组件没有 label props 吗？

### ISSUE THREAD

**Issue by miyagipipi** [varletjs/varlet#1748]
# Feature request 🚀

### Expected:

- 我看官方文档的相关示例，都没有 label 可用（输入框左侧文本），想问下是设计如此吗？

**Comment by haoziqaq** [comment]
![image](https://github.com/user-attachments/assets/f480c48a-00bb-47fb-8bea-6a9b08008f3c)
![image](https://github.com/user-attachments/assets/9dff955e-6361-4d87-98ad-9016750ca4af)
Material Design 设计如此，如果需要独立于组件之外的 label，建议自行封装。

**Comment by chouchouji** [comment]
如果还有疑问的话，欢迎在此issue或者社区群留言
