### ISSUE TITLE
Tooltip 自定义颜色的文字颜色

### ISSUE THREAD

**Issue by peiyanlu** [varletjs/varlet#1749]
# About `styles` 🛠️

如图所示， Tooltip 支持 `color` 自定义颜色（背景颜色）但是文字颜色仍是默认，请问为何不支持同样的形式设置文字颜色（例如：`text-color`），感觉相对更改CSS变量，这种方式更方便
![image](https://github.com/user-attachments/assets/5a02f205-1ced-488c-9490-2dade3ca605f)

**Comment by chouchouji** [comment]
![image](https://github.com/user-attachments/assets/08714d54-968f-490c-92af-4dd124820bd6)

可以使用 content slot自定义内容

**Comment by chouchouji** [comment]
会添加一个 `text-color` 的 属性，有需要请关注下本周的发版

**Comment by chouchouji** [comment]
@cszhjh

**Comment by peiyanlu** [comment]
> 会添加一个 `text-color` 的 属性，有需要请关注下本周的发版

好的 谢谢
