### ISSUE TITLE
[Feature] add tooltips for the buttons that in the code example

### ISSUE THREAD

**Issue by LoTwT** [varletjs/varlet#1783]
# About `docs`

<img width="864" alt="image" src="https://github.com/user-attachments/assets/f45c7940-438b-46a5-8f29-861865914d30">

When hovering on the buttons in the code examples, there are no hints about what the button does. It may be a little confusing for new users because icon designs are various and not all people can get access to the meaning of the icons in this current design.

Adding tooltips or designing a more friendly interaction may bring a better experience.

**Comment by chouchouji** [comment]
Thanks for your feedback! I think it is a good idea. We will consider it in recent days.

**Comment by chouchouji** [comment]
It has been accomplished. You will see it in [https://varletjs.org/#/zh-CN/button](https://varletjs.org/#/zh-CN/button)
![image](https://github.com/user-attachments/assets/d4fe42d1-d16b-4a9b-b7f0-7c5692d6e492)
