### ISSUE TITLE
问题：有外边框的input，在聚焦时，移至顶部的placeholder右侧有空隙

### ISSUE THREAD

**Issue by SnowdropK** [varletjs/varlet#1803]
# Bug report 🐞
版本：2.13.1
有外边框的input，在聚焦时，移至顶部的placeholder右侧有空隙。
mac上显示正常，但在windows系统有如上问题，浏览器都是chrome

window系统如下显示异常：
![777](https://github.com/user-attachments/assets/f9b7dcee-154b-45fd-87f5-e93248cd447a)

mac显示正常
![888](https://github.com/user-attachments/assets/b3bfac0e-08d1-4b2e-9f9a-8a47ec6b67dd)

**Comment by haoziqaq** [comment]
2.x 版本可能过于陈旧了，3.x 版本应该是没有这个问题。

**Comment by cszhjh** [comment]
> > 2.x 版本可能过于陈旧了，3.x 版本应该是没有这个问题（在 2.x 后期的版本中我们对 input select 进行了一次重构）
> 
> 请问重构的2.x是哪个版本，我先试下能不能用。

建议升级到2.13.3以上的版本，2.13.3之后都没有发现存在这个问题
