### ISSUE TITLE
在router-stack组件下使用Snackbar函数调用，会默认append body

### ISSUE THREAD

**Issue by ST-log** [varletjs/varlet#1818]
# Bug report 🐞

官方提供的模板项目，页面在stacks文件下，
router-stack组件使用Snackbar函数调用， 样式不生效

此时一个奇怪现象，我只要在这里放一个组件 <var-snackbar  > 这是一个消息条！！</var-snackbar>
函数调用的样式就正常

## Version & Environment
"@varlet/ui": "3.5.2",
 "@varlet/use": "3.5.2",
## Expectation

不知道可不可以在函数调用也加一个teleport配置，我看样式类型里只在属性上加了

## Actual results (or Errors)

希望

**Comment by haoziqaq** [comment]
未复现问题，请提供一个最小可复现的仓库或在线示例代码。

**Comment by ST-log** [comment]
https://gitee.com/test-varlet/test.git   
github传不上去

**Comment by haoziqaq** [comment]
### 解决方法

utils/snackbar.ts

```diff
- import { Snackbar, SnackbarOptions } from '@varlet/ui'
+ import { SnackbarOptions } from '@varlet/ui'
```

这是因为自动导入插件的机制决定了，当你手动引入 Snackbar 时，会默认认为你不需要自动导入 Snackbar 的副作用（如样式）。
总之，避免手动引入 Varlet 相关功能 (类型除外) 即可。

**Comment by ST-log** [comment]
明白
