### ISSUE TITLE
希望可以支持小程序

### ISSUE THREAD

**Issue by yuWorm** [varletjs/varlet#1819]
# Feature request 🚀
感谢各位大佬实现了这么棒的ui库，个人感觉移动端这一块主要是小程序，希望未来能够支持小程序
### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by haoziqaq** [comment]
未来不出意外是不会支持小程序了，原因可以参考这个 [issue](https://github.com/varletjs/varlet/issues/753)，希望理解～。

**Comment by yuWorm** [comment]
好的，我尝试webview hybrid吧
