### ISSUE TITLE
Switch组件能否提供一个选中/非选中时的文字提示

### ISSUE THREAD

**Issue by JayChen953641513** [varletjs/varlet#1820]
# Feature request 🚀

### Expected:
我希望在使用Switch组件的时候能有一个属性或者插槽能让我在如下位置添加对应的选中状态描述：
![image](https://github.com/user-attachments/assets/053ec729-4f49-49bc-a166-fc59f024e713)
![image](https://github.com/user-attachments/assets/62a938e3-de0d-49f8-92e5-e4a8905d648d)

**Comment by haoziqaq** [comment]
好的，但短期内可能不会新增该特性，会在后续的版本中新增。

**Comment by elarbor** [comment]
> 好的，但短期内可能不会新增该特性，会在后续的版本中新增。

能不能开通GitHub discussion啊

**Comment by haoziqaq** [comment]
> > 好的，但短期内可能不会新增该特性，会在后续的版本中新增。
> 
> 能不能开通GitHub discussion啊

开了
