### ISSUE TITLE
[Feature] Tooltip 的 reference 属性能不能支持直接使用 Element 的引用

### ISSUE THREAD

**Issue by zhujianxintian** [varletjs/varlet#1822]
# Feature request 🚀
Tooltip 的 reference 属性能不能支持直接使用 Element 的引用，因为我的有些元素就是动态生成的，我看源代码中是在 onMounted 的时候就确定好了元素的, 如果 reference 发生变化了，引用变了，那么就重新执行绑定操作

1、比如我在使用高德地图的时候，先从 api 中获取数据，然后高德地图去渲染出对应的 marker，然后我再把 marker 的引用给 Tooltip
但是在我这些做步骤之前，就已经在 onMounted 中确定好了触发元素，我无法动态改变触发元素

https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/menu/usePopover.ts#L59

2、本来看源代码之前就想到过一个方法应该可以，就是对页面中的 Tooltip 使用 v-if，预先传入 reference 选择器选中元素，的然后在地图渲染完成之后在设为 true，这个时候 marker 应该是存在了的，所以 usePopover 里面的 onMounted 应该是可以做到的，但是 Tooltip 的 reference 属性不生效，然后看了下源代码，`host.value!.querySelector(options.reference)!` 他是直接基于子元素里面进行查找的，所以地图组件要放在 Tooltip 里面才行，但是因为地图组件才会触发 init，去请求数据和动态生成 marker，Tooltip 又要等地图渲染完成之后 v-if 才为 true，这样就会都不渲染了，没有一个会触发

如果是 document.querySelector 的话估计可以

下面这个代码就是我现在的困境
```vue
<script setup>
const markerTooltipRef = ref();

const isMapRendered = ref(false);

const handleChangeMarkerLocation = () => {
    // 1. 改变 marker 的位置...

    // 2. 重置 tooltip 位置
    markerTooltipRef.value?.resize();
};

const handleInit = async () => {
    // 1. 接口请求...

    // 2. 添加 marker 到地图中...

    // 3. tooltip 可以开始渲染，并且通过 reference 去查找对应的 DOM 元素 (这个步骤只会在 onMounted 的时候执行, 所以只能使用条件渲染来触发)
    isMapRendered.value = true;
};
</script>

<template>
    <div class="container">
        <!-- isMapRendered 永远为 false, 因为更改 isMapRendered 的逻辑在 handleInit 中, 但是 handleInit 会因为 AMap 没有渲染，导致永远无法执行  -->
        <var-tooltip v-if="isMapRendered" ref="markerTooltipRef" reference=".amap-marker" placement="top" content="Tooltip">
            <div style="width: 100%; height: 100%">
                <AMap @init="handleInit"></AMap>
            </div>
        </var-tooltip>
        <var-button @click="handleChangeMarkerLocation">伪代码, 用来改变 marker 位置的按钮</var-button>
    </div>
</template>

<style lang="scss" scoped>
.container {
    :deep(.var-tooltip) {
        width: 100%;
        height: 100%;
    }
}
</style>
```

### Expected:

1. 希望能增加一个 setReference 的方法，传入 Element 或者选择器字符串，动态更改和重新绑定（如果是 reference 属性变更了也会动态重新绑定）
2. 希望 reference 属性是使用 document.querySelector 来查找元素，那样我的 v-if 代码也能生效

下面的代码就是我想要的样子
```vue
<script setup>
const markerTooltipRef = ref();

const handleChangeMarkerLocation = () => {
    // 1. 改变 marker 的位置...

    // 2. 重置 tooltip 位置
    markerTooltipRef.value?.resize();
};

const handleInit = async () => {
    // 1. 接口请求...

    // 2. 添加 marker 到地图中...

    // 3. tooltip 的 reference 可以切换到已经生成的 DOM 元素
    const markerEl = document.querySelector('.amap-marker');
    markerTooltipRef.setReference(markerEl);
};
</script>

<template>
    <div class="container">
        <div style="width: 100%; height: 100%">
            <AMap @init="handleInit"></AMap>
        </div>
        <var-tooltip ref="markerTooltipRef" reference=".amap-marker" placement="top" content="Tooltip"> </var-tooltip>
        <var-button @click="handleChangeMarkerLocation">伪代码, 用来改变 marker 位置的按钮</var-button>
    </div>
</template>

<style lang="scss" scoped>
.container {
    :deep(.var-tooltip) {
        width: 100%;
        height: 100%;
    }
}
</style>
```

**Comment by zhujianxintian** [comment]
@haoziqaq 
可以的，这两个都可以满足我的需求。
但是我有点想不通的问题是关于 "不支持响应 reference 的变化"，这个应该是可以实现的，监听并且重新绑定即可。
是因为以前就不会响应变化，所以和以前的行为保持一致吗，还是有什么其他的具体考量？
当然不实现这个响应，其他两个我也是可以满足需求的（使用 1 + v-if 或者只是用 2 皆可），只是好奇具体原因

**Comment by haoziqaq** [comment]
可能会产生隐含的破坏性更新，并且这是一个相对边缘的案例，setReference 和 watch reference 不会有太大体验差距。所以感觉新增一个实例方法合适一些。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 上午9:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] [Feature] Tooltip 的 reference 属性能不能支持直接使用 Element 的引用 (Issue #1822)




 
@haoziqaq
 可以的，这两个都可以满足我的需求。
 但是我有点想不通的问题是关于 "不支持响应 reference 的变化"，这个应该是可以实现的，监听并且重新绑定即可。
 是因为以前就不会响应变化，所以和以前的行为保持一致吗，还是有什么其他的具体考量？
 当然不实现这个响应，其他两个我也是可以满足需求的（使用 1 + v-if 或者只是用 2 皆可），只是好奇具体原因

**Comment by zhujianxintian** [comment]
@haoziqaq 嗯嗯，了解了

**Comment by haoziqaq** [comment]
可以提前尝试测试版本 3.7.2-alpha.1733245375527 

```html
<script setup>
import { ref, onMounted } from 'vue'

const tooltip = ref()
const reference = ref()

onMounted(() => {
  tooltip.value.setReference(reference.value.$el)
})
</script>
<template>
  <var-tooltip ref="tooltip">
    <template #content>
      Tooltip Content
    </template>
  </var-tooltip>

  <var-button ref="reference">Reference</var-button>
</template>
```

**Comment by zhujianxintian** [comment]
@haoziqaq 试用了一下，没问题

以下单纯为个人建议，可以考究之后再看是否接受

建议：
https://github.com/varletjs/varlet/blob/0c784c30e818c7079e5bf1932299548263a14334/packages/varlet-ui/src/menu/usePopover.ts#L410

就是如果在这一行加一个警告或者报错感觉会更好
因为我忘记去掉我写在页面组件的 reference 属性了，又因为我这个元素是运行时动态生成的，然后导致在执行完 https://github.com/varletjs/varlet/blob/0c784c30e818c7079e5bf1932299548263a14334/packages/varlet-ui/src/menu/usePopover.ts#L98
代码：`onMounted(createPopperInstance)`

之后

https://github.com/varletjs/varlet/blob/0c784c30e818c7079e5bf1932299548263a14334/packages/varlet-ui/src/menu/usePopover.ts#L105
代码：`reference.addEventListener('mouseenter', handleReferenceMouseenter)`
这里发生了报错，会导致开发者没有那么快的发现错误位于哪个地方 (其实就是我传入了 reference 字符串属性, 然后 onMounted 的时候查找不到, 报错了)


类似以下，或者使用你感觉更好的方式

```ts
function getReference() {
    const targetReference = reference ?? options.reference ?? host.value;

    if (!isString(targetReference)) {
        return targetReference;
    }

    const targetReferenceBySelector = host.value?.querySelector(targetReference);

    if (__DEV__) {
        assert(targetReferenceBySelector, `[${COMPONENT_NAME}]: the "reference" attribute '${targetReference}' is not found.`);
    }

    return targetReferenceBySelector;
}
```

其他的没有问题了

**Comment by haoziqaq** [comment]
感谢建议，这个议题我们早期内部有过讨论，结论是只会在特别主要case上对用户进行 warn，尽可能通过文档去规避一些常见的使用问题。


主要原因还是因为就UI库的复杂度和排查难度来看可能不太需要在每个分支上步步为营，可能会造成 warn 的泛滥导致一些没必要的维护压力。


还是非常感谢您的建议，这是一个很有帮助的 feature request🌸



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月4日(周三) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] [Feature] Tooltip 的 reference 属性能不能支持直接使用 Element 的引用 (Issue #1822)




 
@haoziqaq 试用了一下，没问题
 
以下单纯为个人建议，可以考究之后再看是否接受
 
建议：
 https://github.com/varletjs/varlet/blob/0c784c30e818c7079e5bf1932299548263a14334/packages/varlet-ui/src/menu/usePopover.ts#L410
 
就是如果在这一行加一个警告或者报错感觉会更好
 因为我忘记去掉我写在页面组件的 reference 属性了，又因为我这个元素是运行时动态生成的，然后导致在执行完 https://github.com/varletjs/varlet/blob/0c784c30e818c7079e5bf1932299548263a14334/packages/varlet-ui/src/menu/usePopover.ts#L98
 代码：onMounted(createPopperInstance)
 
之后
 
https://github.com/varletjs/varlet/blob/0c784c30e818c7079e5bf1932299548263a14334/packages/varlet-ui/src/menu/usePopover.ts#L105
 代码：reference.addEventListener('mouseenter', handleReferenceMouseenter)
 这里发生了报错，会导致开发者没有那么快的发现错误位于哪个地方 (其实就是我传入了 reference 字符串属性, 然后 onMounted 的时候查找不到, 报错了)
 
类似以下，或者使用你感觉更好的方式
 function getReference() {     const targetReference = reference ?? options.reference ?? host.value;     if (!isString(targetReference)) {         return targetReference;     }     const targetReferenceBySelector = host.value?.querySelector(targetReference);     if (__DEV__) {         assert(targetReferenceBySelector, `[${COMPONENT_NAME}]: the "reference" attribute '${targetReference}' is not found.`);     }     return targetReferenceBySelector; }
 
其他的没有问题了

**Comment by zhujianxintian** [comment]
@haoziqaq 好的，辛苦啦，可以理解你们的想法。还有就是关于这个 issue 没有问题了

**Comment by haoziqaq** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月4日(周三) 中午11:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] [Feature] Tooltip 的 reference 属性能不能支持直接使用 Element 的引用 (Issue #1822)

好的


 
@haoziqaq 好的，辛苦啦，可以理解你们的想法。还有就是关于这个 issue 没有问题了
