### ISSUE TITLE
Menu-Select,Auto-Complete等弹出组件在overlay组件中行为异常

### ISSUE THREAD

**Issue by DawnCatch** [varletjs/varlet#1828]
# Bug report 🐞

## Expectation
点击空白处(非overlay遮罩)将Menu-Select,Auto-Complete等弹出组件的弹出层关闭

## Actual results (or Errors)
![image](https://github.com/user-attachments/assets/4a8b4844-3eee-476d-9c0a-055f260e0e9a)
点击空处时,无法关闭弹出层
Auto-Complete的表现为一直持有焦点,点击其他的Input也无法转移焦点
Menu-Select的表现为无法关闭Option-Slot

**Comment by haoziqaq** [comment]
已复现问题，将在下个版本进行修复，可先用 popup 替代。

**Comment by haoziqaq** [comment]
修复于 3.7.4-alpha.1734454650011
