### ISSUE TITLE
想问问 varlet-cli 使用gen命令生成项目的时候报错的解决方案

### ISSUE THREAD

**Issue by Cynthia0329** [varletjs/varlet#269]
![image](https://user-images.githubusercontent.com/30437028/148512015-30435e4a-0f35-413c-8ffe-9dfbe77c5fde.png)

https://varlet.gitee.io/varlet-ui/#/zh-CN/cli
按照这里的步骤来的

应该就是es2020可选链的问题
我太菜了😭，项目里报这个错还可以用babel兼容，生成项目的时候报错怎么解决啊😂

**Comment by haoziqaq** [comment]
你可以升级一下你的node版本，组件库cli相关的插件我们都是默认用户环境是一个较新node环境去做的

**Comment by haoziqaq** [comment]
我们后面可能会考虑把开发的环境整体向下兼容一下，不过最近一小段时间可能不会做这个事情，你可以先升级node到最新的稳定版解决
