### ISSUE TITLE
DatePicker Component error with "modelValue" is an Invalid Date

### ISSUE THREAD

**Issue by Banana-energy** [varletjs/varlet#277]
# Feature request 🚀

### Expected:

- When the initial value is '' or undefined, don't warn I "modelValue" is an invalid date.

### Examples:

```vue
<template>
    <var-date-picker v-model="date" />
</template

<script setup>
import { ref } from "vue";

const date = ref('');
</script>
```

**Comment by BeADre** [comment]
You should change your initial value beaucse ths format of `modalValue` is `ISO 8601, YYYY-MM-DD or YYYY-MM`

**Comment by Banana-energy** [comment]
But I don't want to have initial value

**Comment by BeADre** [comment]
will be fixed soon

**Comment by Banana-energy** [comment]
thanks
