### ISSUE TITLE
No event is fired when changing the size of the pagination component

### ISSUE THREAD

**Issue by Banana-energy** [varletjs/varlet#279]
# Feature request 🚀

### Expected:

- Notify me when the size of the page-turning component changes

### Examples:

See the next example

[Example](https://codepen.io/BananaEnergy/pen/XWeyLJR)

**Comment by haoziqaq** [comment]
Ok, we will add v-model:current and v-model:size in a later version, currently you can use `@change` to synchronize the state of size and current

**Comment by Banana-energy** [comment]
> Ok, we will add v-model:current and v-model:size in a later version, currently you can use `@change` to synchronize the state of size and current

thanks, but when I change the size through the pagination component, the `@change` event is not triggered

**Comment by haoziqaq** [comment]
Ok, let's check it out, it will be included in the next release
