### ISSUE TITLE
为 Button 增加一个 autoLoading 功能

### ISSUE THREAD

**Issue by a145789** [varletjs/varlet#281]
# Feature request 🚀

### Expected:

为 Button 增加一个 autoLoading 功能，如果传入的 @click function 返回一个 promise ，那 Button 组件内部开启 loading ，等待传入的 function promise resolve 或者 reject ，结束 loading ，这样就不用手动在外边维护一个 loading 状态了

- No breaking changes

### Examples:

```js
<var-button autoLoading type="primary" @click="handle">

setup(){
    const handle = async ()=>{
        await fetch(...)
    }
    return { handle }
}

```

**Comment by haoziqaq** [comment]
看上去不错

**Comment by haoziqaq** [comment]
下个版本会加入这个功能，感谢～
