### ISSUE TITLE
The modelValue of the input component is of the wrong type

### ISSUE THREAD

**Issue by Banana-energy** [varletjs/varlet#282]
# Bug report 🐞

## Version & Environment
varlet 1.24.4
node 16.13.0
vue 3.2.26
## Expectation
When I select the type of input as number, the type of modelValue should be number

**Comment by haoziqaq** [comment]
The current behavior is consistent with the native behavior, we think it is easier to understand always getting a string, if you need a number type component, it is recommended to try <var-counter />

**Comment by haoziqaq** [comment]
The current behavior is consistent with the native behavior, we think it is easier to understand always getting a string, if you need a number type component, it is recommended to try `counter`
