### ISSUE TITLE
add a new component: SearchBar

### ISSUE THREAD

**Issue by xyz-fish** [varletjs/varlet#285]
# Feature request 🚀

### Expected:

i want have a search functional component

when use AppBar i sometime have need search

- No breaking changes

### Examples:

```js

```

**Comment by haoziqaq** [comment]
We think that the search bar is a very business-oriented component. The search bar can be easily implemented with var-input. If it is made into a component lib, a large number of configuration items need to be provided for customization, so we do not consider it.
