### ISSUE TITLE
Ripple无效果

### ISSUE THREAD

**Issue by estoi** [varletjs/varlet#292]
# Bug report 🐞
使用的Button组件 无水波纹效果，通过引入Ripple指令添加也无效果
## Version & Environment
"@varlet/ui": "^1.24.11"
"vite": "^2.7.2"
## Expectation
预期点击button出现水波纹效果
## Actual results (or Errors)
未出现水波纹效果

## Code
![image](https://user-images.githubusercontent.com/44252820/149858685-e0f411f5-14da-47bd-90e2-39216d5df1b4.png)
![image](https://user-images.githubusercontent.com/44252820/149858736-970c6c4d-cdfd-472e-aedf-c9c8b4196a55.png)
![image](https://user-images.githubusercontent.com/44252820/149858753-b0a0934e-9298-435d-ae13-dc6391c4776e.png)

https://codesandbox.io/s/polished-microservice-k8cye?file=/index.html

**Comment by estoi** [comment]
@haoziqaq

**Comment by haoziqaq** [comment]
你如果是在桌面端使用，需要加一个插件去适配touch事件，因为我们所有的手势都是基于touch实现的，
详情看这里的桌面端适配部分 https://varlet.gitee.io/varlet-ui/#/zh-CN/browserAdaptation
