### ISSUE TITLE
Nuxt3 环境下 IndexBar 组件 IndexAnchor 宽度异常

### ISSUE THREAD

**Issue by zhenyuWang** [varletjs/varlet#296]
# Bug report 🐞

初始进入页面，IndexAnchor 宽度异常，滚动或者刷新后恢复正常

<img width="398" alt="indexBar nuxt bug" src="https://user-images.githubusercontent.com/37523000/150168148-11b66665-d980-44b9-a01d-e94bf381cf5f.png">

## Version & Environment
"@varlet/ui": "^1.24.11",
"nuxt3": "latest",

node v16.13.0
## Expectation
<img width="406" alt="nuxt3 indexBar expecation" src="https://user-images.githubusercontent.com/37523000/150168405-7ada727b-8c94-428a-95d6-fe05546d88fa.png">

**Comment by BeADre** [comment]
fixed by [this](https://github.com/varletjs/varlet/commit/6c7df9f4b218ca4174f610262112dbe8567fecc1)
