### ISSUE TITLE
AppBar切换主题

### ISSUE THREAD

**Issue by jnwx** [varletjs/varlet#299]
# About `styles` 🛠️
当我切换主题时，AppBar的背景色无法一起切换，我使用了下面的代码来控制整个app的主题：
```
* {
  transition: background-color 0.25s;
  color: var(--color-text);
  background-color: var(--color-body);
}
```
而且运用了这个代码后switch开关的按钮样式也会受影响，不美观了。
![高亮模式](https://user-images.githubusercontent.com/97720555/150631238-ad58fd53-b6c6-4646-bc5c-96086998b1ad.png)
切换后：
![深色模式](https://user-images.githubusercontent.com/97720555/150631264-48b6ddbd-06b7-46ef-aef5-52fbab81e677.png)

**Comment by haoziqaq** [comment]
最好不要使用*去匹配所有的元素，推荐只把那两个变量注入到body上

**Comment by jnwx** [comment]
> 最好不要使用*去匹配所有的元素，推荐只把那两个变量注入到body上

那就是AppBar在切换时再单独去控制背景色，感觉能不能优化下，让AppBar也能一起简单切换😁🍖🍗

**Comment by haoziqaq** [comment]
emmmmmm， 其实是因为，app-bar在暗黑模式下也是蓝色，是一种相对亮色的蓝，你是觉得在暗黑模式下app-bar也是黑色会好一些？

**Comment by jnwx** [comment]
> emmmmmm， 其实是因为，app-bar在暗黑模式下也是蓝色，是一种相对亮色的蓝，你是觉得在暗黑模式下app-bar也是黑色会好一些？

必须啊，我是在做Electron桌面应用，切换主题得统一。

**Comment by haoziqaq** [comment]
你其实可以修改暗黑主题文件appbar对应的默认主题颜色变量去达到你的目的，因为主题都是可以直接定制的，可以作为一个暂时方案
我们也想考虑一下appbar的默认颜色是不是应该搞成黑色和白色，而不是现在的蓝色



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月23日(周日) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] AppBar切换主题 (Issue #299)




  
emmmmmm， 其实是因为，app-bar在暗黑模式下也是蓝色，是一种相对亮色的蓝，你是觉得在暗黑模式下app-bar也是黑色会好一些？
  
必须啊，我是在做Electron桌面应用，切换主题得统一。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoziqaq** [comment]
dark mode下我们把蓝色修改成了黑色，light mode下维持现在不变，会在下个小版本中更新
