### ISSUE TITLE
Sticky（置顶）图标

### ISSUE THREAD

**Issue by jnwx** [varletjs/varlet#301]
# Feature request 🚀

### Expected:

希望能增加图钉图标，App有窗口置顶的需求。当然可以用其它源的图标，但还是希望风格统一。

**Comment by haoziqaq** [comment]
你可以pr上来 或者在material的图标库找到截图给我们，图标数量不大我们是愿意内置的，还有一部分预留的空间



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月23日(周日) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] Sticky（置顶）图标 (Issue #301)




 
Feature request 🚀
 
Expected:
 
希望能增加图钉图标，App有窗口置顶的需求。当然可以用其它源的图标，但还是希望风格统一。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jnwx** [comment]
like these:
![图片](https://user-images.githubusercontent.com/97720555/150667082-e0398715-9200-4a07-92a9-2d3ea813263b.png)
![图片](https://user-images.githubusercontent.com/97720555/150667083-684243e7-a715-485a-8022-5c47d848b01a.png)

**Comment by haoziqaq** [comment]
下个版本会带有新图标
