### ISSUE TITLE
Unwanted scroll rail under at the bottom side of selects

### ISSUE THREAD

**Issue by gevorgmelkumyan** [varletjs/varlet#305]
# Bug report 🐞
When changing the selected value of a select, there's a scroll rail showing up at the bottom for about a second and then disappears. Below is the video that describes the bug:
[Select bug](https://vimeo.com/670216424/67cc2163a6)

## Version & Environment
`"@varlet/ui": "^1.25.0"`
`"vue": "^3.0.0"`
`"@varlet/touch-emulator": "^1.25.0"`

## Expectation
The select should open and close without any unexpected overflow issues.

## Actual results (or Errors)
A rail at the bottom of the select appears and disappears when the dropdown is opening, closing or a certain value is selected for the first time.

**Comment by haoziqaq** [comment]
I have not reproduced this problem in my local environment.
Can you provide a demo that minimizes the reproduction problem?

**Comment by gevorgmelkumyan** [comment]
> I have not reproduced this problem in my local environment. Can you provide a demo that minimizes the reproduction problem?

Sure thing, I've recreated the issue in this snipped:
[CodePen](https://codepen.io/-gevorg-melkumyan/pen/PoOwZgO)

**Comment by haoziqaq** [comment]
This one doesn't seem to have scroll bars, what browser are you using？

**Comment by gevorgmelkumyan** [comment]
@haoziqaq Chromium Version 97.0.4692.99 (Official Build) snap (64-bit) on Ubuntu 20.04 LTS

**Comment by haoziqaq** [comment]
The problem should be fixed, it will be fixed in the next patch version, thank you for your feedback

**Comment by gevorgmelkumyan** [comment]
@haoziqaq thank you too!
