### ISSUE TITLE
List组件load事件无法正确触发

### ISSUE THREAD

**Issue by illisac** [varletjs/varlet#310]
# Bug report 🐞
List滚动到底后load事件偶尔无法正确触发

## Version & Environment
Chrome / Firefox ...

## Expectation
在不设置offset属性的情况下 正确触发load事件

## Actual results (or Errors)
位置 packages/varlet-ui/src/list/List.vue Line 54
```javascript
const isReachBottom = () => {
  const containerBottom =
    scroller === window ? window.innerHeight : (scroller as HTMLElement).getBoundingClientRect().bottom
  const { bottom: detectorBottom } = (detectorEl.value as HTMLElement).getBoundingClientRect()
  return detectorBottom - toPxNum(props.offset) <= containerBottom
}
```
当容器为window时, 由于获取innerHeight 和 底部元素getBoundingClientRect精度问题, 导致return false

**Comment by haoziqaq** [comment]
有可以复现的demo么

**Comment by haoziqaq** [comment]
https://varlet.gitee.io/varlet-ui-playground/
可以尝试用在线的repl复现问题反馈给我们

**Comment by illisac** [comment]
> https://varlet.gitee.io/varlet-ui-playground/ 可以尝试用在线的repl复现问题反馈给我们
试试这个
body默认margin置为0会出现这个问题
https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWFjdGl2ZSwgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG5cbmNvbnN0IGxvYWRpbmcgPSByZWYoZmFsc2UpXG4gICAgY29uc3QgZmluaXNoZWQgPSByZWYoZmFsc2UpXG4gICAgY29uc3QgbGlzdCA9IHJlYWN0aXZlKFtdKVxuXG4gICAgY29uc3QgbG9hZCA9ICgpID0+IHtcbiAgICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICBmb3IgKGxldCBpID0gMDsgaSA8IDIwOyBpKyspIHtcbiAgICAgICAgICBsaXN0LnB1c2gobGlzdC5sZW5ndGggKyAxKVxuICAgICAgICB9XG5cbiAgICAgICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlXG4gICAgICB9LCAxMDAwKVxuICAgIH1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgc3R5bGU9XCJ3aWR0aDogMTAwJTsgaGVpZ2h0OiAzMDBweDtiYWNrZ3JvdW5kOiBncmF5XCI+PC9kaXY+XG4gIDx2YXItbGlzdFxuICA6ZmluaXNoZWQ9XCJmaW5pc2hlZFwiXG4gIHYtbW9kZWw6bG9hZGluZz1cImxvYWRpbmdcIlxuICBAbG9hZD1cImxvYWRcIlxuPlxuICA8dmFyLWNlbGwgOmtleT1cIml0ZW1cIiB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiPlxuICAgIOWIl+ihqOmhuToge3sgaXRlbSB9fVxuICA8L3Zhci1jZWxsPlxuPC92YXItbGlzdD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgYm9keSB7XG4gICAgbWFyZ2luOiAwO1xuICB9XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==

**Comment by haoziqaq** [comment]
是不是因为第一页的数据没有撑满一屏导致的，因为没撑满一屏的情况下，无法滚动，就没办法进行位置检测。

**Comment by illisac** [comment]
应该不是，在线例子里20条数据是撑满了的。
拉到底部，调试结果就像图里一样。获取到底部元素的bottom比window.innerHeight溢出一点点
![微信截图_20220212004833](https://user-images.githubusercontent.com/97740841/153708927-aa72e99f-0548-418f-8669-1ceb0333ab06.png)
![微信截图_20220212004845](https://user-images.githubusercontent.com/97740841/153708929-98c71b4c-14b6-420d-b552-2965476d8fb8.png)

**Comment by haoziqaq** [comment]
可以提供一下chorme的版本号和操作系统的版本么，在我的本地获取不到这么高精度的bottom，目前不知道是什么原因，虽然有解决办法，把bottom向下取整就可以，但是还是想了解具体的产生原因

**Comment by illisac** [comment]
PC:  
```code
Chrome/98.0.4758.82
```
Android:  
```code
Android Version: 11 API30
WebView Version: 87.0.4280.141(428014133)
```

**Comment by haoziqaq** [comment]
你滚动到740.xxx的时候，无法再向下滚动了是么？

**Comment by illisac** [comment]
对的,  无法滚动

**Comment by haoziqaq** [comment]
理论上在文档最底部高度为0的元素不应该获取到bottom溢出0.x个像素。我先向下取整处理，会在代码中关联这个issue，感谢反馈

**Comment by illisac** [comment]
嗯  刚刚参考了vant，它的默认offset不是0，置0后也有这个问题。

最后，感谢大佬的开源贡献😎

**Comment by haoziqaq** [comment]
应该的应该的，这个issue我先关掉啦～
