### ISSUE TITLE
暗黑模式下的海拔效果

### ISSUE THREAD

**Issue by RuinousCheng** [varletjs/varlet#312]
# About `styles` 🛠️
切换到暗黑模式后，海拔的效果就完全看不出来了。

**Comment by haoziqaq** [comment]
暗黑模式下提现层级是靠颜色深度的，海拔跟暗黑的设计实际是冲突的，你可以就当他不存在



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 晚上8:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 暗黑模式下的海拔效果 (Issue #312)




 
About styles 🛠️
 
切换到暗黑模式后，海拔的效果就完全看不出来了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
