### ISSUE TITLE
如何使用style-provider组件定义全局ripple颜色

### ISSUE THREAD

**Issue by estoi** [varletjs/varlet#318]
# About `styles` 🛠️
我想要定义全局的ripple color，在使用style-provider组件传入样式时候遇到问题：找不到ripple的样式变量，文档上只有一个贝塞尔的样式
![image](https://user-images.githubusercontent.com/44252820/154874046-a4bd3564-3ce8-49bd-b37d-0ddd9af75e01.png)

**Comment by haoziqaq** [comment]
下个版本加个变量进去～

**Comment by haoziqaq** [comment]
已经修复了，在下个小版本会发布，注意版本更新
