### ISSUE TITLE
space组件里面使用v-for渲染就失效了

### ISSUE THREAD

**Issue by ChenErik** [varletjs/varlet#319]
# Bug report 🐞
space组件里面使用v-for渲染没有产生间距
## Version & Environment
v1.26.1
## Expectation
预期v-for的每个元素出现间距
## Actual results (or Errors)
没有出现间距

[varlet ui playground demo ](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItc3BhY2UgZGlyZWN0aW9uPVwiY29sdW1uXCI+XG4gICAgPHZhci1idXR0b24gdi1mb3I9XCJpIGluIDZcIiA6a2V5PVwiaVwiIHR5cGU9XCJwcmltYXJ5XCI+5oyJ6ZKue3sgaSB9fTwvdmFyLWJ1dHRvbj5cbiAgPC92YXItc3BhY2U+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)

**Comment by qytayh** [comment]
感谢反馈，这个问题将在下个小版本中修复，请注意查看

**Comment by qytayh** [comment]
> # Bug report 🐞
> space组件里面使用v-for渲染没有产生间距
> 
> ## Version & Environment
> v1.26.1
> 
> ## Expectation
> 预期v-for的每个元素出现间距
> 
> ## Actual results (or Errors)
> 没有出现间距
> 
> [varlet ui playground demo ](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItc3BhY2UgZGlyZWN0aW9uPVwiY29sdW1uXCI+XG4gICAgPHZhci1idXR0b24gdi1mb3I9XCJpIGluIDZcIiA6a2V5PVwiaVwiIHR5cGU9XCJwcmltYXJ5XCI+5oyJ6ZKue3sgaSB9fTwvdmFyLWJ1dHRvbj5cbiAgPC92YXItc3BhY2U+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)

感谢反馈，这个问题将在下个小版本中修复，请注意查看

**Comment by ChenErik** [comment]
谢谢啦，我尝试修复了一下，没做到，好好学习大佬怎么改的😬

**Comment by ChenErik** [comment]
谢谢啦，我尝试修复了一下，没做到，好好学习大佬怎么改的😬

**Comment by haoziqaq** [comment]
感谢反馈， issue先关掉了

**Comment by ChenErik** [comment]
修复以后看上去展示效果好了，可是打开控制台发现出现几个空的带margin样式的div，导致出现不需要的间距
感觉可以加上
```vue
import { Comment } from 'vue'
if(vNode.type!==Comment){
   result.push(vNode)
}
````

**Comment by haoziqaq** [comment]
好的，在修复了

**Comment by qytayh** [comment]
已修复，感谢反馈，请留意版本更新
