### ISSUE TITLE
pull-refresh和list组件一起使用回不停触发list组件的load事件

### ISSUE THREAD

**Issue by estoi** [varletjs/varlet#324]
# Bug report 🐞

## Version & Environment
```bash
"@varlet/ui": "^1.26.2";
"vue": "^3.2.25",
"node": "v16.0.0";

```
## Expectation
上拉加载正常
## Actual results (or Errors)
上拉加载循环触发

**Comment by haoziqaq** [comment]
可以在 https://varlet.gitee.io/varlet-ui-playground/ 提供一个可以复现的demo么

**Comment by haoziqaq** [comment]
可以参考一下这个demo的做法
