### ISSUE TITLE
ImagePreview组件能否增加保存图片功能

### ISSUE THREAD

**Issue by estoi** [varletjs/varlet#326]
ImagePreview组件预览图片的时候能否增加一个保存图片到本地的功能？

**Comment by haoziqaq** [comment]
手机浏览器存在默认行为，长按就可以保存图片。Varlet的当前版本在ios上长按保存会自动关闭预览组件，体验不是很好，会在下个小版本修复

**Comment by estoi** [comment]
> 手机浏览器存在默认行为，长按就可以保存图片。Varlet的当前版本在ios上长按保存会自动关闭预览组件，体验不是很好，会在下个小版本修复

我目前是混合开发打包成APP的 长按没法保存图片

**Comment by haoziqaq** [comment]
webview的话长按保存就需要自己实现了，涉及到原生和web的通信，最好是预览组件都调起原生的，体验会更好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [varletjs/varlet] ImagePreview组件能否增加保存图片功能 (Issue #326)




  
手机浏览器存在默认行为，长按就可以保存图片。Varlet的当前版本在ios上长按保存会自动关闭预览组件，体验不是很好，会在下个小版本修复
  
我目前是混合开发打包成APP的 长按没法保存图片
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by estoi** [comment]
> 

就是预览图片的时候能否配置一些extra内容的选项，比如我可以额外配置一个按钮  然后再我自己实现下载功能

**Comment by haoziqaq** [comment]
嗯 好的

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [varletjs/varlet] ImagePreview组件能否增加保存图片功能 (Issue #326)




   
就是预览图片的时候能否配置一些extra内容的选项，比如我可以额外配置一个按钮  然后再我自己实现下载功能
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by estoi** [comment]
Hi!,目前有什么进展吗

**Comment by haoziqaq** [comment]
她已经做好了，估计这两天就能发布

**Comment by haoziqaq** [comment]
发布了

**Comment by estoi** [comment]
> 发布了

支持函数式调用配置extra吗

**Comment by haoziqaq** [comment]
只支持声明式插槽，暂时不在函数式调用中支持自定义render函数
