### ISSUE TITLE
Image组件配置lazy导致程序卡死

### ISSUE THREAD

**Issue by estoi** [varletjs/varlet#327]
# Bug report 🐞
依旧是capacitor+vue3项目， 我使用了瀑布流+list组件，子节点带有image组件并且配置了lazy，会导致程序卡死
## Version & Environment
`"@varlet/ui": "^1.26.2",`
`"vue": "^3.2.25",`
`"@capacitor/core": "^3.3.4",`
`"vite": "^2.7.2"`
## Expectation
懒加载功能正常
## Actual results (or Errors)
程序卡死

**Comment by haoziqaq** [comment]
https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYsIHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG5cbmNvbnN0IGxvYWRpbmcgPSByZWYoZmFsc2UpXG5jb25zdCBmaW5pc2hlZCA9IHJlZihmYWxzZSlcbmNvbnN0IGxpc3QgPSByZWFjdGl2ZShbXSlcbiAgICBcbmNvbnN0IGxvYWQgPSAoKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGZvciAobGV0IGkgPSAwOyBpIDwgMjA7IGkrKykge1xuICAgICAgICBsaXN0LnB1c2gobGlzdC5sZW5ndGggKyAxKVxuICAgIH1cblxuICAgIGxvYWRpbmcudmFsdWUgPSBmYWxzZVxuXG4gICAgaWYgKGxpc3QubGVuZ3RoID49IDYwKSB7XG4gICAgICAgZmluaXNoZWQudmFsdWUgPSB0cnVlXG4gICAgIH1cbiAgIH0sIDEwMDApXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLWxpc3RcbiAgICA6ZmluaXNoZWQ9XCJmaW5pc2hlZFwiXG4gICAgdi1tb2RlbDpsb2FkaW5nPVwibG9hZGluZ1wiXG4gICAgQGxvYWQ9XCJsb2FkXCJcbiAgID5cbiAgICA8dmFyLWltYWdlIFxuICAgICAgdi1mb3I9XCJpdGVtIGluIGxpc3RcIiBcbiAgICAgIDprZXk9XCJpdGVtXCIgXG4gICAgICBsYXp5IFxuICAgICAgc3JjPVwiaHR0cHM6Ly92YXJsZXQuZ2l0ZWUuaW8vdmFybGV0LXVpL2NhdC5qcGdcIiBcbiAgICAvPlxuICA8L3Zhci1saXN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=

**Comment by haoziqaq** [comment]
我没能复现这个问题， 你可以提供一个在线demo

**Comment by estoi** [comment]
> 我没能复现这个问题， 你可以提供一个在线demo

不知是否是图片太大 的问题 ，我把图片压缩了一下 目前没有卡死了

**Comment by haoziqaq** [comment]
有可能的，列表的组件虽然配置了懒加载但是还是应该使用缩略图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月8日(周二) 下午3:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] Image组件配置lazy导致程序卡死 (Issue #327)




  
我没能复现这个问题， 你可以提供一个在线demo
  
不知是否是图片太大 的问题 ，我把图片压缩了一下 目前没有卡死了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
