### ISSUE TITLE
GitHub经常被墙，可否在国内的码云也上一套？

### ISSUE THREAD

**Issue by z8985561** [varletjs/varlet#330]
# About `docs`
## 国内GitHub经常会上不到，对于那些不会科学上网的开发者不太友好，建议在国内的码云也上一下

**Comment by haoziqaq** [comment]
这方面我做了同步脚本，会在gitee上同步github仓库的代码，我们的文档站点也部署在gitee上。

https://gitee.com/varlet/varlet-ui

不过还是推荐在github上进行贡献和交流
