### ISSUE TITLE
@BeADre  约个饭啊？

### ISSUE THREAD

**Issue by AnDaLinShui** [varletjs/varlet#332]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

### Programme:
@BeADre  大佬约个饭啊？

**Comment by haoziqaq** [comment]
看来是耗某不配吃这个饭了

**Comment by wangKBweb** [comment]
我们这边是正经组件库哦亲 一般情况不约饭的

**Comment by haoziqaq** [comment]
除非请我们一起吃

**Comment by BeADre** [comment]
哈哈哈 非常荣幸 约饭当然可以 顺便要是对组件库感兴趣 可以留下邮箱 进群一起讨论

**Comment by haoziqaq** [comment]
这回复很不Varlet
