### ISSUE TITLE
部分控件的优化建议（由gitee转过来的）

### ISSUE THREAD

**Issue by az6161311** [varletjs/varlet#334]
日期控件无法左右滑动的吗？移动端滑动会更友好一些。
![输入图片说明](https://images.gitee.com/uploads/images/2022/0311/140949_5034503d_888330.png "屏幕截图.png")

IndexBar 索引栏
使用微信打开时，无法点击右边的abc..定位位置。另外应该可以在“abc..”点选/滑动的时候中间显示对应的字符，手机端太右边的快捷太小了误操作太多~

---------------------------------
以上为个人建议，如有不适，请忽略。

**Comment by BeADre** [comment]
> 另外应该可以在“abc..”点选/滑动的时候中间显示对应的字符
你的意思是在屏幕中央闪现一下当前对应的字符？

**Comment by az6161311** [comment]
> > 另外应该可以在“abc..”点选/滑动的时候中间显示对应的字符
> 
> 你的意思是在屏幕中央闪现一下当前对应的字符？

https://user-images.githubusercontent.com/9971676/158000561-1169fe68-d02d-428b-9a47-0dbf06ca1411.mp4

这样是否会顺畅一些呢？

**Comment by BeADre** [comment]
这个提示效果是可以通过`change`事件实现的

**Comment by BeADre** [comment]
https://user-images.githubusercontent.com/34639100/158005396-9a894e78-0706-4ef6-b442-b048b037dea1.mp4

我在微信浏览器下没能复现你的问题

**Comment by BeADre** [comment]
`date-picker` 已支持滑动, 发版本后即可用

**Comment by haoziqaq** [comment]
已发布

**Comment by az6161311** [comment]
谢谢~
