### ISSUE TITLE
var-tabs导致var-back-top的fixed失效

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#345]
# Bug report 🐞
我看到var-tabs里面的没有var-swipe-item都有style="width: 360px; transform: translateX(0px);" transform会导致position: fixed;失效,造成var-back-top的fab不能固定在可滚动的页面上
## Try
我尝试这样设置，问题得到解决，也没有引起其他的负面作用
.var-swipe-item {
	overflow: auto;
	transform: none !important;
}

这里不是很理解配置transform: translateX(0px);的作用

**Comment by haoziqaq** [comment]
tabsItems 内部调用了 <var-swipe/> 这里的 transform 是用来使用无缝循环轮播的。你提到的 back-top 固定失效问题我先尝试复现一下试试，如果你有可复现的 [在线playground](https://varlet.gitee.io/varlet-ui-playground/) 也可以提供给我

**Comment by haoziqaq** [comment]
https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgYWN0aXZlID0gcmVmKDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLXRhYnNcbiAgZWxldmF0aW9uXG4gIGNvbG9yPVwiIzI5NzlmZlwiXG4gIGFjdGl2ZS1jb2xvcj1cIiNmZmZcIlxuICBpbmFjdGl2ZS1jb2xvcj1cImhzbGEoMCwgMCUsIDEwMCUsIC42KVwiXG4gIHYtbW9kZWw6YWN0aXZlPVwiYWN0aXZlXCJcbj5cbiAgPHZhci10YWI+6YCJ6aG5MTwvdmFyLXRhYj5cbiAgPHZhci10YWI+6YCJ6aG5MjwvdmFyLXRhYj5cbjwvdmFyLXRhYnM+XG5cbjx2YXItdGFicy1pdGVtcyB2LW1vZGVsOmFjdGl2ZT1cImFjdGl2ZVwiPlxuICA8dmFyLXRhYi1pdGVtPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICA8L3Zhci10YWItaXRlbT5cbiAgPHZhci10YWItaXRlbT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT5cbiAgICA8aDE+aGVsbG88L2gxPlxuICAgIDxoMT5oZWxsbzwvaDE+XG4gICAgPGgxPmhlbGxvPC9oMT4gICAgXG4gIDwvdmFyLXRhYi1pdGVtPlxuPC92YXItdGFicy1pdGVtcz5cbiAgXG48dmFyLWJhY2stdG9wLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpXCI6IFwiLi92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3RvdWNoLWVtdWxhdG9yXCI6IFwiLi92YXJsZXQtdG91Y2gtZW11bGF0b3IuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoVmFybGV0VUkpXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBhcHBlbmRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnLi92YXJsZXQuY3NzJ1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn1cbiJ9

**Comment by haoziqaq** [comment]
上面这个例子中，我没能复现这个问题，可以帮忙复现一下么？

**Comment by little-alei** [comment]
> tabsItems 内部调用了 这里的 transform 是用来使用无缝循环轮播的。你提到的 back-top 固定失效问题我先尝试复现一下试试，如果你有可复现的 [在线playground](https://varlet.gitee.io/varlet-ui-playground/) 也可以提供给我

我提交了一份代码，您能看到嘛

**Comment by haoziqaq** [comment]
提交到哪里的，如果是在playground编辑的，需要把你的url分享到这里来，那个是通过url解析文件内容的

**Comment by little-alei** [comment]
Varlet UI Playground (gitee.io)&nbsp;里面的unfixed.vue
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "varletjs/varlet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [varletjs/varlet] var-tabs导致var-back-top的fixed失效 (Issue #345)





 
提交到哪里的，如果是在playground编辑的，需要把你的url分享到这里来，那个是通过url解析文件内容的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by little-alei** [comment]
[这个链接](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBWYXJsZXQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+e3sgbXNnIH19PC92YXItYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIiwidW5maXhlZC52dWUiOiI8dGVtcGxhdGU+XG5cdDxkaXYgY2xhc3M9XCJ0cmFuc2Zvcm1cIj5cblx0XHQ8dmFyLWNlbGwgdi1mb3I9XCJsaXN0IGluIGxpc3RzXCIgOmtleT1cImxpc3RcIj5TY3JvbGwgdG8gYm90dG9tIHt7IGxpc3QgfX08L3Zhci1jZWxsPlxuXHRcdDx2YXItYmFjay10b3AgOmR1cmF0aW9uPVwiMzAwXCIgLz5cblx0PC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0PlxuY29uc3QgbGlzdHMgPSBbLi4uQXJyYXkoNTApLmtleXMoKV07XG5leHBvcnQgZGVmYXVsdCB7XG5cdHNldHVwKCkge1xuXHRcdHJldHVybiB7XG5cdFx0XHRsaXN0cyxcblx0XHR9O1xuXHR9LFxufTtcbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi50cmFuc2Zvcm0ge1xuXHR0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoMHB4KTtcbn1cbjwvc3R5bGU+In0=)
里面的unfixed.vue文件

**Comment by little-alei** [comment]
> 提交到哪里的，如果是在playground编辑的，需要把你的url分享到这里来，那个是通过url解析文件内容的

[代码上传在这里](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcbmluc3RhbGxWYXJsZXRVSSgpXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFZhcmxldCEnKVxuY29uc3QgYWN0aXZlID0gcmVmKDApO1xuY29uc3QgbGlzdHMgPSBbLi4uQXJyYXkoNTApLmtleXMoKV07XG48L3NjcmlwdD5cbjx0ZW1wbGF0ZT5cbiAgPHZhci10YWJzIHN0aWNreSB2LW1vZGVsOmFjdGl2ZT1cImFjdGl2ZVwiPlxuXHRcdDx2YXItdGFiPummlumhtTwvdmFyLXRhYj5cblx0XHQ8dmFyLXRhYj7npLrkvos8L3Zhci10YWI+XG5cdDwvdmFyLXRhYnM+XG4gIDx2YXItdGFicy1pdGVtcyB2LW1vZGVsOmFjdGl2ZT1cImFjdGl2ZVwiPlxuICAgICAgPHZhci10YWItaXRlbT5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICA8dmFyLWNlbGwgdi1mb3I9XCJsaXN0IGluIGxpc3RzXCIgOmtleT1cImxpc3RcIj5TY3JvbGwgdG8gYm90dG9tIHt7IGxpc3QgfX08L3Zhci1jZWxsPlxuICAgICAgICAgIDx2YXItYmFjay10b3AgOmR1cmF0aW9uPVwiMzAwXCIgLz5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3Zhci10YWItaXRlbT5cbiAgICAgIDx2YXItdGFiLWl0ZW0+XG4gICAgICAgIDxoNj57e21zZ319PC9oNj5cbiAgICAgIDwvdmFyLXRhYi1pdGVtPlxuXHQ8L3Zhci10YWJzLWl0ZW1zPlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbi52YXItc3dpcGUtaXRlbSB7XG5cdG92ZXJmbG93OiBhdXRvO1xuXHR0cmFuc2Zvcm06IG5vbmUgIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpXCI6IFwiLi92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3RvdWNoLWVtdWxhdG9yXCI6IFwiLi92YXJsZXQtdG91Y2gtZW11bGF0b3IuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoVmFybGV0VUkpXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBhcHBlbmRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnLi92YXJsZXQuY3NzJ1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn1cbiIsInVuZml4ZWQudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2IGNsYXNzPVwidHJhbnNmb3JtXCI+XG5cdFx0PHZhci1jZWxsIHYtZm9yPVwibGlzdCBpbiBsaXN0c1wiIDprZXk9XCJsaXN0XCI+U2Nyb2xsIHRvIGJvdHRvbSB7eyBsaXN0IH19PC92YXItY2VsbD5cblx0XHQ8dmFyLWJhY2stdG9wIDpkdXJhdGlvbj1cIjMwMFwiIC8+XG5cdDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdD5cbmNvbnN0IGxpc3RzID0gWy4uLkFycmF5KDUwKS5rZXlzKCldO1xuZXhwb3J0IGRlZmF1bHQge1xuXHRzZXR1cCgpIHtcblx0XHRyZXR1cm4ge1xuXHRcdFx0bGlzdHMsXG5cdFx0fTtcblx0fSxcbn07XG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4udHJhbnNmb3JtIHtcblx0dHJhbnNmb3JtOiB0cmFuc2xhdGVYKDBweCk7XG59XG48L3N0eWxlPiJ9)

**Comment by haoziqaq** [comment]
产生原因明确了。

不过我个人认为开发者应该主动绕开这种使用方式。

**因为回到顶部的功能是相对滚动容器的，应该只在滚动容器中使用，而不应该分别在不同的 tab 中创建回到顶部的功能(除非不同的 tab 中也开启了不同的局部滚动)。就算是在 tabs 组件中特殊处理了这种使用方式，也无法避免开发者在其他场景下无意中和带有 transform 的容器进行和组合使用**。

我个人倾向在 back-top 文档中做一个小tip，提醒开发者注意这样的边缘使用情况

**Comment by haoziqaq** [comment]
或者考虑把back top传送到body中，这个我跟这个组件的作者进行一下沟通，还是先感谢你的反馈

**Comment by little-alei** [comment]
> 或者考虑把back top传送到body中，这个我跟这个组件的作者进行一下沟通，还是先感谢你的反馈

我一开始尝试传送到body里了，但是记上target参数后，试了好几次滑动也没能触发back top出现，可能是我参数没写对，目前是通过
.var-swipe-item {
	overflow: auto;
	transform: none !important;
}
解决的。
感谢提供ui组件库，很不错的体验

**Comment by little-alei** [comment]
> 或者考虑把back top传送到body中，这个我跟这个组件的作者进行一下沟通，还是先感谢你的反馈

使用中发现缺少安卓的类似Bottom App Bar的组件，其他的感觉很全面

**Comment by haoziqaq** [comment]
确实很多人跟我们提了需要一个底部导航栏，尤其是对底部导航栏中间部分的悬浮fab很感兴趣，我们把手上的任务完成之后，然后做一个这样的组件吧

**Comment by little-alei** [comment]
![image](https://user-images.githubusercontent.com/59299759/159171202-56acc1c0-2d6a-41ea-ad45-56b60e64a55a.png)
我也在尝试，不过做的好丑，还没做好。等正式提供了，我也第一时间用上。感谢开发varlet-ui

**Comment by haoziqaq** [comment]
嗯 好的

**Comment by BeADre** [comment]
现在`back-top`默认会被`teleport`到body中

**Comment by haoziqaq** [comment]
1.27.0发布了，新增了底部导航栏，可以体验一下，及时反馈

**Comment by haoziqaq** [comment]
@little-alei

**Comment by little-alei** [comment]
> @little-alei

3Q，我尝试一下，感谢
