### ISSUE TITLE
var-select位置错误

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#350]
# Bug report 🐞
在页面底部使用var-select时,依然向下弹出,导致页面被拉伸，建议增来类似alignment="bottom"属性来调整它的top: calc(...px);或者调整transform: translateY(-100%);
![image](https://user-images.githubusercontent.com/59299759/159232379-0b6be67f-a071-49f0-bf35-245ba92eb914.png)

**Comment by haoziqaq** [comment]
可以增加类似菜单偏移量的属性，但是你这里的场景 可能用picker会更好，在手机场景下还是比较推荐使用picker的，select主要是满足桌面端或者平板的一些使用需求。

**Comment by little-alei** [comment]
> 可以增加类似菜单偏移量的属性，但是你这里的场景 可能用picker会更好，在手机场景下还是比较推荐使用picker的，select主要是满足桌面端或者平板的一些使用需求。

好的谢谢

**Comment by mnmnun** [comment]
> 可以增加类似菜单偏移量的属性，但是你这里的场景 可能用picker会更好，在手机场景下还是比较推荐使用picker的，select主要是满足桌面端或者平板的一些使用需求。

选择多个选项时，还是用select好点，如果用偏移量属性的话，有时候并不知道有几个选项具体要偏移多少px，或者这次调好了偏移量，下次加多一个选项又要重新调整偏移量！！
