### ISSUE TITLE
Tabs Events建议增加滑动回调

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#352]
# Feature request 🚀
建议Tabs Events增加一个回调的方法，可以在can-swipe为true时，暴露当前滑动完成的百分比。这样用户可以根据这个值做一些动画效果或者其他的用途

**Comment by haoziqaq** [comment]
相当于在轮播拖拽时另外做一些事情，这个场景目前看来还是比较小的，我们会考虑一下，但是优先级暂时不会太高。
