### ISSUE TITLE
基于vm布局，设计稿宽度为750或者1042的兼容问题

### ISSUE THREAD

**Issue by zhuchongyue** [varletjs/varlet#354]
# About `styles` 🛠️

当业务的设计稿是750（国内常用）或者其他非375尺寸的时候

这个时候基于vm布局，使用postcss-px-to-viewport插件配置viewportWidth=750，这样肯定会显得varlet组件视觉上缩小50%。

目前我是简单先重定义一下var改为2倍，还有一些间距问题。

请问，官方团队有什么好的解决方案？

**Comment by haoziqaq** [comment]
在插件内配置 var开头的class应用375 其余应用750



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(周五) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 基于vm布局，设计稿宽度为750或者1042的兼容问题 (Issue #354)




 
About styles 🛠️
 
当业务的设计稿是750（国内常用）或者其他非375尺寸的时候
 
这个时候基于vm布局，使用postcss-px-to-viewport插件配置viewportWidth=750，这样肯定会显得varlet组件视觉上缩小50%。
 
目前我是简单先重定义一下var改为2倍，还有一些间距问题。
 
请问，官方团队有什么好的解决方案？
