### ISSUE TITLE
黑暗模式切换成正常模式

### ISSUE THREAD

**Issue by cll123456** [varletjs/varlet#357]
# Bug report 🐞
>在组件库中，提供了黑暗模式是更改root上的变量。是ok的。

![image](https://user-images.githubusercontent.com/41314419/161221474-7ffb0a3a-1ae1-48ae-8611-e5be203014cd.png)

但是style中的index.js 是不是该定义对呀正常模式的css变量，方便切换回来？目前style中的index.js是空的。或者说怎么切换回来？

如果说考虑到用户自定义了样式，那是不是也应该提供一个基础的css变量文件，让用户去继承修改？
## Version & Environment 
`"@varlet/ui": "^1.26.8",`

**Comment by haoziqaq** [comment]
StyleProvider(null)就可以切换回默认主题，目前的设计是一套默认主题+N套自定义主题的模式

用户如果需要自定义默认的样式，可以直接通过css在:root上直接修改

**Comment by cll123456** [comment]
@haoziqaq 好的，谢谢
