### ISSUE TITLE
更改input的v-model值不会触发验证?

### ISSUE THREAD

**Issue by 473833864** [varletjs/varlet#360]
# Bug report 🐞

**Comment by 473833864** [comment]
"@varlet/ui": "^1.26.8"

## Expectation

验证的规则不是根据v-model值改变触发的吗?发现根本不触发,就算手动调用validate() 里面的值居然也是空

**Comment by qytayh** [comment]
我先尝试复现一下你这边的问题。

如果你有可复现的 [在线playground](https://varlet.gitee.io/varlet-ui-playground/) 也可以提供给我们。

**Comment by 473833864** [comment]
<script setup lang='ts'>
import { ref,onMounted,getCurrentInstance  } from 'vue'
import { installVarletUI } from './varlet-repl-plugin.js'

installVarletUI()
const internalInstance = getCurrentInstance()
const msg = ref('')


onMounted(()=>{
  
  internalInstance.refs.fieldRef.validate()
	setTimeout(()=>{
    msg.value = '21414'
  },3000)
})
</script>

<template>
  <var-input ref="fieldRef" :rules="[v => !!v || '用户名不能为空']"  placeholder="请输入内容" v-model="msg" />
</template>

感觉是必须要手输才能触发并且改变验证里面的值

**Comment by 473833864** [comment]
`<script setup lang='ts'>
import { ref,getCurrentInstance,onMounted  } from 'vue'
import { installVarletUI } from './varlet-repl-plugin.js'
const internalInstance = getCurrentInstance()
installVarletUI()

const msg = ref('')
onMounted(()=>{
  internalInstance.refs.field.validate()
  setTimeout(()=>{
    msg.value = 'aaaaa'
  },3000)
})
</script>

<template>
  <var-input ref="field" :rules="[v => !!v || '用户名不能为空']" placeholder="请输入" v-model="msg"  />
</template>`
感觉必须是手输才会触发验证

**Comment by 473833864** [comment]
![image](https://user-images.githubusercontent.com/51225790/161373235-bb760796-35b4-4adf-b2de-44670e5d7d40.png)

**Comment by qytayh** [comment]
你可以直接点击右上角的分享，然后将链接粘贴在这边的

**Comment by 473833864** [comment]
[https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYsZ2V0Q3VycmVudEluc3RhbmNlLG9uTW91bnRlZCAgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcbmNvbnN0IGludGVybmFsSW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgbXNnID0gcmVmKCcnKVxub25Nb3VudGVkKCgpPT57XG4gIGludGVybmFsSW5zdGFuY2UucmVmcy5maWVsZC52YWxpZGF0ZSgpXG4gIHNldFRpbWVvdXQoKCk9PntcbiAgICBtc2cudmFsdWUgPSAnYWFhYWEnXG4gIH0sMzAwMClcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLWlucHV0IHJlZj1cImZpZWxkXCIgOnJ1bGVzPVwiW3YgPT4gISF2IHx8ICfnlKjmiLflkI3kuI3og73kuLrnqbonXVwiIHBsYWNlaG9sZGVyPVwi6K+36L6T5YWlXCIgdi1tb2RlbD1cIm1zZ1wiICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=](url)

**Comment by qytayh** [comment]
可以在赋值后重新调一次 `validate`  [参考这样](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYsIG5leHRUaWNrLCBvbk1vdW50ZWQgIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG5cbmNvbnN0IG1zZyA9IHJlZignJylcbmNvbnN0IGZpZWxkID0gcmVmKClcblxub25Nb3VudGVkKCgpPT57XG4gIGZpZWxkLnZhbHVlLnZhbGlkYXRlKClcbiAgXG4gIHNldFRpbWVvdXQoYXN5bmMgKCk9PntcbiAgICBtc2cudmFsdWUgPSAnYWFhYWEnXG4gICAgXG4gICAgYXdhaXQgbmV4dFRpY2soKVxuICAgIGZpZWxkLnZhbHVlLnJlc2V0VmFsaWRhdGlvbigpXG4gICAgZmllbGQudmFsdWUudmFsaWRhdGUoKVxuICB9LCAzMDAwKVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItaW5wdXQgcmVmPVwiZmllbGRcIiA6cnVsZXM9XCJbdiA9PiAhIXYgfHwgJ+eUqOaIt+WQjeS4jeiDveS4uuepuiddXCIgcGxhY2Vob2xkZXI9XCLor7fovpPlhaVcIiB2LW1vZGVsPVwibXNnXCIgIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)
