### ISSUE TITLE
imagePreview组件close按钮位置无法配置

### ISSUE THREAD

**Issue by estoi** [varletjs/varlet#414]
# Feature request 🚀
希望能够增加配置close按钮的显示位置，因为我目前的混合开发项目中close显示在右上角，当配置了沉浸式状态栏的时候，close按钮与状态栏重叠了。
当我使用slot配置自定义关闭按钮的时候无法生效

[Demo](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGltYWdlcyA9IHJlZihbXG4gICAgICAnaHR0cHM6Ly92YXJsZXQuZ2l0ZWUuaW8vdmFybGV0LXVpL2NhdC5qcGcnLFxuICAgICAgJ2h0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQyLmpwZycsXG4gICAgXSlcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ2aXNpYmxlID0gdHJ1ZVwiPumihOiniDwvdmFyLWJ1dHRvbj5cbiAgPHZhci1pbWFnZS1wcmV2aWV3XG4gICAgY3VycmVudD1cImh0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQyLmpwZ1wiXG4gICAgOmltYWdlcz1cImltYWdlc1wiXG4gICAgdi1tb2RlbDpzaG93PVwidmlzaWJsZVwiXG4gID5cbiAgICA8c2xvdCBuYW1lPVwiY2xvc2UtaWNvblwiPlxuICAgICAgPHA+XG4gICAgICAgIGNsb3NlXG4gICAgICA8L3A+XG4gICAgPC9zbG90PlxuICA8L3Zhci1pbWFnZS1wcmV2aWV3PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=)

**Comment by haoziqaq** [comment]
https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGltYWdlcyA9IHJlZihbXG4gICAgICAnaHR0cHM6Ly92YXJsZXQuZ2l0ZWUuaW8vdmFybGV0LXVpL2NhdC5qcGcnLFxuICAgICAgJ2h0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQyLmpwZycsXG4gICAgXSlcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ2aXNpYmxlID0gdHJ1ZVwiPumihOiniDwvdmFyLWJ1dHRvbj5cbiAgPHZhci1pbWFnZS1wcmV2aWV3XG4gICAgY3VycmVudD1cImh0dHBzOi8vdmFybGV0LmdpdGVlLmlvL3ZhcmxldC11aS9jYXQyLmpwZ1wiXG4gICAgOmltYWdlcz1cImltYWdlc1wiXG4gICAgdi1tb2RlbDpzaG93PVwidmlzaWJsZVwiXG4gID5cbiAgICA8dGVtcGxhdGUgI2Nsb3NlLWljb24+XG4gICAgICA8cCBzdHlsZT1cInBvc2l0aW9uOiBhYnNvbHV0ZTsgcGFkZGluZzogMTAwcHg7IGJhY2tncm91bmQ6ICNmZmY7IHRvcDogMTAwcHg7IGxlZnQ6IDEwMHB4O1wiIEBjbGljaz1cInZpc2libGUgPSBmYWxzZVwiPlxuICAgICAgICBjbG9zZVxuICAgICAgPC9wPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvdmFyLWltYWdlLXByZXZpZXc+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==
