### ISSUE TITLE
组件库样式设计问题

### ISSUE THREAD

**Issue by mark3h** [varletjs/varlet#417]
# About `styles` 🛠️
有一个疑问：
varlet-ui库中，为什么不直接采用css var的方式进行样式的管理？
为什么要先设置less的变量，然后将less的变量设置到:root上，同理在组件中使用也是，先定义less的变量，并引用common.less中定义的基础css变量，然后再将less的变量赋予给每一个组件的css变量。

这样做的好处是？

**Comment by mark3h** [comment]
我理解使用css变量的方式是为了用户可以全局或局部替换，但是为什么要通过less再定义一层

**Comment by BeADre** [comment]
因为最之前我们是用less变量替换样式的 后来为了做运行时的主题替换 就加了css var, 但是并没有把less变量移除

**Comment by haoziqaq** [comment]
也就是说，你在编译时和运行时都可以进行主题定制

**Comment by mark3h** [comment]
懂了谢谢
