### ISSUE TITLE
官网上右侧预览不显示

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#418]
# Bug report 🐞
edge浏览器，右侧预览不加载，页面404。浏览器开发者工具切换成移动端ui能显示。在谷歌浏览器也能显示
![image](https://user-images.githubusercontent.com/59299759/162580373-725c03f2-6e09-44f0-a013-e58f5e92cd68.png)

**Comment by haoziqaq** [comment]
今天刚部署过文档，可能有24小时强缓存，清理下缓存

**Comment by haoziqaq** [comment]
刚刚部署过文档 清理一下缓存 gitee24小时强缓存



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月9日(周六) 晚上11:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 官网上右侧预览不显示 (Issue #418)




 
Bug report 🐞
 
edge浏览器，右侧预览不加载，页面404。浏览器开发者工具切换成移动端ui能显示。在谷歌浏览器也能显示
