### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#419]
# Bug report 🐞
当使用varlet组件后，使用自定义指令会导致编译不通过，测试不使用varlet时不存在这个问题
![image](https://user-images.githubusercontent.com/59299759/162606804-3b5eebd2-25d4-4fff-8e75-eecae5d9c56d.png)

**Comment by haoziqaq** [comment]
是否使用了`unplugin-vue-components`?

**Comment by little-alei** [comment]
> 是否使用了`unplugin-vue-components`?

是的，用了这个。这种情况需要怎么处理，能避免吗

**Comment by haoziqaq** [comment]
我去修改一下这个插件吧，只允许编译lazy和ripple，你可以先临时取消一下这个插件

**Comment by haoziqaq** [comment]
你先传入directives: false 把指令的编译关掉

**Comment by little-alei** [comment]
> 你先传入directives: false 把指令的编译关掉

OK，关掉可以编译了

**Comment by haoziqaq** [comment]
https://github.com/antfu/unplugin-vue-components/pull/352

release之后升级一下插件应该就可以了

**Comment by little-alei** [comment]
> [antfu/unplugin-vue-components#352](https://github.com/antfu/unplugin-vue-components/pull/352)
> 
> release之后升级一下插件应该就可以了

效率这么高，6呀老哥。提个建议，组件库后面是不是也可以提供手势组件。被包裹的组件可以响应比如长按、拖动的手势。毕竟是移动端组件库，有些手势比较常用

**Comment by haoziqaq** [comment]
这个主要是在手机浏览器上，常见的手势都被占用了，不同平台的行为也不一致，我们很难把体验做的很好

**Comment by haoziqaq** [comment]
ok了
