### ISSUE TITLE
varlet-cli里面的eslint-plugin-vue 版本低于8.0 

### ISSUE THREAD

**Issue by HZZformGD** [varletjs/varlet#429]
# Bug report 🐞
cli里面的eslint-plugin-vue比较低，导致在使用setup defineProps等时eslint一直报错
## Version & Environment
varlet-cli 1.27.2
## Expectation
更新eslint-plugin-vue 版本，正常使用setup语法

**Comment by haoziqaq** [comment]
我们的编译器没有支持使用`script setup`编写组件

**Comment by HZZformGD** [comment]
> 我们的编译器没有支持使用`script setup`编写组件

ok 了解。
