### ISSUE TITLE
Picker组件中列表添加子标题

### ISSUE THREAD

**Issue by fangkai2017** [varletjs/varlet#441]
# Feature request 🚀
可以为Picker组件中，滚动列表添加子标题特性吗？比如：年月日子标题
### Expected:
![image](https://user-images.githubusercontent.com/24379589/163681240-46c685c1-761a-4bdd-8f9b-041dc8e68874.png)

**Comment by haoziqaq** [comment]
看起来是个不错的想法，我们后续讨论讨论， 目前阶段在做script setup的文档迁移，可能还需要一点时间，非全职开源，希望能理解，哈哈

**Comment by fangkai2017** [comment]
> 看起来是个不错的想法，我们后续讨论讨论， 目前阶段在做script setup的文档迁移，可能还需要一点时间，非全职开源，希望能理解，哈哈

~期待~~
