### ISSUE TITLE
打包后组件的样式单独一个文件

### ISSUE THREAD

**Issue by HZZformGD** [varletjs/varlet#462]
# Bug report 🐞
感觉这不是bug，可能是varlet的设计如此， 打包后的文件并没有在代码里面import css。所以想问问，是否加个配置将style打包进当前组件的js里面 (ps:因为我有一个需求，想打包成webcomponent)
## Version & Environment
@varlet-cli 1.27.2

**Comment by haoziqaq** [comment]
不打包进js里是为了更好的按需引入，加配置的话，可能会排在比较后面的时间里了，暂时还是推荐单独导入对应组件的css

**Comment by HZZformGD** [comment]
> 不打包进js里是为了更好的按需引入，加配置的话，可能会排在比较后面的时间里了，暂时还是推荐单独导入对应组件的css

好的吧，自己摸索看看去了，webcomponent是比较麻烦点
