### ISSUE TITLE
varlet-cli如何配置tailwindcss?

### ISSUE THREAD

**Issue by 70hnXX** [varletjs/varlet#476]
# About `styles` 🛠️
我安装了兼容版本的tailwindcss后,启动项目能发现tailwindcss起作用了,但是刷新页面后样式就失效了

**Comment by haoziqaq** [comment]
`varlet-cli`适合的用户主要还是没有组件库开发经验的入门者，遵循`varlet`的开发模式进行开发，是可以覆盖绝大部分的需求的。如果需要更个性化定制或者需求的话，可能就不适合使用`varlet-cli`
