### ISSUE TITLE
轮播图图片不显示

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#507]
# Bug report 🐞
当打开对话框，对话框里面有Input 输入框，当在移动端设备上，输入框获取焦点弹出键盘后，有很大概率 Swipe 轮播 的图片不显示了。在电脑上不存在这个问题，电脑上打字不弹输入法

**Comment by little-alei** [comment]
测试了下是route多界面时，对话框和Swipe 轮播不在一个页面时存在这个问题。在同一个页面不会

**Comment by little-alei** [comment]
https://user-images.githubusercontent.com/59299759/164970088-401711dd-8465-4410-a952-d8e0fa1c5cc5.mp4

这是我复现的测试视频

**Comment by haoziqaq** [comment]
有没有用到keepalive

**Comment by little-alei** [comment]
> 有没有用到keepalive

是的，keep-alive包裹起来的

**Comment by haoziqaq** [comment]
如果用到了`keepalive`可能需要你在路由激活时调用一下`resize`方法，之前也有人遇到这个问题，后续我们考虑要不要在组件里注册`keepalive`的钩子去帮助开发者`resize`

**Comment by little-alei** [comment]
> 

好的，谢谢。我尝试了一下，发现调用resize方法后每次切换路由后，需要加个setTimeout，是可以解决问题的，需要燕赤霞调用，不加的话一直是空白😂

**Comment by haoziqaq** [comment]
应该是需要nexttick一次，因为keepalive也要一次渲染帧，其实我也不清楚到底是keepalive内部做了什么会把轮播的尺寸设置成0，后续我们考虑集成到组件里去修复这个坑吧
