### ISSUE TITLE
表单类控件的placeholder可以显示在组件的同一行吗？

### ISSUE THREAD

**Issue by languanghao** [varletjs/varlet#533]
# About `styles` 🛠️
input, select 之类的表单类控件的placeholder都是显示在组件的上一行的，能跟其他UI一样线是在同一行吗？

![image](https://user-images.githubusercontent.com/3765379/166874738-28a13667-b4f1-4afe-b3d3-09350e24a19c.png)

**Comment by haoziqaq** [comment]
这是设计风格决定的，不太好做改动，或者也可以使用 input 的 朴素模式自己组合
