### ISSUE TITLE
[datatable] any plan to create datatable component?

### ISSUE THREAD

**Issue by guolimin1995** [varletjs/varlet#565]
datatable component.

**Comment by haoziqaq** [comment]
No plan for now, we hope to focus on mobile side in the short term...
Out next component is floating button, the datetable maybe create later

**Comment by guolimin1995** [comment]
> No plan for now, we hope to focus on mobile side in the short term... Out next component is floating button, the datetable maybe create later

great. thanks for you doing with this project.
