### ISSUE TITLE
Varlet UI Playground

### ISSUE THREAD

**Issue by goldbergmoshe** [varletjs/varlet#580]
# Bug report 🐞
I have just tried to use the Ui Playground - I really like this library, however it is not working! Please fix!

## Actual results (or Errors)

The error I get is "Uncaught (in promise): Load failed"

**Comment by BeADre** [comment]
Please provide a reproduction demo

**Comment by goldbergmoshe** [comment]
There is no need for a demo since if you just open the playground you get this error. But here is a link to the playground

https://varlet.gitee.io/varlet-ui-playground/

**Comment by goldbergmoshe** [comment]
Hi,

Just managed to figure it out. This playground only gives this error when being used with Safari. However, in chrome this works. 
Think this is a Bug!

**Comment by haoziqaq** [comment]
Ok, bug fixed, thx~

**Comment by goldbergmoshe** [comment]
Nice! Thanks so much!
