### ISSUE TITLE
手势冲突

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#596]
# Bug report 🐞
pull-refresh的下拉组件里使用表格时，下拉动作与table表格组件的下拉冲突。导致下滑表格触发刷新

**Comment by BeADre** [comment]
Please provide a reproduction demo

**Comment by little-alei** [comment]
> Please provide a reproduction demo

[复现的代码](https://varlet-ui-playground.vercel.app/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjxzY3JpcHQ+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBnZW4gPSAoY3VycmVudCwgc2l6ZSkgPT4ge1xuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogc2l6ZSB9KS5tYXAoKF8sIGluZGV4KSA9PiB7XG4gICAgY29uc3QgaWQgPSAoY3VycmVudCAtIDEpICogc2l6ZSArIGluZGV4ICsgMVxuICAgIHJldHVybiB7XG4gICAgICBuYW1lOiBgTmFtZSAke2lkfWAsXG4gICAgICBtYXRoOiBpZCxcbiAgICAgIGVuZ2xpc2g6IGlkLFxuICAgIH1cbiAgfSlcbn1cbmNvbnN0IGlzUmVmcmVzaCA9IHJlZihmYWxzZSlcbmNvbnN0IGxpc3QgPSByZWYoZ2VuKDEsIDUwKSlcbmNvbnN0IGdldCA9IChjdXJyZW50LCBzaXplKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBnZW4oY3VycmVudCwgc2l6ZSlcbn1cbmNvbnN0IHJlZnJlc2ggPSAoKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGlzUmVmcmVzaC52YWx1ZSA9IGZhbHNlXG4gIH0sIDEwMDApXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLXB1bGwtcmVmcmVzaCB2LW1vZGVsPVwiaXNSZWZyZXNoXCIgQHJlZnJlc2g9XCJyZWZyZXNoXCI+XG4gICAgPHZhci10YWJsZSBjbGFzcz1cInRhYmxlXCI+XG4gICAgICA8dGhlYWQ+XG4gICAgICAgIDx0cj5cbiAgICAgICAgICA8dGg+5aeT5ZCNPC90aD5cbiAgICAgICAgICA8dGg+5pWw5a2mPC90aD5cbiAgICAgICAgICA8dGg+6Iux6K+tPC90aD5cbiAgICAgICAgPC90cj5cbiAgICAgIDwvdGhlYWQ+XG4gICAgICA8dGJvZHk+XG4gICAgICAgIDx0ciB2LWZvcj1cImwgaW4gbGlzdFwiIDprZXk9XCJsLm5hbWVcIj5cbiAgICAgICAgICA8dGQ+e3sgbC5uYW1lIH19PC90ZD5cbiAgICAgICAgICA8dGQ+e3sgbC5tYXRoIH19PC90ZD5cbiAgICAgICAgICA8dGQ+e3sgbC5lbmdsaXNoIH19PC90ZD5cbiAgICAgICAgPC90cj5cbiAgICAgIDwvdGJvZHk+XG4gICAgPC92YXItdGFibGU+XG4gIDwvdmFyLXB1bGwtcmVmcmVzaD5cbiAgPGRpdiBjbGFzcz1cImZvb3RcIj5cblx0XHRcdDx2YXItYnV0dG9uIHR5cGU9XCJpbmZvXCIgc3R5bGU9XCJ3aWR0aDogMzAlXCI+5oyJ6ZKu5LiAPC92YXItYnV0dG9uPlxuXHRcdFx0PHZhci1idXR0b24gdHlwZT1cImluZm9cIiBzdHlsZT1cIndpZHRoOiAzMCVcIj7mjInpkq7kuow8L3Zhci1idXR0b24+XG5cdFx0XHQ8dmFyLWJ1dHRvbiB0eXBlPVwiaW5mb1wiIHN0eWxlPVwid2lkdGg6IDMwJVwiPuaMiemSruS4iTwvdmFyLWJ1dHRvbj5cblx0XHQ8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4udGFibGUgOmRlZXAoLnZhci10YWJsZV9fbWFpbikge1xuXHRoZWlnaHQ6IGNhbGMoODV2aCk7XG59XG4uZm9vdCB7XG5cdHBhZGRpbmctdG9wOiAwLjVyZW07XG5cdGRpc3BsYXk6IGZsZXg7XG5cdGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2Vlbjtcbn1cbjwvc3R5bGU+PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcImh0dHBzOi8vdmFybGV0LXVpLXBsYXlncm91bmQudmVyY2VsLmFwcC92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3RvdWNoLWVtdWxhdG9yXCI6IFwiaHR0cHM6Ly92YXJsZXQtdWktcGxheWdyb3VuZC52ZXJjZWwuYXBwL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcImh0dHBzOi8vdmFybGV0LXVpLXBsYXlncm91bmQudmVyY2VsLmFwcC92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ZhcmxldC11aS1wbGF5Z3JvdW5kLnZlcmNlbC5hcHAvdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)
这这应该不是组件库的问题，因为我为了让表格下方固定按钮，用deep修改了表格的高度。

**Comment by BeADre** [comment]
因为你修改了表格的高度 导致下拉组件判断子元素是滚动到头了 所以出现了这个情况  或许你可以用一个设置了最大高度的容器来包裹下拉组件
