### ISSUE TITLE
In typescript, var-swipe-item have a type error

### ISSUE THREAD

**Issue by twohair** [varletjs/varlet#600]
# Bug report 🐞
![image](https://user-images.githubusercontent.com/71372667/172342328-b40e1bff-f112-4a3a-beef-de72f199fb48.png)
SwipeItem doesn't have '$props' member cause the following error
![image](https://user-images.githubusercontent.com/71372667/172342944-42091c62-4271-496b-8770-c54a868772db.png)
## Version & Environment
"@varlet/ui": "^1.27.11",
"vue": "^3.2.25"
"@vitejs/plugin-vue": "^2.3.3",
"typescript": "^4.5.4",
"vite": "^2.9.9",
"vue-tsc": "^0.34.7"

**Comment by haoziqaq** [comment]
原因是组件类型缺少了 `$props: {}` 的类型，晚些修复一下，如果你有兴趣，也可以帮我们修复一下

**Comment by twohair** [comment]
#602
