### ISSUE TITLE
组件相对位置浮动层如何配置 z-index的值？

### ISSUE THREAD

**Issue by shenyuanheli** [varletjs/varlet#607]
#引用组件：但是该组件
```
<back-top :duration="300" :right="30" />
<script>
export default {
  components: {
    BackTop,
  },
}
</script>
```
#配置不了z-index导致一直在最下层看不到按钮。望优化！！
![image](https://user-images.githubusercontent.com/70498139/174031572-37bbe28f-aaad-4377-9b01-89ef3535da7c.png)

**Comment by BeADre** [comment]
已修复，直接传css样式即可

**Comment by BeADre** [comment]
@shenyuanheli 已发版本 升级即可
