### ISSUE TITLE
Snackbar disappears suddenly during the leaving animation

### ISSUE THREAD

**Issue by cleoledev** [varletjs/varlet#610]
# Bug report 🐞
The snackbar disappears suddenly during the leaving animation when the trigger button is not on top of the page (needs scrolling down)

## Version & Environment
Nuxt 3 with @varlet/ui 1.27.11

## Expectation
Expect the fade-out animation will go smoothly when leaving

## Actual results (or Errors)
I've reproduced this situation through the [varlet playground](https://varlet-ui-playground.vercel.app/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcblxuY29uc3Qgc2hvdyA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwIGFsaWduPVwiY2VudGVyXCI+XG4gICAgXHRTY3JvbGwgRG93biBhbmQgQ2xpY2sgdGhlIGJ1dHRvblxuICA8L3A+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAzMDB2aFwiPlxuICAgIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgYmxvY2sgQGNsaWNrPVwic2hvdyA9ICFzaG93XCI+5Z+65pys5L2/55SoPC92YXItYnV0dG9uPlxuICBcdDx2YXItc25hY2tiYXIgdi1tb2RlbDpzaG93PVwic2hvd1wiPiDov5nmmK/kuIDkuKrmtojmga/mnaHvvIHvvIEgPC92YXItc25hY2tiYXI+XG4gIDwvZGl2PlxuICBcbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpXCI6IFwiaHR0cHM6Ly92YXJsZXQtdWktcGxheWdyb3VuZC52ZXJjZWwuYXBwL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCJodHRwczovL3ZhcmxldC11aS1wbGF5Z3JvdW5kLnZlcmNlbC5hcHAvdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiaHR0cHM6Ly92YXJsZXQtdWktcGxheWdyb3VuZC52ZXJjZWwuYXBwL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vdmFybGV0LXVpLXBsYXlncm91bmQudmVyY2VsLmFwcC92YXJsZXQuY3NzJ1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn1cbiJ9)
  
![画面収録 2022-06-20 午後9 24 57](https://user-images.githubusercontent.com/71680892/174612108-71a2b8cd-4032-4618-9c8e-4e1ff663a0cd.gif)

I think it is caused by  `.var-snackbar-fade-leave-active` class which applied the `position: absolute` style.
It works fine if I override the `absolute` style.

**Comment by BeADre** [comment]
are you interested in fixing it?

**Comment by cleoledev** [comment]
YES, sure! It would be great if I could contribute to this awesome project!
