### ISSUE TITLE
当我再vite配置按需引入之后,使用vue自定义的的全局指令时会报错

### ISSUE THREAD

**Issue by check1874** [varletjs/varlet#612]
# Bug report 🐞

## Actual results (or Errors)
当我再vite配置按需引入之后,使用vue自定义的的全局指令时会报错如何解决
![image](https://user-images.githubusercontent.com/53104529/175469736-16947bec-c73d-4607-92fb-279917a60fcf.png)
![image](https://user-images.githubusercontent.com/53104529/175469791-df62de3b-7533-4d82-84c7-c1eecddc34e3.png)
![image](https://user-images.githubusercontent.com/53104529/175470128-d8c0d8ea-c104-4e72-ab79-0dd64a2bbed9.png)
![image](https://user-images.githubusercontent.com/53104529/175470181-4d0091d1-e580-4bdd-b4b9-bb8f51de1e5b.png)
![image](https://user-images.githubusercontent.com/53104529/175470276-418a29cf-278c-4b8e-8fba-509f07297e7b.png)
![image](https://user-images.githubusercontent.com/53104529/175470294-aea7d070-f936-4055-979a-79e08b735be4.png)

**Comment by haoziqaq** [comment]
unplugin-vue-components 的版本是多少

**Comment by haoziqaq** [comment]
可以尝试升级 unplugin-vue-components 的版本解决问题，因为这个问题在早期的插件版本中确实存在过。

**Comment by check1874** [comment]
版本是 0.18.1

**Comment by check1874** [comment]
> unplugin-vue-components 的版本是多少

版本是 0.18.1

**Comment by check1874** [comment]
> 可以尝试升级 unplugin-vue-components 的版本解决问题，因为这个问题在早期的插件版本中确实存在过。

好的 我试试 感谢

**Comment by check1874** [comment]
> 可以尝试升级 unplugin-vue-components 的版本解决问题，因为这个问题在早期的插件版本中确实存在过。

升级 unplugin-vue-components 解决了 谢谢！

**Comment by haoziqaq** [comment]
不客气～
