### ISSUE TITLE
如何添加组件库的国际化语言，比如越南语

### ISSUE THREAD

**Issue by xxj2016** [varletjs/varlet#617]
你好，请问怎么添加组件库的国际化语言？现在组件只内置了中文跟英文，怎么添加使用其他语言哈？比如，越南语，韩语。感谢。

**Comment by xxj2016** [comment]
不好意思，我知道怎么弄了，模仿官方的文件，在本地建一个新的语言，然后add locale，跟use locale就可以了。

**Comment by haoziqaq** [comment]
嗯是的～
