### ISSUE TITLE
select 边界检测第一次选择无效

### ISSUE THREAD

**Issue by mnmnun** [varletjs/varlet#619]
select组件 边界检测页面打开或刷新，第一次选择无效。把select组件放到页面最底部，下拉选项还是在页面最底部并超出页面外，再次选择选项就正常向上显示了。
第一次选择：
![微信图片_20220701151903](https://user-images.githubusercontent.com/19620843/176844716-fa244047-517f-43c1-a7b5-a4046459575f.png)
再次选择：
![微信图片_20220701151930](https://user-images.githubusercontent.com/19620843/176844747-4fd785b5-92d8-4745-a390-66dad4ee45c5.png)

**Comment by haoziqaq** [comment]
我找负责这个 feat 的人确认一下

**Comment by wangKBweb** [comment]
> select组件 边界检测页面打开或刷新，第一次选择无效。把select组件放到页面最底部，下拉选项还是在页面最底部并超出页面外，再次选择选项就正常向上显示了。 第一次选择： ![微信图片_20220701151903](https://user-images.githubusercontent.com/19620843/176844716-fa244047-517f-43c1-a7b5-a4046459575f.png) 再次选择： ![微信图片_20220701151930](https://user-images.githubusercontent.com/19620843/176844747-4fd785b5-92d8-4745-a390-66dad4ee45c5.png)

可不可以提供一下实际场景代码或者playground演示呢

**Comment by wangKBweb** [comment]
> 
方便的话可以加一下微信群吗 在readme里有二维码

**Comment by mnmnun** [comment]
> > > 
> > 
> > 
> > QQ.20220701163144.mp4
> 
> 方便的话可以加一下微信群吗 在readme里有二维码

readme里的二维码，我这网络显示不出来

**Comment by wangKBweb** [comment]
> > > > 
> > > 
> > > 
> > > QQ.20220701163144.mp4
> > 
> > 
> > 方便的话可以加一下微信群吗 在readme里有二维码
> 
> readme里的二维码，我这网络显示不出来

18266072139 你加我 我拉你

**Comment by mnmnun** [comment]
> > > 
> > 
> > 
> > QQ.20220701163144.mp4
> 
> 方便的话可以加一下微信群吗 在readme里有二维码

刚刚发现，页面有垂直滚动条的时候，select在最底下非常靠底边的时候就会出现这问题，里最低部有点距离时就正常。比如下图是正常的：

![123456789](https://user-images.githubusercontent.com/19620843/176859095-79bb2806-7bf5-485c-88b3-ad00e8726714.png)

**Comment by mnmnun** [comment]
> > > > > 
> > > > 
> > > > 
> > > > QQ.20220701163144.mp4
> > > 
> > > 
> > > 方便的话可以加一下微信群吗 在readme里有二维码
> > 
> > 
> > readme里的二维码，我这网络显示不出来
> 
> 18266072139 你加我 我拉你

好的
