### ISSUE TITLE
dev命令没有打印出启动ip地址

### ISSUE THREAD

**Issue by liyang1345** [varletjs/varlet#648]
用脚手架创建的项目，启动后没有打印出ip地址
![image](https://user-images.githubusercontent.com/41931745/178927955-2c491e3b-18c6-45a5-9eb4-33f5211d4baf.png)

**Comment by haoziqaq** [comment]
提供一下操作系统，varlet-cli的版本

**Comment by BeADre** [comment]
猜测应该是vite版本过低的问题

 - node api
![image](https://user-images.githubusercontent.com/34639100/178961546-78f1719b-2765-4312-b873-eed2d82339d3.png)

- [vite support node v18](https://github.com/vitejs/vite/pull/7812/files#diff-6f5b07ad608d93a8d357965c94bd23e23944f9dea74be70e54a1900ad93bb58e)


可先暂时升级或降级node版本

**Comment by liyang1345** [comment]
版本"version": "1.27.17",系统：macos

**Comment by BeADre** [comment]
我看你上面截图node版本是18.3？还是说你切换成14.18还是有问题？

**Comment by liyang1345** [comment]
不好意思，刚才切换错了，切到低版本就可以了
