### ISSUE TITLE
日期组件可以出一个监听月份切换或者年份切换吗

### ISSUE THREAD

**Issue by Silvaer** [varletjs/varlet#654]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by BeADre** [comment]
你是说只切换面板但是日期无变化的时候？

**Comment by Silvaer** [comment]
> 你是说只切换面板但是日期无变化的时候？

对，可能在切换月份时需获取其他数据。场景是在日期上通过一些标识去添加一些内容，比如我8月26日有活动，通过切换面板调取接口获取八月份的所有信息，然后在每一天底下加上标识。（类似vant组件库里的自定义日期文案）

**Comment by BeADre** [comment]
后续会加上
