### ISSUE TITLE
组件库不支持vue3 setup语法吗

### ISSUE THREAD

**Issue by litongde1996** [varletjs/varlet#657]
<script setup lang="ts"></script>

**Comment by haoziqaq** [comment]
组件库构建工具不支持，组件库本身支持

**Comment by litongde1996** [comment]
有什么办法可以支持上吗，目前没有暴露出什么配置文件

**Comment by haoziqaq** [comment]
我们没有计划支持这个语法，主要原因是我们自己也是使用这个cli构建的，目前没有迁移script setup的打算

**Comment by haoziqaq** [comment]
还有一个原因是我们认为script setup对于底层的组件设计来说没有特别明显的好处，迁移对我们来说是不太值得的。我们自己都不用的特性直接加进cli里面，感觉不是特别合适，我们也没办法提前预判有哪些可能存在的问题。
