### ISSUE TITLE
vite打包后dialog函数式调用样式丢失怎么解决？

### ISSUE THREAD

**Issue by keyao** [varletjs/varlet#662]
# About `styles` 🛠️
vite打包后dialog函数式样式丢失。main.js中引入了全局样式的
![image](https://user-images.githubusercontent.com/22851847/183792191-5614fcb6-bc5a-490c-a49d-7e035ef5dbe1.png)

**Comment by puchunjie** [comment]
同问，为啥就关掉了

**Comment by haoziqaq** [comment]
@puchunjie varlet是什么版本，方便的话提供一个复现问题的仓库。他应该是自己解决了。

**Comment by haoziqaq** [comment]
先尝试升级最新的varlet版本。



---原始邮件---
发件人: "jeremy ***@***.***&gt;
发送时间: 2022年10月10日(周一) 晚上6:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [varletjs/varlet] vite打包后dialog函数式调用样式丢失怎么解决？ (Issue #662)




 
同问，为啥就关掉了

**Comment by haoziqaq** [comment]
应该和这个issue问题一致，#666，升级版本即可解决
