### ISSUE TITLE
请问开发该项目有开启ESlint吗？

### ISSUE THREAD

**Issue by suzhenghui-sky** [varletjs/varlet#665]
# Feature request 🚀

### Expected:
请问开发该项目有开启ESlint吗？我把你们的代码拷过来报一堆的ESlint错误

- No breaking changes

### Examples:

```js

```

**Comment by BeADre** [comment]
应该是你ide没有找到eslint package 你要手动配置一下

**Comment by suzhenghui-sky** [comment]
不是很懂，不过我看了几个vue3项目的目录下都是有个.eslintrc这个文件的。

**Comment by haoziqaq** [comment]
我们eslint的配置在package.json里

**Comment by BeADre** [comment]
我们项目的eslint配置放在根目录的`package.json`中，其规则继承于`packages/varlet-eslint-config`, [eslint配置文件文档](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#extending-configuration-files)
