### ISSUE TITLE
使用selece样式显示和官网的不同

### ISSUE THREAD

**Issue by suzhenghui-sky** [varletjs/varlet#666]
# Bug report 🐞
使用selece样式显示和官网的不同
## Version & Environment
import Varlet from "@varlet/ui";
import "@varlet/ui/es/style.js";
createApp(App).use(Varlet).use(store).use(router).mount("#app");
 "@varlet/ui": "^1.27.19",
    "vue": "^3.2.13",
## Expectation
![图片](https://user-images.githubusercontent.com/48371536/184057016-b881f6fc-5675-43b7-817c-b2e723f7f787.png)

## Actual results (or Errors)
![图片](https://user-images.githubusercontent.com/48371536/184057042-5bb60f90-97f1-4697-9a1e-166c4c17569b.png)

**Comment by BeADre** [comment]
请提供一个最小的可复现例子

**Comment by suzhenghui-sky** [comment]
![图片](https://user-images.githubusercontent.com/48371536/184058704-4b2c75ff-2ed6-47a1-97ef-e5bd149ef200.png)
![图片](https://user-images.githubusercontent.com/48371536/184058735-ca1f5863-24ed-43a1-b8cc-d353fff38a18.png)
![图片](https://user-images.githubusercontent.com/48371536/184058755-ea3a4e6e-48c3-4764-b254-8286c5210843.png)

**Comment by BeADre** [comment]
我不能复现你的问题 或许你需要给我一个[可复现例子](https://antfu.me/posts/why-reproductions-are-required-zh#%E4%B8%BA%E4%BB%80%E4%B9%88%E9%9C%80%E8%A6%81%E9%87%8D%E7%8E%B0)

**Comment by suzhenghui-sky** [comment]
https://github.com/suzhenghui-sky/cpy-varlet-test.git

**Comment by BeADre** [comment]
升级版本即可

**Comment by haoziqaq** [comment]
原因是我们前1-2个版本优化 tree-shaking 造成的 bug，影响了全局导入的可用性，感谢你的反馈
