### ISSUE TITLE
关于表单验证

### ISSUE THREAD

**Issue by cmf-chenmf** [varletjs/varlet#667]
我去对比了Vant3的表单验证，Button组件提供了原生native-type来提交表单，通过验证submit参数来判断是否通过表单验证。varlet表单提供了触发表单组件的验证方法validate，但是我不知道怎么去验证通过表单提交。如果现在还是要写多个if判断来控制的话，那我想我这个issue是没用的

**Comment by haoziqaq** [comment]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/24223652/184061831-5a0638d1-e539-410b-8f26-43e5ec1c88a6.png">

这个方法会返回验证是否通过，可能这边文档也写的不是很清楚，我们找时间优化一下。

**Comment by priority3** [comment]
![image](https://user-images.githubusercontent.com/75966543/184062108-f9d84732-bc7b-4dc1-bdca-f11fd56c55ac.png)
也许你可以这样

**Comment by cmf-chenmf** [comment]
抱歉自定义relus导致验证回调一直处于false

**Comment by haoziqaq** [comment]
客气了客气了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月11日(周四) 中午12:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] 关于表单验证 (Issue #667)




 
抱歉自定义relus导致验证回调一直处于false
