### ISSUE TITLE
分页器current和total都为0的时候,change事件会被执行

### ISSUE THREAD

**Issue by monhly** [varletjs/varlet#668]
问题:
使用分页组件,当前的current和total都是0的时候,在分页中输入页数是0的时候, 分页的chang事件会被执行.如果代码的逻辑中调接口请求的数据总数还是0那么分页就会继续执行change事件,进入一个死循环调接口请求.

具体代码如下:
![Snipaste_2022-08-11_13-48-20](https://user-images.githubusercontent.com/61449492/184071506-350dd33a-3d96-4caa-9023-cabaf09e5f66.jpg)

![2022-08-11 13-46-32 2022-08-11 13_46_47](https://user-images.githubusercontent.com/61449492/184072254-85a6e6d3-40d6-47a8-b2b8-93b8a3825442.gif)

在代码中需要判断当前的page不等于0,请问能否在组件中判断current为0的时候不执行change事件.

**Comment by priority3** [comment]
你好，貌似我只能看到只有每次页面刷新的时候才会去执行一次change，而当数据总数total为0，好像并不能触发change，我甚至也在本地模拟了下请求，同样不能复现，也许你可以提供一个最小重现😶

**Comment by monhly** [comment]
chang 代码中的逻辑是这样
   // 分页数据
const pageChange = (page, size) => {

    console.log(page, size);
    curPage.value = page;
    pageSize.value = size;
    //调接口
    API();
 
};
接口的逻辑就是对当前的current和total赋值
(接口返回的current是1,total是0)

然后就出现了下面的情况
![2022-08-11 14-54-20 2022-08-11 14_56_37](https://user-images.githubusercontent.com/61449492/184079981-29efcd02-75cd-43e4-a17a-cdb43be7b3b6.gif)

**Comment by monhly** [comment]
![2022-08-11 14-54-20 2022-08-11 14_56_37](https://user-images.githubusercontent.com/61449492/184080675-125f3e00-0c54-425d-b3dd-ffaf5214b710.gif)

**Comment by monhly** [comment]
![2022-08-11 14-54-20 2022-08-11 14_56_37-min](https://user-images.githubusercontent.com/61449492/184088327-acf8eca6-9cf2-4654-a083-9218b153dabb.gif)

**Comment by priority3** [comment]
这样在change当中更改current或者pagesize的值 会重新触发change，所以如果要做这样的更新我觉得不适合在change当中做这样的事情，可以考虑v-modal更新current和pagesize，这是我参考了element-plus的说明，所以不确定是否这样的设计🙄

**Comment by BeADre** [comment]
升级版本即可

**Comment by monhly** [comment]
好的👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月11日(周四) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] 分页器current和total都为0的时候,change事件会被执行 (Issue #668)




 
升级版本即可
