### ISSUE TITLE
[Feature request] 滚动内容的组件添加与浏览器无关联的细滚动条

### ISSUE THREAD

**Issue by sxwlmsrbi** [varletjs/varlet#681]
Varlet 目前所有组件中会出现滚动的地方均使用的浏览器原生滚动条，但如果使用桌面端浏览器访问由 Varlet 组件构成的网页，由于桌面端原生的滚动条很粗，导致页面不是很好看。最明显的例子之一就是开启滚动后的选项卡组，很粗的滚动条出现在选项卡底部，导致选项卡组非常难看。希望会出现滚动内容的组件中，可以自由选择是否启用与浏览器无关的细滚动条。

**Comment by haoziqaq** [comment]
好的，我们会在v2.0的分支处理这个问题
