### ISSUE TITLE
[Feature request] UMD 模块添加对暗黑模式的支持

### ISSUE THREAD

**Issue by sxwlmsrbi** [varletjs/varlet#682]
只通过 UMD 模块来使用 Varlet 貌似无法顺利应用暗黑模式，在 https://cdn.jsdelivr.net/npm/@varlet/ui@1.27.20/umd/varlet.js 的代码中虽然暴露了 StyleProvider 函数，但未找到暗黑模式相关样式（找不到 dark)。浏览https://cdn.jsdelivr.net/npm/@varlet/ui@1.27.20/es/themes/dark/ 目录发现 dark 只是导出了一些 CSS 样式，封装进 UMD 应该不会影响组件库的轻量性。所以希望添加对暗黑模式的支持，如果本身已支持还请说明一下怎么使用，谢谢😉

**Comment by haoziqaq** [comment]
v2.0分支已经显式的对外暴露，会跟着2.0一起release，并且优化了直接引入（umd）的使用方式
