### ISSUE TITLE
[Bug] UMD 模块水波指令无效

### ISSUE THREAD

**Issue by sxwlmsrbi** [varletjs/varlet#684]
# Bug report 🐞

通过 UMD 模块使用组件库时，水波指令无效

## Version & Environment

Varlet 和 Vue 的 UMD 模块均为当前最新版本
Firefox:104
Chrome:104
OS:Windows 10

## Expectation

点击元素产生正常的水波扩散效果

## Actual results (or Errors)

点击元素无水波扩散效果

## Reproduction

改写自官方文档的示例代码: https://jsbin.com/rihocuyoze/1/edit?html,console,output

**Comment by haoziqaq** [comment]
桌面端需要安装适配器 参考文档 https://varlet-varletjs.vercel.app/#/zh-CN/browserAdaptation

**Comment by sxwlmsrbi** [comment]
> 桌面端需要安装适配器 参考文档 https://varlet-varletjs.vercel.app/#/zh-CN/browserAdaptation

@varlet/touch-emulator 貌似是ES6模块，未提供UMD模块的CDN引入，希望增加UMD支持或简化适配器的启用🧐

**Comment by haoziqaq** [comment]
有iife的版本 在文档中没体现出来 抽空补一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] [Bug] UMD 模块水波指令无效 (Issue #684)




  
桌面端需要安装适配器 参考文档 https://varlet-varletjs.vercel.app/#/zh-CN/browserAdaptation
  
@varlet/touch-emulator 貌似是ES6模块，未提供UMD模块的CDN引入，希望增加UMD支持或简化适配器的启用🧐

**Comment by sxwlmsrbi** [comment]
感谢！但刚刚发现只要手动去掉最后一句也可以正常使用🤣

**Comment by haoziqaq** [comment]
哈哈哈 不客气



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月3日(周六) 中午12:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] [Bug] UMD 模块水波指令无效 (Issue #684)




 
感谢！但刚刚发现只要手动去掉最后一句也可以正常使用🤣
