### ISSUE TITLE
template中识别不到组件的ts定义，vscode也未高亮组件

### ISSUE THREAD

**Issue by LizNex** [varletjs/varlet#685]
# Bug report 🐞
template中识别不到组件的ts定义，vscode也未高亮组件，但vant组件都可以正常识别，如图
![origin_img_v2_c00f5a35-915f-41ea-ba99-69d043cb078g](https://user-images.githubusercontent.com/20060832/188355518-2aee98cf-fe92-49fd-a6e8-8b6e12d86b1b.jpg)
![origin_img_v2_a63f3dcf-5f81-4776-97e8-30bcd4fa710g](https://user-images.githubusercontent.com/20060832/188355525-db8825f3-4a6b-41d3-b0db-35dfd8e48f2d.jpg)
![origin_img_v2_ad18a3fe-a9b3-4fb2-a9d5-687174cdefbg](https://user-images.githubusercontent.com/20060832/188355544-c1ed178f-fb28-41a1-846f-f3438b7b4d92.jpg)

## Version & Environment
@varlet/ui: 1.27.20

## Expectation
希望能够和vant一样识别到ts定义，vscode中也能高亮

**Comment by haoziqaq** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/24223652/188358520-9f13cc34-9dea-4093-98be-091bf0cf8cda.png">

参考一下这里，另外我也好奇vant可以不用配置就能得到提示么？ 可否给我一个你的案例仓库供我参考一下

**Comment by LizNex** [comment]
> 
这是示例仓库：https://github.com/LizNex/test-vant-varlet-highlight
把一些项目相关的删除了，可能跑不起来，但是能复现上方的问题

**Comment by LizNex** [comment]
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/24223652/188358520-9f13cc34-9dea-4093-98be-091bf0cf8cda.png">
> 
> 参考一下这里，另外我也好奇vant可以不用配置就能得到提示么？ 可否给我一个你的案例仓库供我参考一下

ts.config.json 是指ts的配置文件吗？如果是的话应该是tsconfig.json吧 😹
如果不是，还请指教下是哪个ts.config.json

**Comment by haoziqaq** [comment]
tsconfig.json 文档 typo 有误

**Comment by haoziqaq** [comment]
刚看了一下案例仓库，提供给 volar 的类型声明是通过 unplugin-vue-components 自动生成的， 这一块 varlet 和 vant 的逻辑几乎是一样的。 这种方案有个很大的问题在于，你必须启动了 vite 服务，并且使用过组件的文件请求到达过服务器并且执行过编译之后，才可以生成类型声明。 我们还是推荐手动配置一下类型 (就如同 vite 一样)，这样一来在应用没启动过的情况下也能得到类型提示。

**Comment by LizNex** [comment]
> 刚看了一下案例仓库，提供给 volar 的类型声明是通过 unplugin-vue-components 自动生成的， 这一块 varlet 和 vant 的逻辑几乎是一样的。 这种方案有个很大的问题在于，你必须启动了 vite 服务，并且使用过组件的文件请求到达过服务器并且执行过编译之后，才可以生成类型声明。 我们还是推荐手动配置一下类型 (就如同 vite 一样)，这样一来在应用没启动过的情况下也能得到类型提示。

我试了启动vite服务后，varlet组件仍然没有高亮..

**Comment by haoziqaq** [comment]
配置之后也没高亮么？

**Comment by LizNex** [comment]
> 

配置tsconfig.json以后高亮了
就是同样不配置的情况下，启动vite，vant会高亮，但varlet不会，就是觉得很神奇，不过可以高亮就解决我的问题了，感谢

**Comment by haoziqaq** [comment]
![image](https://user-images.githubusercontent.com/24223652/188399703-dbee6ed4-630e-45ec-a94a-c2a1846946f0.png)

**Comment by haoziqaq** [comment]
好的～

**Comment by LizNex** [comment]
> 好的～
另外想请教下，用varlet-cli写组件，组件的types都是手写的，不是根据组件自动生成的是吗？

**Comment by haoziqaq** [comment]
这个是我们刻意为之的，我们觉得想把用户使用的类型和维护者使用的类型区分开，比如有些内置的类型，我们就不愿意暴露给用户去干扰用户使用。也可以避免引入一些 break change
