### ISSUE TITLE
按需引入也会最终会将组件全部打包

### ISSUE THREAD

**Issue by Tyh2001** [varletjs/varlet#689]
# Bug report 🐞

在按需引入的情况下，最终打包也会把全部组件都打包进去。可以在测试时只引入一个组件，然后打包，在打包结果中搜索其它组件关键词，如组件名或类名，都可以搜索到。

而且不管是按需引入还是全部引入，打包出来的文件大小是一样的

main.ts

```ts
import { createApp } from 'vue'
import App from './App.vue'
// 按需引入
import { Button } from '@varlet/ui'

createApp(App).use(Button).mount('#app')
```

## Version & Environment

"@varlet/ui": "^1.27.20",

## Expectation

预期是只是打包需要的，引入什么就打包什么

## Actual results (or Errors)

实际上将全部组件都打包到 dist 了

**Comment by Tyh2001** [comment]
因为最近[我的项目](https://github.com/FightingDesign/fighting-design)也遇到了相同的问题，发现是因为在注册插件[这里](https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/button/index.ts)产生了副作用，副作用代码就是：

```ts
Button.install = function (app: App) {
  app.component(Button.name, Button)
}
```

不过目前我还没找到比较好的解决方案

**Comment by BeADre** [comment]
我没法复现你的问题
![image](https://user-images.githubusercontent.com/34639100/189848909-e7f2d56e-a155-4715-8dad-7095a62cb3b4.png)

![image](https://user-images.githubusercontent.com/34639100/189849305-0728a17e-bfa3-42df-9b08-10cb2f6d1324.png)

**Comment by Tyh2001** [comment]
问题出在这里：https://github.com/Tyh2001/the-varlet-build-bug

直接 `pnpm build` 即可

![image](https://user-images.githubusercontent.com/73180970/189852707-70c64c25-8af1-4ea3-a854-64203a543a41.png)

@BeADre

**Comment by BeADre** [comment]
我依然无非复现你的问题 @haoziqaq 你来试试

**Comment by wangKBweb** [comment]
已经解决了吗 我在删除了
![image](https://user-images.githubusercontent.com/85718018/189866010-267cfdc3-ed15-4dce-8ea3-5167f529793a.png)
这个依赖后 也是正常运行 没有复现

**Comment by Tyh2001** [comment]
这个项目是我之前的一个测试项目，安装了好几个组件库，之前都是全部打包的，后来才使用的按需打包，可能是 vite 缓存了吧？

我刚才重新安装了依赖项就无法复现了
