### ISSUE TITLE
下拉刷新事件的一些问题

### ISSUE THREAD

**Issue by boringmj** [varletjs/varlet#693]
# About `styles` 🛠️
我不知道我该如何阻止下拉刷新事件向父级传递,在chrome移动端中,我尝试下拉刷新会导致chrome也响应下拉刷新事件,导致整个页面被刷新，而我预期的仅仅是下拉刷新组件中的数据被刷新，请问我该如何阻止chrome响应这个事件呢

**Comment by haiya6** [comment]
也许你可以尝试一下这里的答案 https://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature

**Comment by BeADre** [comment]
上面的链接也许可以解决你的问题
