### ISSUE TITLE
Card 组件的content插槽无效

### ISSUE THREAD

**Issue by chenshiming1113** [varletjs/varlet#705]
# Bug report 🐞

**Comment by haoziqaq** [comment]
`content` 在 `Card` 的设计中指的是卡片漂浮时显示的正文内容，可能 `content` 这个 api 命名误导了你，也的确是反直觉的。 我们将在 2.0 的版本中进行重命名，感谢你的反馈。

**Comment by chenshiming1113** [comment]
感谢，响应好快

**Comment by haoziqaq** [comment]
哈哈哈～🙏
