### ISSUE TITLE
input 添加 readonly后，外部修改state值， 没法触发验证,有什么方法解决吗？

### ISSUE THREAD

**Issue by eleanors** [varletjs/varlet#712]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by nonzzz** [comment]
添加了`readonly`以后.Input组件作为只读的从设计的原则上来说。组件作为受控的一方有自己的临时状态.验证值更改的行为应该是在这个值自己发生了改变而不是我通过modelValue 去驱动他是否要验证数据。从设计上来看这样是不合理的。因为 `input` 组件触发校验应该是发生在元素自己的input change blur focus的时候。 至于你想通过`v-model` 外部驱动的话。你可以给`input`组件提供一个`ref`值。 `var-input`组件向外暴露了一个`validate`的方法你可以用它进行手动验证。[地址](https://github.com/varletjs/varlet/blob/dev/packages/varlet-ui/src/input/Input.vue#L289-L308)

**Comment by eleanors** [comment]
好的已解决 , 感谢

**Comment by haoziqaq** [comment]
不客气
