### ISSUE TITLE
var-cell 在使用的时候description无法显示

### ISSUE THREAD

**Issue by neatstudio** [varletjs/varlet#719]
# Bug report 🐞
包括官网，在[cell](https://varlet.gitee.io/varlet-ui/#/zh-CN/cell)页，点击playground，输入
```javascript 
<var-cell title='这是单元格' description='描述'/>
```
照样无法显示【描述】这段文字

**Comment by haoziqaq** [comment]
我们刚刚发布了2.0的版本，详情可以看最新的[迁移指南](https://varlet.gitee.io/varlet-ui/#/zh-CN/migrationGuide)。 playground 可能存在缓存，可以尝试清空缓存重试。

**Comment by neatstudio** [comment]
这么巧的么。。。

嗯，切到2.0.0.alphaxxxx后，确实正常了

**Comment by haoziqaq** [comment]
确实很巧哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月12日(周三) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] var-cell 在使用的时候description无法显示 (Issue #719)




 
这么巧的么。。。
 
嗯，切到2.0.0.alphaxxxx后，确实正常了
