### ISSUE TITLE
表单设置只读以后，选择框可以被点击弹出选项

### ISSUE THREAD

**Issue by Lin-Ya** [varletjs/varlet#730]
# Bug report 🐞
[地址](https://varlet.gitee.io/varlet-ui/#/zh-CN/form)
如题，在文档页面中进去表单页以后
1. 点击下方“表单只读”按钮以后
2. 点击上方的任意一个选择框，此时出现了选择框选项的弹窗
## Version & Environment
version: v2.05
环境：官方文档页
## Expectation
在表单组件配置只读状态以后，点击选择框没有任何响应
## Actual results (or Errors)
![image](https://user-images.githubusercontent.com/33563178/196883423-8648943b-b0b4-4eab-ae1b-b4cb88489f14.png)
![image](https://user-images.githubusercontent.com/33563178/196883525-e5153176-c137-4825-a557-113417e6c30a.png)

**Comment by Lin-Ya** [comment]
补充一下，在表单禁用状态下，也会出现类似的情况。
![image](https://user-images.githubusercontent.com/33563178/196883950-26ec74fb-64f0-4b6f-9292-a34d62a83d12.png)

**Comment by haoziqaq** [comment]
升级到 2.0.6
