### ISSUE TITLE
滑块的取值范围只能在0到100。但是我想设置200、300、1000

### ISSUE THREAD

**Issue by yueduz** [varletjs/varlet#732]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by nonzzz** [comment]
I think we can join two props called  `min` and `max`. And according min and max to calculate. But now. I saw the source code. If we do. the step logic may be effect.

**Comment by BeADre** [comment]
As nonzzz said，I will add min and max props utils I finished migrate

**Comment by wangKBweb** [comment]
he's kanno
