### ISSUE TITLE
关于表单自定义组件

### ISSUE THREAD

**Issue by popring** [varletjs/varlet#733]
想问下如何实现一个自定义组件，而且可以结合表单相关功能使用呢？

看了下文档，现在各种校验规则，方式都是绑定在每个内置的组件上，所以有点疑惑。

**Comment by haoziqaq** [comment]
Varlet 的表单组件是通过内部的 FormDetails 组件 + useForm + useValidation 实现的。但在目前我们的文档中并没有体现。后面我们会完善这一块的内容。

**Comment by popring** [comment]
> Varlet 的表单组件是通过内部的 FormDetails 组件 + useForm + useValidation 实现的。但在目前我们的文档中并没有体现。后面我们会完善这一块的内容。

好的，谢谢回复👍🏻

**Comment by haoziqaq** [comment]
客气了

**Comment by haoziqaq** [comment]
v2.2.0@alpha 已经支持
