### ISSUE TITLE
uploader  组件 在浏览器页面闪退问题

### ISSUE THREAD

**Issue by glIrving** [varletjs/varlet#742]
小米机型 安卓13

varlet - vue3版本

当用户使用小米手机 打开app（webapp）中uploader组件选择文件时  页面黑屏然后闪退

**Comment by haoziqaq** [comment]
什么文件，多大的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 上午8:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] uploader  组件 在浏览器页面闪退问题 (Issue #742)




 
小米机型 安卓13
 
varlet - vue3版本
 
当用户使用小米手机 打开app（webapp）中uploader组件选择文件时  页面黑屏然后闪退

**Comment by glIrving** [comment]
> 什么文件，多大的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年11月2日(周三) 上午8:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [varletjs/varlet] uploader 组件 在浏览器页面闪退问题 (Issue #742) 小米机型 安卓13 varlet - vue3版本 当用户使用小米手机 打开app（webapp）中uploader组件选择文件时 页面黑屏然后闪退 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
还没选择文件就闪退了

**Comment by haoziqaq** [comment]
可以提供一个最小化的复现demo么，方便我们进行复现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 上午8:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] uploader  组件 在浏览器页面闪退问题 (Issue #742)




  
什么文件，多大的
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年11月2日(周三) 上午8:25 收件人: @.&gt;; 抄送: @.&gt;; 主题: [varletjs/varlet] uploader 组件 在浏览器页面闪退问题 (Issue #742) 小米机型 安卓13 varlet - vue3版本 当用户使用小米手机 打开app（webapp）中uploader组件选择文件时 页面黑屏然后闪退 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
 还没选择文件就闪退了

**Comment by glIrving** [comment]
业务比较复杂只能提供部分 代码放附件中了


该邮件从移动设备发送



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "varletjs/varlet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [varletjs/varlet] uploader  组件 在浏览器页面闪退问题 (Issue #742)





 可以提供一个最小化的复现demo么，方便我们进行复现 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年11月2日(周三) 上午8:52 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [varletjs/varlet] uploader  组件 在浏览器页面闪退问题 (Issue #742) 
 
 
 
 
    
 什么文件，多大的 
  … 
  ---原始邮件--- 发件人: @.&amp;gt; 发送时间: 2022年11月2日(周三) 上午8:25 收件人: @.&amp;gt;; 抄送: @.&amp;gt;; 主题: [varletjs/varlet] uploader 组件 在浏览器页面闪退问题 (Issue #742) 小米机型 安卓13 varlet - vue3版本 当用户使用小米手机 打开app（webapp）中uploader组件选择文件时 页面黑屏然后闪退 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&amp;gt; 
  还没选择文件就闪退了

**Comment by haoziqaq** [comment]
我们有人正在尝试用 uniapp 构建 webapp 复现问题。需要一些时间。

**Comment by jiechen66** [comment]
你好 我这边 小米12s pro的机型    安卓13
varlet - vue3 
 uniapp  webapp测试以后暂时没有发现这个问题
能问下你具体的手机型号吗   或者有没有可能是内存太小导致的

**Comment by glIrving** [comment]
小米12 8+256的 这个问题也是偶尔发现的 出现的频率并不高&nbsp;


该邮件从移动设备发送



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月2日(星期三) 下午2:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [varletjs/varlet] uploader  组件 在浏览器页面闪退问题 (Issue #742)





 
你好 我这边 小米12s pro的机型    安卓13
 varlet - vue3
 uniapp  webapp测试以后暂时没有发现这个问题
 能问下你具体的手机型号吗   或者有没有可能是内存太小导致的
 
&mdash;

**Comment by haoziqaq** [comment]
如果是选择了大文件，可能出现 base64 编码占用大量内存闪退的情况，后面我们考虑加一个文件尺寸的阈值，超过这个阈值就跳过 base64 的编码，可能会减少这类情况的发生。如果并没有选择大文件直接闪退了，可能还是要在手机本身找原因了。

**Comment by glIrving** [comment]
目前情况是还没有选择文件的时候 ，也就是在点击加号打开文件选择器这个界面的时候会出现这种情况&nbsp;


该邮件从移动设备发送



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月2日(星期三) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [varletjs/varlet] uploader  组件 在浏览器页面闪退问题 (Issue #742)





 
如果是选择了大文件，可能出现 base64 编码占用大量内存闪退的情况，后面我们考虑加一个文件尺寸的阈值，超过这个阈值就跳过 base64 的编码，可能会减少这类情况的发生。如果并没有选择大文件直接闪退了，可能还是要在手机本身找原因了。

**Comment by haoziqaq** [comment]
相当于是 `input = file` 在拉起相册的时候就闪退了，这个我认为跟组件本身的关系应该不是很大了，处理逻辑没走到。

**Comment by haoziqaq** [comment]
相当于是 `input[type=file]` 在拉起相册的时候就闪退了，这个我认为跟组件本身的关系应该不是很大了，处理逻辑没走到。
