### ISSUE TITLE
希望添加环形滑块,像环形进度条一样的那种.滑块应支持鼠标滚轮事件.

### ISSUE THREAD

**Issue by yueduz** [varletjs/varlet#745]
# Feature request 🚀

### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by BeADre** [comment]
这个组件并不常见，它的使用场景是啥？

**Comment by yueduz** [comment]
> 这个组件并不常见，它的使用场景是啥？

仪表盘

**Comment by BeADre** [comment]
交互性的仪表盘在移动端项目中使用场景太苛刻了，我认为它不适合放在组件库中
