### ISSUE TITLE
Button support to replace href target props

### ISSUE THREAD

**Issue by a145789** [varletjs/varlet#747]
# Feature request 🚀

### Expected:
button support navigation, when you use `href`, will be rendered as `<a />`, use `to` or `replace`, will be rendered as `<router-link /> `
- No breaking changes

### Examples:

[quasar button handling navigation](https://quasar.dev/vue-components/button#handling-navigation)

```js
<var-button href="www.baidu.com">默认按钮</var-button>
<var-button href="www.baidu.com" target="_blank">默认按钮</var-button>
<var-button to="/">默认按钮</var-button>
<var-button replace="/">默认按钮</var-button>
```

### Programme:
如果觉得这个功能可以的话，我可以参与开发.

**Comment by nonzzz** [comment]
FYI. I think if we implement it. it will not be a good idae. The following reasons will prove my point.

- First, duck element is not friendly for brower. ( Because if user add prop href for `var-button` it will be generator as <a /> So that browser can't handle his behavior properly. If you add role as button for it. 
- Second, follow the above. If you nested the implemented varlet button in a form component. and I wann use submit. How to use? Because the varlet button is translate as `a` not `button`.
- Thrid, If you want to do this. I think add a new component who named as `link`. you can refer [next's link component](https://nextjs.org/docs/api-reference/next/link). it's a right way. I think so.

**Comment by haoziqaq** [comment]
I also think it would be better to make a link component to solve this problem

**Comment by a145789** [comment]
英语能力只有机翻的三言两语，用中文表述一下吧。

我觉得 ` link`  组件和按钮使用  `href` 可以共同存在。

如果  `botton`  传入  `href` `props`，开发者应当明白此时按钮提供的功能和原生 `a`  标签并无二致。如果开发者希望在跳转前或跳转后做一些操作，原生 `a` 标签无法满足其行为，那也就不应该再使用 `href` 功能的按钮组件。

使用 `href` 功能的按钮组件和作为表单的按钮组件应用场景大部分并不重叠。正常情况下表单提交都会进行一些验证、数据再处理或者接口调用操作，如上面所说，如果希望只加一个 `href` `prop`  就可以实现表单提交后跳转到其他页面 ，从开发者的角度是有点匪夷所思的。

此外，从设计的角度考虑，`link` 组件和 `href` 按钮的功能有重叠有不同。`link` 是一个明确性的指向链接，而  `button`  按钮是一个功能性操作，但诸如 `next`  `preview`  `more`  此类的操作在现实开发中  `UI` 可能设计为链接也可能设计为按钮。比如当前页面上的 `New issue`  按钮，我们似乎没办法把它当做链接对待。

给按钮组件添加 `href` 功能可以减少此场景下还需注册一个事件使用 `windows.open` 或者 `router.push` 做跳转的繁琐操作，同时对用户而言，增加浏览器原生功能，比如移动端下长按此按钮，在新 `Tab` 页打开。

以上。

---------------------------------------------
I think the 'link' component and the button can coexist with the 'href'.

If you call 'botton' to 'href' props', you should know that buttons provide the same functions as native 'a' tags. If a developer wants to do something before or after a jump, and the native A tag doesn't satisfy that behavior, then the button component of the 'href' function should no longer be used.

The button component that uses the 'href' function and the button component that acts as a form do not overlap for the most part. Normally, a form submission requires validation, data reprocessing, or an interface call. As mentioned above, if you want to add only a 'href' prop 'to the form submission and then jump to another page, it is a bit strange from the perspective of the developer.

In addition, from a design perspective, the link component and the href button have overlapping and different functions. 'link' is a specific pointing link, and 'button' is a functional action, but actions such as' next ' 'preview' 'more' in real development 'UI' may be designed as a link or a button. For example, the 'New issue' button on the current page, we don't seem to be able to treat it as a link.

Adding the 'href' function to the button component can reduce the tedious operation of registering an event to jump to windows.open or router.push in this scenario, while adding browser native functions for the user, such as long pressing the button on the mobile side to open a new Tab page.

**Comment by a145789** [comment]
`<var-link `to="/avatar"><var-button>Action</var-button></var-link>`

虽然我觉得一个组件的内部实现可以黑盒一些，不过这个方式更赞👍。

**Comment by a145789** [comment]
> button是按钮.而a标签的意义则是连接.指鹿为马的行为无论从哪看都是十分奇怪的

还是想对这句话再讨论下，以这个 github issuses 页面为例。

<img width="610" alt="image" src="https://user-images.githubusercontent.com/37403253/201251269-4cc71db4-dbcf-4084-bcfd-9b2be88d6046.png">
这是一个明确指向性的链接  

***
<img width="343" alt="image" src="https://user-images.githubusercontent.com/37403253/201251394-f00fc649-1658-4dd7-b581-dc1a17fbcb42.png">
这是一个功能性按钮，只不过这个功能可以跳转到另一个页面

***
虽然它们都是具备跳转页面功能，当用户绝对不会把它们当作同一种交互。从语义化的角度讲一个 button 想要做到页面跳转功能

```html
<var-button :href="...">New issues</var-button>
<var-link to="/avatar"><var-button>Action</var-button></var-link>
```
其实都不对，因为不论从用户的角度还是浏览器的角度 button 语义想要跳转就应当使用一个 click 事件触发 window.open 跳转，`button` 是不应该具有长按打开行页面的功能，这个需求从浏览器语义的角度讲不合理，但它的确已经存在存在于现实的开发中了，无论对于用户设计师开发者都不可逆转，这个时候打破语义化也无不妥。

而事实上即便使用
```html
<var-link to="/avatar"><var-button>Action</var-button></var-link>
```
这种方式，它最终呈现的效果，面对用户所表达的交互意义仍然是 `button` ，不是 `link`，但浏览器把它识别为了链接。从语义化的角度，对一个按钮让它打开新页面本身就是一个不合理需求，或者浏览器在`原生js`对这种能力提供弱 ，这个时候不论是用哪种方式都是在做折衷。
