### ISSUE TITLE
support var-link component

### ISSUE THREAD

**Issue by a145789** [varletjs/varlet#748]
# Feature request 🚀

### Expected:
**API**

 | name | type | default |
 | --- | ---- | --- |
 | type | `default` `primary` `info` `success` `warning` `danger` | default |
 | underline | `always`  `hover`   `none` | always |
 | disabled | boolean | false |
 | no-style | boolean | false |
 | href | string | - |
 | target | - | - |
 | to | string | - |
 | replace | boolean | false | 

 **slot**
 default

样式可以和 `button` 组件的文字模式保持一致，但是没有水波纹和外部边框，不知道类型为 `default` 是否会对内部 slot 样式有侵入性，`no-style` 表示只清除 a 标签默认样式，不再指定任何样式。
`href` 优先级高于 `to` 。

 **No breaking changes**

### Examples:

```html
<var-link href="www.baidu.com">百度</var-link>
<var-link to="/home">首页</var-link>
<var-link to="/home" no-style>
  <var-button>Hello</var-button>
</var-link>
```

### Programme:

reference: [Element Plus Link](https://element-plus.org/zh-CN/component/link.html) | [Mui Link](https://mui.com/zh/material-ui/api/link/)

### Others:
[#747](https://github.com/varletjs/varlet/issues/747)

**Comment by haoziqaq** [comment]
建议 `no-style` 改为 `default-style`，和 `Menu` 组件一致。 再增加一个 `text-color`。其他都挺好的，非常感谢～

**Comment by a145789** [comment]
> 建议 `no-style` 改为 `default-style`，和 `Menu` 组件一致。 再增加一个 `text-color`。其他都挺好的，非常感谢～

好的，周六日我尝试开发一下

**Comment by haoziqaq** [comment]
好的好的



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 11, 2022 17:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [varletjs/varlet] support var-link component (Issue #748)




  
建议 no-style 改为 default-style，和 Menu 组件一致。 再增加一个 text-color。其他都挺好的，非常感谢～
  
好的，周六日我尝试开发一下

**Comment by nonzzz** [comment]
Sounds good. I'll wait you do it.
