### ISSUE TITLE
使用组件生成库的问题

### ISSUE THREAD

**Issue by z851103999** [varletjs/varlet#751]
### 我编写了一个message但是我不知道去哪个文件声明我的全局对象
``` js
app.config.globalProperties.$message
```

**Comment by BeADre** [comment]
你应该是没办法添加全局属性 但我比较好奇你是出于什么样的需求添加这个玩意儿呢

**Comment by z851103999** [comment]
> 你应该是没办法添加全局属性 但我比较好奇你是出于什么样的需求添加这个玩意儿呢

主要想全局调用，做不到那就局部应用吧。
