### ISSUE TITLE
请问现在uni-app可以用varlet了吗？

### ISSUE THREAD

**Issue by lukangkang** [varletjs/varlet#753]
# Feature request 🚀

**Comment by nonzzz** [comment]
不能。 你如果想在 uniapp使用varlet。可以参考在`webview`上承载。 因为这种hybrid 方案对于框架来说需要花费不少精力适配。适配了uniapp就会有taro 等等。 理想的情况是需要一个dsl=>dsl的过程。而不是徒增工作量。

**Comment by lukangkang** [comment]
> 不能。 你如果想在 uniapp使用varlet。可以参考在`webview`上承载。 因为这种hybrid 方案对于框架来说需要花费不少精力适配。适配了uniapp就会有taro 等等。 理想的情况是需要一个dsl=>dsl的过程。而不是徒增工作量。

那这样不是很局限了吗，Varlet定位为移动端UI框架，现在移动端有几个产品纯做H5在手机浏览器用的的？都是小程序，安卓，IOS这样的

**Comment by nonzzz** [comment]
> 那这样不是很局限了吗，Varlet定位为移动端UI框架，现在移动端有几个产品纯做H5在手机浏览器用的的？都是小程序，安卓，IOS这样的.

你可以参考vant。vant 官方只提供了 原生小程序版本。其他的平台则是由第三方进行提供。

**Comment by haoziqaq** [comment]
是很局限，但是没办法。

第一个是技术上很难行得通，小程序的渲染性能很差，varlet 要想跑在小程序或者一些跨端框架上，可能效果要打骨折。
第二个是时间成本，就算勉强能够接受打骨折的效果，我们再去维护一个仓库，并且保证开源态度，不玩水。对于一个纯社区并且没有任何其他收益来源的组织来说很困难。
第三个其实 varlet 写C端，桌面端也很不错。我自己很多的桌面应用也用的 varlet，还是比较顺手的。

**Comment by lukangkang** [comment]
> 是很局限，但是没办法。
> 
> 第一个是技术上很难行得通，小程序的渲染性能很差，varlet 要想跑在小程序或者一些跨端框架上，可能效果要打骨折。 第二个是时间成本，就算勉强能够接受打骨折的效果，我们再去维护一个仓库，并且保证开源态度，不玩水。对于一个纯社区并且没有任何其他收益来源的组织来说很困难。 第三个其实 varlet 写C端，桌面端也很不错。我自己很多的桌面应用也用的 varlet，还是比较顺手的。

**Comment by lukangkang** [comment]
@haoziqaq 谢谢作者解答，我现在想用material风格的UI做个安卓端，但我既不会安卓原生开发，能找到的移动端mateial风格UI好像也只有varlet(并且完成度很高)。
想问下我采用什么样的技术方案来做比较好呢？不用考虑小程序，不做微信小程序

**Comment by haoziqaq** [comment]
现在主流的跨端方案，比如像是 react-native，都可以去给 webview 提供原生能力。

**Comment by haoziqaq** [comment]
嗯，肯定可以的，uniapp 就是做 hybird 起家的
