### ISSUE TITLE
如何让Card组件宽度填满浏览器

### ISSUE THREAD

**Issue by liuts** [varletjs/varlet#758]
# About `styles` 🛠️
现在使用Card组件发现，在浏览器中两边会有空。我想要让Card组件填满，应该怎么设置。

多谢。

![image](https://user-images.githubusercontent.com/8000832/202829584-210db8a8-7d1a-4253-9f78-c14a92aed00c.png)

**Comment by qytayh** [comment]
截图中没有填满浏览器是因为我们在外层容器中设置了padding
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/39668309/202833957-dc8fb8ae-8bf3-41a7-af67-796317ceef90.png">

card组件是可以撑满他的父容器的，见这个 [例子](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gVmFybGV0IScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPSdkZW1vLWNvbnRhaW5lcic+XG4gIDx2YXItY2FyZFxuICAgIHRpdGxlPVwi5pys6I2J57qy55uuXCJcbiAgICBzdWJ0aXRsZT1cIuaIkeihqOaDheaCoOWTiSDot7PkuKrlpKfmpoJcIlxuICAgIGRlc2NyaXB0aW9uPVwi5aaC5p6c5Y2O5L2X5YaN5LiWLOW0h+a0i+mDveiiq+WMu+ayuyzlpJbpgqbmnaXlrabmsYnlrZcs5r+A5Y+R5oiR5rCR5peP5oSP6K+G44CC6ams6ZKx5a2Q44CB5Yaz5piO5a2Q44CB6IuN6ICz5a2Q77yM6L+Y5pyJ6I6y5a2Q77yb6buE6I2v5a2Q44CB6Ium6LGG5a2Q44CB5bed5qWd5a2Q77yM5oiR6KaB6Z2i5a2Q44CC55So5oiR55qE5pa55byP77yM5pS55YaZ5LiA6YOo5Y6G5Y+y44CC5rKh5LuA5LmI5Yir55qE5LqL77yM6Lef552A5oiR5b+15Yeg5Liq5a2X44CC5bGx6I2v5b2T5b2S5p645p2eIEdP77yM5bGx6I2vIOW9k+W9kiDmnrjmnZ4gR0/vvIznnIvmiJHmipPkuIDmiorkuK3oja/vvIzmnI3kuIvkuIDluJbpqoTlgrJ+XCJcbiAgICBzcmM9XCJodHRwczovL3ZhcmxldC5naXRlZS5pby92YXJsZXQtdWkvY2F0LmpwZ1wiXG4gIC8+XG4gIDwvZGl2PlxuIFxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuZGVtby1jb250YWluZXJ7XG4gICAgYm9yZGVyOiAycHggc29saWQgcmVkO1xuICB9XG48L3N0eWxlPlxuIiwiUGxheWdyb3VuZC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpXCI6IFwiLi92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3RvdWNoLWVtdWxhdG9yXCI6IFwiLi92YXJsZXQtdG91Y2gtZW11bGF0b3IuanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=)

在使用的时候保证其父容器填满且没设置横向的间距即可

**Comment by liuts** [comment]
非常感谢qytayh。根据你的例子，我找这里没有撑满原因找到了。是因为 “用户代理样式表”的原因。
