### ISSUE TITLE
loading icon size is not correct in mini button

### ISSUE THREAD

**Issue by wtto00** [varletjs/varlet#761]
# Bug report 🐞
在非`normal`大小的`button`中，开启`loading`的情况下，`loading`图标的大小不正确

[demo](https://varlet.gitee.io/varlet-ui-playground/?initialTheme=dark#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dmFyLXNwYWNlIDpzaXplPVwiWzEwLCAxMF1cIj5cbiAgICA8dmFyLWJ1dHRvbiBsb2FkaW5nIHNpemU9XCJtaW5pXCIgdHlwZT1cInByaW1hcnlcIj5cbiAgICAgIOWKoOi9veeKtuaAgVxuICAgIDwvdmFyLWJ1dHRvbj5cbiAgICA8dmFyLWJ1dHRvbiBsb2FkaW5nIHR5cGU9XCJpbmZvXCIgbG9hZGluZy10eXBlPVwicmVjdFwiPlxuICAgICAg5Yqg6L2954q25oCBXG4gICAgPC92YXItYnV0dG9uPlxuICAgIDx2YXItYnV0dG9uIGxvYWRpbmcgdHlwZT1cInN1Y2Nlc3NcIiBsb2FkaW5nLXR5cGU9XCJkaXNhcHBlYXJcIj5cbiAgICAgIOWKoOi9veeKtuaAgVxuICAgIDwvdmFyLWJ1dHRvbj5cbiAgICA8dmFyLWJ1dHRvbiBsb2FkaW5nIHR5cGU9XCJkYW5nZXJcIiBsb2FkaW5nLXR5cGU9XCJjdWJlXCI+XG4gICAgICDliqDovb3nirbmgIFcbiAgICA8L3Zhci1idXR0b24+XG4gICAgPHZhci1idXR0b24gbG9hZGluZyB0eXBlPVwid2FybmluZ1wiIGxvYWRpbmctdHlwZT1cIndhdmVcIj5cbiAgICAgIOWKoOi9veeKtuaAgVxuICAgIDwvdmFyLWJ1dHRvbj5cbiAgPC92YXItc3BhY2U+XG48L3RlbXBsYXRlPlxuIiwiUGxheWdyb3VuZC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpXCI6IFwiLi92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3RvdWNoLWVtdWxhdG9yXCI6IFwiLi92YXJsZXQtdG91Y2gtZW11bGF0b3IuanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=)

```html
<button class="var-button var--box var-button--mini var--inline-flex var-button--primary var-elevation--2" style="overflow: hidden; z-index: 1;">
  <div class="var-loading var-button__loading" var-button-cover="">
    <!--v-if-->
    <div class="var--box var-loading__body">
      <div class="var-loading__circle">
        <span class="var-loading__circle-block var-loading__circle-block--normal" style="width: 24px; height: 24px; color: currentcolor;">
          <svg viewBox="25 25 50 50"><circle cx="50" cy="50" r="20" fill="none"></circle></svg>
        </span>
      </div>
      <!--v-if--><!--v-if--><!--v-if--><!--v-if--><!--v-if-->
    </div>
  </div>
  <div class="var-button__content var-button--hidden"> 加载状态 </div>
</button>
```
看渲染结果：
1. `loading`图标的`class`是否应该是`var-loading__circle-block--mini`，而不是`var-loading__circle-block--normal`
2. `loading`有个行内样式，定义了大小`width`和`height`，覆盖了`class`中的样式
3. `var-loading`这个`class`，定义了四种大小的css变量，可是`var-loading__circle-block--normal`却没有用，是重新直接定义的`width`和`height`

   ```css
   .var-loading {
    --loading-normal-width: 50px;
    --loading-normal-height: calc(var(--font-size-md) + 2px);
    --loading-large-width: 64px;
    --loading-large-height: calc(var(--font-size-lg) + 2px);
    --loading-small-width: 36px;
    --loading-small-height: calc(var(--font-size-sm) + 2px);
    --loading-mini-width: 22px;
    --loading-mini-height: calc(var(--font-size-xs) + 2px);
    position: relative;
   }
   ```

**Comment by BeADre** [comment]
> loading图标的class是否应该是var-loading__circle-block--mini，而不是var-loading__circle-block--normal

loading图标的大小是由`loading-size`属性控制

> loading有个行内样式，定义了大小width和height，覆盖了class中的样式 
> var-loading这个class，定义了四种大小的css变量，可是var-loading__circle-block--normal却没有用，是重新直接定义的width和height

行内width和height是当设置`loading-radius`时覆盖，而当前是button错误的添加了一个属性默认值导致

如果你要设置mini类型的按钮，可以如下设置（发布新版本后生效）
```html
<var-button loading size="mini" loading-size="mini" type="primary">
  加载状态
</var-button>
```
