### ISSUE TITLE
The button style is not displayed as expected on the official website, and there is no highlight fluctuation effect.

### ISSUE THREAD

**Issue by anzhiyu-c** [varletjs/varlet#765]
# About `styles` 🛠️

The button style is not displayed as expected on the official website, and there is no highlight fluctuation effect.

The following is the smallest application I created through npm init vue@latest.

The warehouse address is here.：https://github.com/anzhiyu-c/varlet-deomo

**Comment by a145789** [comment]
Put your browser into mobile mode? `command + shift + M` or `ctrl + shift + M` in devtools

**Comment by anzhiyu-c** [comment]
> Put your browser into mobile mode? `command + shift + M` or `ctrl + shift + M` in devtools

Can there be a water wave effect only in mobile mode? 😭, I think I get it, because I'm trying to develop a smaller demo application that only needs to use the button style. Thank you.

**Comment by haoziqaq** [comment]
![image](https://user-images.githubusercontent.com/24223652/204506794-bd3c795d-b930-4582-926a-1763f3bbcea2.png)

see https://varlet.gitee.io/varlet-ui/#/en-US/browserAdaptation
