### ISSUE TITLE
组件事件设计缺陷

### ISSUE THREAD

**Issue by haiweilian** [varletjs/varlet#786]
### 现有实现

我简化一个示例，现在的组件把事件设计为了 `props` 通过 `props.onXxx` 调用存在很严重的问题。

```js
export default defineComponent({
  props: {
    onChange: {
      type: Function as PropType<(e: Event) => void>,
    },
  },
  setup() {
    call(props.onChange, e)
  }
})
```

### 出现的问题

当我去封装一个组件的时候，我在组件内部绑定了一个事件处理函数用于处理组件内部的状态，此时如果我在组件外部再绑定一次事件用于获取值，会出现警告和错误。

[复现链接 https://varlet.gitee.io/varlet-ui-playground](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDb21wSW5wdXQgZnJvbSAnLi9Db21wLnZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBjaGFuZ2UgPSAodmFsKSA9PiB7XG4gXHRjb25zb2xlLmxvZygn5bCB6KOF57uE5Lu2JywgdmFsKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENvbXBJbnB1dCBAY2hhbmdlPVwiY2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuY29uc3QgY2hhbmdlID0gKHZhbCkgPT4ge1xuIFx0Y29uc29sZS5sb2coJ+WGhemDqOe7hOS7ticsIHZhbClcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItaW5wdXQgcGxhY2Vob2xkZXI9XCLor7fovpPlhaXmlofmnKxcIiB2LW1vZGVsPVwidmFsdWVcIiBAY2hhbmdlPVwiY2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG4ifQ==)

![image](https://user-images.githubusercontent.com/34850199/209316218-ef3fb4c9-c185-4be9-b8cc-425050729285.png)

### 产生的原因

首先这是 vue 的特性。组件的 atrrs 是会继承到子组件的，并且和组件 props 合并过程中遵循 [mergeProps](https://cn.vuejs.org/api/render-function.html#mergeprops) 多个相同的 events 会转换成数组。所以此时类型是数组所以会出现警告，由于是数组所以在调用的时候不是函数出现错误。

### 解决方案

**基于现有的改**

- `Function` 改为 `[Function, Array]` 解决警告。
- `call` 调用支持数组解决错误。

**遵循实现标准**

强烈建议使用官方的实现方式，不要丢失 vue 的特性。

- 使用 `emits(['change'])` 定义事件。
- 使用 `emit('change')` 派发事件。

**Comment by haoziqaq** [comment]
这是我们的已知问题，将近一年时间里我们不确定是否需要支持多个监听器的使用方式。
我们倾向于用户的组件清楚的声明了 emits，就像下面这样。

[链接](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDb21wSW5wdXQgZnJvbSAnLi9Db21wLnZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBjaGFuZ2UgPSAodmFsKSA9PiB7XG4gXHRjb25zb2xlLmxvZygn5bCB6KOF57uE5Lu2JywgdmFsKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPENvbXBJbnB1dCBAY2hhbmdlPVwiY2hhbmdlXCIgLz5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4iLCJDb21wLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIGRlZmluZUVtaXRzIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBlbWl0ID0gZGVmaW5lRW1pdHMoWydjaGFuZ2UnXSlcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBjaGFuZ2UgPSAodmFsKSA9PiB7XG4gXHRlbWl0KCdjaGFuZ2UnLCB2YWwpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8dmFyLWlucHV0IHBsYWNlaG9sZGVyPVwi6K+36L6T5YWl5paH5pysXCIgdi1tb2RlbD1cInZhbHVlXCIgQGNoYW5nZT1cImNoYW5nZVwiIC8+XG48L3RlbXBsYXRlPlxuIn0=)

不过你提到的不去丢失 vue 本身的特性，这一点我们也很赞同，但是我们还是不倾向于使用 defineEmits 的官方用法。
我们倾向于您提到的 `基于现有的改`。原因是我们认为 props.onXXX() 的方式更加灵活，更加贴近我们的代码风格。
首先函数调用对于类型提示很友好，并且可以通过处理监听器的返回值，更方便的做一些特性。

我们会在接下来的时间，慢慢改进这个问题。也欢迎你帮助我们。

**Comment by haiweilian** [comment]
改动确实有纠结的地方，比如声明为数组会不会造成误解？有处理返回值的地方如果是数组怎么处理？

我现在是可以在代码中单独处理。如果你们讨论过后决定更改，希望能有一个好的解决方案。

**Comment by haoziqaq** [comment]
我们已经确定了修改路线，会逐步去应用到各个组件，以不破坏目前的组件行为为标准。

**Comment by haoziqaq** [comment]
感谢反馈～
