### ISSUE TITLE
[Icon] 图标命名空间自动追加 `--set` 导致对应不上

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#788]
# Bug report 🐞

`Icon` 传入的 `namespace` 会自动追加 `--set` 后缀，导致项目内的字体图标无法对应上。
## Version & Environment

- `vue@latest`
- `@varlet/ui@latest`

## Expectation

正常显示图标，移除侵入性的命名空间更改。

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/53589602/209556291-d050d851-e217-4579-887d-976a9d43a4c2.png)

**Comment by haoziqaq** [comment]
`@varlet/ui@2.4.3-alpha.1672073838506` alpha 版本提供了兼容了两种使用方式，将会在下一个修订版本发布。
