### ISSUE TITLE
projects 问题中的 修改中英文中的空格问题

### ISSUE THREAD

**Issue by xzqyun** [varletjs/varlet#804]
# About `docs`
https://github.com/varletjs/varlet/projects/4#card-74336815

这个问题中的这个句号问题要不要统一

**Comment by haoziqaq** [comment]
是需要的，我们的文档中还存有很多类似问题，如中西文排版的空格问题，中英文符号问题，以及某些文档一句话结束但是没写句号的问题。

**Comment by wegi8** [comment]
PR Welcome
