### ISSUE TITLE
表单校验成功后报错

### ISSUE THREAD

**Issue by FeiFanLiang** [varletjs/varlet#807]
# Bug report 🐞

## Version & Environment
v2.5.0
## Expectation
表单在成功通过验证后,控制台报错无法正常进行提交。

![image](https://user-images.githubusercontent.com/30872365/210260977-5060f3a1-d7c7-4ad3-978d-3589652872d1.png)

debugger结果如图，此时errorindex值为-1,进行后续判断直接报错。

**Comment by FeiFanLiang** [comment]
目前回退到2.4.2版本正常工作，判断是新增加的滚动到表单报错项目的新feature导致的bug

**Comment by haoziqaq** [comment]
已修复，感谢反馈，升级版本 2.5.1
