### ISSUE TITLE
[Menu] 菜单列表增加 `menu-width` 属性

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#809]
# Feature request 🚀

### Expected:

- 菜单组件增加 `menu-width` 属性，设置列表的容器元素宽度
- 菜单组件支持初始化时为列表容器元素设置最小宽度为组件元素实际宽度

### Examples:

```html
<VarMenu
  style="width: 100%"
  placement="bottom"
>
  <VarButton
    :block="true"
    color="#fff"
  >
    状态
  </VarButton>

  <template #menu>
    <VarCell>未开始</VarCell>
    <VarCell>进行中</VarCell>
  </template>
</VarMenu>
```

### Others:

![image](https://user-images.githubusercontent.com/53589602/210471181-8f5d8da9-5b7b-4fb7-a579-7082d3e80668.png)

**Comment by haoziqaq** [comment]
https://varlet.gitee.io/varlet-ui-playground/?initialTheme=dark#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dmFyLW1lbnU+XG4gICAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIj7ln7rmnKzkvb/nlKg8L3Zhci1idXR0b24+XG4gICAgXG4gICAgPHRlbXBsYXRlICNtZW51PlxuICAgICAgPGRpdiBzdHlsZT1cIndpZHRoOiAzMDBweFwiPlxuICAgICAgICA8dmFyLWNlbGw+6I+c5Y2V6aG5PC92YXItY2VsbD5cbiAgICAgIFx0PHZhci1jZWxsPuiPnOWNlemhuTwvdmFyLWNlbGw+XG4gICAgICBcdDx2YXItY2VsbD7oj5zljZXpobk8L3Zhci1jZWxsPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC92YXItbWVudT5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==

**Comment by haoziqaq** [comment]
[参考这里](https://varlet.gitee.io/varlet-ui-playground/?initialTheme=dark#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dmFyLW1lbnU+XG4gICAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIj7ln7rmnKzkvb/nlKg8L3Zhci1idXR0b24+XG4gICAgXG4gICAgPHRlbXBsYXRlICNtZW51PlxuICAgICAgPGRpdiBzdHlsZT1cIndpZHRoOiAzMDBweFwiPlxuICAgICAgICA8dmFyLWNlbGw+6I+c5Y2V6aG5PC92YXItY2VsbD5cbiAgICAgIFx0PHZhci1jZWxsPuiPnOWNlemhuTwvdmFyLWNlbGw+XG4gICAgICBcdDx2YXItY2VsbD7oj5zljZXpobk8L3Zhci1jZWxsPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC92YXItbWVudT5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)

**Comment by haoziqaq** [comment]
菜单和触发器等宽这个特性我们后续会考虑加上，感谢反馈～

**Comment by haoziqaq** [comment]
同时欢迎 pr～

**Comment by l246804** [comment]
> [参考这里](https://varlet.gitee.io/varlet-ui-playground/?initialTheme=dark#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8dmFyLW1lbnU+XG4gICAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIj7ln7rmnKzkvb/nlKg8L3Zhci1idXR0b24+XG4gICAgXG4gICAgPHRlbXBsYXRlICNtZW51PlxuICAgICAgPGRpdiBzdHlsZT1cIndpZHRoOiAzMDBweFwiPlxuICAgICAgICA8dmFyLWNlbGw+6I+c5Y2V6aG5PC92YXItY2VsbD5cbiAgICAgIFx0PHZhci1jZWxsPuiPnOWNlemhuTwvdmFyLWNlbGw+XG4gICAgICBcdDx2YXItY2VsbD7oj5zljZXpobk8L3Zhci1jZWxsPlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC92YXItbWVudT5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5Db250ZXh0LnRvdWNobW92ZUZvcmJpZCA9IGZhbHNlXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)

我期望的是列表容器宽度和 `Menu` 根元素等宽，暂时是通过额外的 `hook` 实现的，期望能类似 `Select` 组件那种在打开时获取实际宽度值。

![image](https://user-images.githubusercontent.com/53589602/210491495-c7fab763-fe12-428a-810b-c1eb662a479f.png)

**Comment by haoziqaq** [comment]
> * 菜单组件增加 `menu-width` 属性，设置列表的容器元素宽度

这个需求参考我给出的 playground 地址

> * 菜单组件支持初始化时为列表容器元素设置最小宽度为组件元素实际宽度

这个我们后面会加一个 prop，使菜单和触发器等宽

**Comment by haoziqaq** [comment]
> * 菜单组件增加 `menu-width` 属性，设置列表的容器元素宽度

这个需求参考我给出的 playground 地址

> * 菜单组件支持初始化时为列表容器元素设置最小宽度为组件元素实际宽度

这个我们后面会加一个 prop，使菜单和触发器等宽

**Comment by l246804** [comment]
ok

**Comment by haoziqaq** [comment]
v2.5.3
