### ISSUE TITLE
[Button] 按钮增加 `square` 属性

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#810]
# Feature request 🚀

### Expected:

- 按钮增加 `square` 属性，项目中容易存在无圆角按钮，期望组件能支持属性设置

### Examples:

```js
<VarButton
    :block="true"
    color="#fff"
    :square="true"
  >
    状态
  </VarButton>
```

### Others:

![image](https://user-images.githubusercontent.com/53589602/210471787-7cd881bc-78cb-42e2-b7d2-23e3adc554ac.png)

**Comment by haoziqaq** [comment]
这个推荐是使用样式定制去实现，增加一个 prop 个人感觉不是很值得。 
![image](https://user-images.githubusercontent.com/24223652/210479151-54d6b13c-4e0e-4602-b7fd-47294219074f.png)

**Comment by l246804** [comment]
目前是定义了全局类样式，在需要时设置，如果 `square` 属性不推荐，是否可以增加 `radius` 属性更恰当呢？

**Comment by haoziqaq** [comment]
一般一个应用的按钮圆角都是统一的，毕竟是有设计规范在的。很少会出现一会儿有圆角一会儿没圆角的情况。如果真的出现这种场景，可以使用 style-provider 组件进行范围定制。
```html
<var-button style="border-radius: 0">默认按钮</var-button>
<var-button style="--button-border-radius: 0">默认按钮</var-button>
```
这样的写法也是 ok 的。`radius` 属性感觉不是必须的。
