### ISSUE TITLE
[PullRefresh] 下拉刷新增加 target 属性

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#811]
# Feature request 🚀

### Expected:

- 下拉刷新增加同 `BackTop` 组件的 `target` 属性，用于指定需要判定允许下拉刷新的目标元素

### Examples:

```js
<VarPullRefresh target=".pull-refresh-box">
    <div class="pull-refresh-box"></div>
</VarPullRefresh>
```

### Others:

由于 App 的页面需要统一定义布局组件，支持路由配置开启下拉刷新，但是无法指定判定元素导致错误时机进行了刷新。

![image](https://user-images.githubusercontent.com/53589602/210530581-bc930e2a-85de-42a0-9286-101b4d75db17.png)

![image](https://user-images.githubusercontent.com/53589602/210530671-92207e8e-544e-46cf-ba4d-db6a3c59dd10.png)

**Comment by BeADre** [comment]
> 支持路由配置开启下拉刷新，但是无法指定判定元素导致错误时机进行了刷新

没太能理解你的意思

**Comment by l246804** [comment]
目前的 `PullRefresh` 是根据组件根元素滚动来判定是否需要下拉刷新，但是一般 `App` 内统一封装的组件里面想包含 `PullRefresh` 组件，但是页面内的元素可能不是由 `PullRefresh` 组件的根元素引起滚动的，所以希望能提供 `target` 属性来指定需要进行判定的某个容器元素。

**Comment by l246804** [comment]
如同 `BackTop` 组件提供了 `target` 属性一样。

![image](https://user-images.githubusercontent.com/53589602/210681901-aa7d8278-f6e1-4718-b5f4-5f34e87446e6.png)

**Comment by BeADre** [comment]
你意思是你的布局组件是一个整体 然后你想为布局组件里面的一个子组件添加`PullRefresh` 是吧？

**Comment by l246804** [comment]
是的，布局组件里面包含了 `PullRefresh`、`BackTop` 这些功能，目前 `BackTop` 拥有 `target` 可以指定目标滚动元素，所以希望 `PullRefresh` 也支持。

**Comment by BeADre** [comment]
我看了一下，`PullRefresh`组件目前不太好支持`target`属性，因为所有的事件以及那个下拉的状态按钮都是放在下拉根组件的 似乎没有太好的办法直接过渡到`target`的元素上

**Comment by l246804** [comment]
并不是指所有事件及下拉，增加的 `target` 适用于判定的，目前是基于 `PullRefresh` 的根元素判定 `scrollTop`，只需要支持根据 `target` 判定就可以了，其他的状态按钮都还是原位。

**Comment by l246804** [comment]
主要用于类似这里的判定，并非更改其他事件和位置。

![image](https://user-images.githubusercontent.com/53589602/210691880-5ee219df-744f-4bd6-bc8b-7c96de18452d.png)

**Comment by l246804** [comment]
现在获取 `scrollTop` 是基于 `PullRefresh` 根元素的，所以希望能支持传入 `target` 来判定是否应该进入下拉状态。
