### ISSUE TITLE
我在nwjs+weston做触摸屏应用的时候,滑块会很卡

### ISSUE THREAD

**Issue by huyanyou** [varletjs/varlet#812]
# Bug report 🐞

## Version & Environment
nwjs+vue3+weston
## Expectation
我在nwjs+weston做触摸屏应用的时候,滑块会很卡,但是触摸滑块后手指移出滑块再滑动的话就不会卡,我改了滑块的触摸范围,和高度,不知道是不是由于这个 原因造成的

**Comment by haoziqaq** [comment]
方便的话可以提供一个最小化可复现的 demo，帮助我们排查问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月5日(周四) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] 我在nwjs+weston做触摸屏应用的时候,滑块会很卡 (Issue #812)




 
Bug report 🐞
 
Version &amp; Environment
 
nwjs+vue3+weston
 
Expectation
 
我在nwjs+weston做触摸屏应用的时候,滑块会很卡,但是触摸滑块后手指移出滑块再滑动的话就不会卡,我改了滑块的触摸范围,和高度,不知道是不是由于这个 原因造成的
 
Actual results (or Errors)

**Comment by huyanyou** [comment]
今天找了一下，之前的回滚版本不在，我发了邮箱
