### ISSUE TITLE
[PullRefresh] 下拉刷新判定时机异常

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#814]
# Bug report 🐞

当容器仅向下滚动少许距离时，此时上拉至顶不需要下拉刷新，由于当前的下拉刷新判定时机是滚动容器 `scrollTop` 为 `0`，导致命中下拉机制，且由于 `scrollTop` 大于 `0`，导致下拉动画快速过渡并无法取消。

## Version & Environment

- `@varlet/ui@latest`

## Expectation

当容器元素 `scrollTop` 不为 `0` 时，此次触摸滑动不应命中下拉机制，当 `scrollTop` 为 `0` 时允许命中下拉机制。

## Actual results (or Errors)

![229d2927-dc5f-4680-ae8d-d5a18b804dc9 (1)](https://user-images.githubusercontent.com/53589602/210723590-fa1de81a-93e9-417b-9233-3af2276744c1.gif)

**Comment by BeADre** [comment]
能给一个最小化可复现的 demo吗

**Comment by l246804** [comment]
操作流程：打开后，`f12` 开启手机模式，先滚动下列表，再向上拉至顶部。

[复现 demo](https://deez2i.csb.app/)

**Comment by BeADre** [comment]
ok 已复现
