### ISSUE TITLE
[Uploader] 上传组件的 `beforeRemove` 未接收到 `file` 对象

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#815]
# Bug report 🐞

上传组件的 `beforeRemove` 回调未接收到 `file` 对象，跟官网 `api` 不符。

## Version & Environment

- `@varlet/ui@latest`

## Expectation

能够正常接收待删除的文件对象。

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/53589602/210765140-bf3c2ee0-f4d8-4c7e-9903-5848cfd2be05.png)

![image](https://user-images.githubusercontent.com/53589602/210765343-ba55fced-948b-4531-b230-adc514c07595.png)

**Comment by haoziqaq** [comment]
@varlet/ui@2.5.5-alpha.1672917688708

**Comment by haoziqaq** [comment]
thx~
