### ISSUE TITLE
分页器的初始默认值始终为0

### ISSUE THREAD

**Issue by FeiFanLiang** [varletjs/varlet#820]
# Bug report 🐞
分页器绑定current为1时，初始默认也为0
## Version & Environment
2.5.4

## Expectation

![image](https://user-images.githubusercontent.com/30872365/210857832-e09f8fc6-b177-4f6e-8a47-b9317ea87e5b.png)
![image](https://user-images.githubusercontent.com/30872365/210857986-ec099cd2-3e55-4796-9163-79198d7b01f0.png)

**Comment by BeADre** [comment]
你上面代码中的`total`是0 但是UI截图是17？代码跟UI应该对不上吧， 麻烦提供一个最小化可复现的 demo

**Comment by FeiFanLiang** [comment]
> 你上面代码中的`total`是0 但是UI截图是17？代码跟UI应该对不上吧， 麻烦提供一个最小化可复现的 demo

https://codesandbox.io/s/quirky-browser-z5du27
total初始值为0，
在total值和current值变更后，current仍然为0
