### ISSUE TITLE
[ActionSheet] 自定义 `actions` 插槽无法触发 `onSelect`

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#822]
# Feature request 🚀

使用 `ActionSheet` 自定义 `actions` 插槽未暴露 `handleSelect` 方法，无法直接触发 `on-select` 事件，需自身单独处理，比较麻烦。

### Expected:

- `actions` 插槽暴露 `handleSelect` 方法

### Examples:

```vue
<VarActionSheet>
    <template #actions="{ handleSelect }">
        <div @click="handleSelect({ xxx })">123</div>
    </template>
</VarActionSheet>
```

**Comment by haoziqaq** [comment]
#actions 插槽默认提供了展示 action 列表的能力以及点击 action 触发 onSelect 事件的能力，如果你复写了 `actions 的内容`，按照组件的功能的职责来说，你也应该自己实现这些内容。还有就是当你复写了 #actions 插槽，让组件触发 onSelect 事件就变成了一件多余的事情了，也不推荐这么做，作用域插槽的参数主要还是传递一些该插槽依赖的数据内容，而不是插槽自己产生的数据内容。

**Comment by haoziqaq** [comment]
自己实现很可能就是如下代码

```html
<VarActionSheet>
    <template #actions>
        <div v-for="a in actions" :key="action.name" @click="handleSelect(a)">{{ a.name }} </div>
    </template>
</VarActionSheet>
```

本质上差别很小

**Comment by haoziqaq** [comment]
这边是一个对比

```html
<VarActionSheet>
    <template #actions>
        <div v-for="action in actions" :key="action.name" @click="handleSelect(a)">{{ a.name }} </div>
    </template>
</VarActionSheet>
```

```html
<VarActionSheet @select="handleSelect">
    <template #actions="{ handleSelect }">
        <div v-for="action in actions" :key="action.name" @click="handleSelect">{{ a.name }} </div>
    </template>
</VarActionSheet>
```

本质上差别很小，可能还变的麻烦了。

**Comment by l246804** [comment]
目前的自定义插槽无法实现点击列表项关闭弹窗效果。

**Comment by haoziqaq** [comment]
尝试使用 `v-model:show` 试试呢～

**Comment by l246804** [comment]
其次列表容器的最大高度设置是无效的。

![image](https://user-images.githubusercontent.com/53589602/210985606-74aa515c-9fde-4b3b-9937-00ead35e5ec0.png)

![image](https://user-images.githubusercontent.com/53589602/210985739-2aa835d5-057e-4eaf-abcf-6c3d91d06c63.png)

**Comment by haoziqaq** [comment]
这个属性确实是没什么意义，可以删掉
