### ISSUE TITLE
[Button] 按钮没有原生 `type` 属性导致在 `form` 中会触发提交事件

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#825]
# Bug report 🐞

按钮没有设置原生 `type` 属性，在 `form` 标签下会触发提交事件，包括使用到 `VarButton` 的其他组件（VarDatePicker）。

## Version & Environment

- `@varlet/ui@latest`
- `vue@latest`

## Expectation

提供 `html-type` 属性允许设置按钮原生类型，且默认应为 `button`。

## Actual results (or Errors)

选择日期时触发了 `VanForm` 的提交事件，排查后是由 `button` 缺失 `type=button` 引起的。

![image](https://user-images.githubusercontent.com/53589602/211709293-6929a593-36df-4079-be94-7f2d5bb9e946.png)

**Comment by haoziqaq** [comment]
v2.6.1 `native-type`
