### ISSUE TITLE
[Overlay] 使用 `unplugin-vue-components` 插件自动导入遮罩层后控制台警告

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#826]
# Bug report 🐞

使用 `unplugin-vue-components` 插件自动导入遮罩层后使用无效，且控制台警告。

## Expectation

正常使用。

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/53589602/211727667-969b86dc-749a-4362-83df-289cb1d71bf3.png)

![image](https://user-images.githubusercontent.com/53589602/211727731-5d8ff460-e2a6-48db-b226-1b120fcd440a.png)

**Comment by haoziqaq** [comment]
v2.6.1
