### ISSUE TITLE
[Dialog] 增加 Api 调用默认配置项

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#830]
# Feature request 🚀

### Expected:

`Dialog`、`Snackbar` 作为 `Api` 使用时需传入一些参数进行特殊显示，但部分参数整个项目基本都是一致的，希望能提供属性进行全局配置。

### Examples:

```ts
// main.ts
import { Dialog, Snackbar } from '@varlet/ui'

Dialog.config.title = '提示'
Dialog.config.confirmButtonText = '是'
Dialog.config.cancelButtonText = '否'

Snackbar.config.duration = 3000
```

### Others:

仅针对 `Api` 形式，调用时若部分参数为 `null`、`undefined`，则获取是否存在全局配置，否则为默认值。

**Comment by haoziqaq** [comment]
感觉用国际化覆盖文本也很方便，如果只是配置组件的外观的话。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月13日(周五) 上午9:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [varletjs/varlet] [Dialog] 增加 Api 调用默认配置项 (Issue #830)




 
Feature request 🚀
 
Expected:
 
Dialog、Snackbar 作为 Api 使用时需传入一些参数进行特殊显示，但部分参数整个项目基本都是一致的，希望能提供属性进行全局配置。
 
Examples:
 // main.ts import { Dialog, Snackbar } from ***@***.***/ui' Dialog.config.title = '提示' Dialog.config.confirmButtonText = '是' Dialog.config.cancelButtonText = '否' Snackbar.config.duration = 3000
 
Programme:
 
Others:
 
仅针对 Api 形式，调用时若部分参数为 null、undefined，则获取是否存在全局配置，否则为默认值。

**Comment by l246804** [comment]
不仅仅是国际化的问题，我只是举例子，例如默认时长，默认标题，默认的一些其他配置，这些基本上整个项目大体都是一致的，如果 `UI` 库方面默认的不满足，在没有提供可配置的前提下，就得额外单独封装，这样我觉得很没有必要，如果能直接提供一个配置入口是最理想的！

**Comment by haoziqaq** [comment]
如果是这样的话，似乎直接把所有的组件props 暴露给用户就解决问题了，二次封装也比较方便，也可以在项目初始化的时候对组件的 props 进行修改（虽然不提倡，但是有用。）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月13日(周五) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] [Dialog] 增加 Api 调用默认配置项 (Issue #830)




 
不仅仅是国际化的问题，我只是举例子，例如默认时长，默认标题，默认的一些其他配置，这些基本上整个项目大体都是一致的，如果 UI 库方面默认的不满足，在没有提供可配置的前提下，就得额外单独封装，这样我觉得很没有必要，如果能直接提供一个配置入口是最理想的！

**Comment by l246804** [comment]
并不是所有 `props` 都合适，理论上这样是能快速解决问题，但实际上你也说了这种不提倡，一般只暴露部分即可。

**Comment by l246804** [comment]
主要在于 `api` 方式和 `template` 方式两者是有区别的，`api` 调用就是为了方便快捷，否则肯定会使用 `template` 的。

**Comment by l246804** [comment]
其次就是项目使用 `unplugin-auto-import` 插件，`api` 的引入可以被插件自动识别，这个时候二次封装再去使用就失去了自动引入的意义。

**Comment by haoziqaq** [comment]
需求大致了解了，后面会给所有函数式组件增加 `setDefaultOptions` 和 `resetDefaultOptions` 方法，也欢迎 pr～

**Comment by haoziqaq** [comment]
props 也会在 2.7.x 版本进行暴露，便于对组件的二次封装。

**Comment by wegi8** [comment]
我理解，要不要向外暴露一个Provider这种东西

**Comment by haoziqaq** [comment]
不用，Provider 无法影响组件函数调用方式的行为，只可能影响组件树上的每个组件的行为。
