### ISSUE TITLE
[Swip] 控制台报空指针错误

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#834]
# Bug report 🐞

由于在移动端，`VarTabsItems` 页面会缓存，在重新激活缓存页时偶发的宽度计算异常，通过转场动画结束主动触发 `resize` 事件进行处理，此时页面离开时会导致元素为空。

## Version & Environment

- `@varlet/ui@latest`

## Expectation

控制台不报错。

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/53589602/212594349-aa9e701a-3b28-435b-b93a-12bb84443701.png)

![image](https://user-images.githubusercontent.com/53589602/212594012-4accf0ab-70be-49c8-9857-a2dc6ffd1e32.png)

**Comment by haoziqaq** [comment]
烦请提供一个最小化可复现的案例



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 16, 2023 11:47 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [varletjs/varlet] [Swip]  (Issue #834)




 
Bug report 🐞
 
由于在移动端，VarTabsItems 页面会缓存，在重新激活缓存页时偶发的宽度计算异常，通过转场动画结束主动触发 resize 事件进行处理，此时页面离开时会导致元素为空。
 
Version &amp; Environment
  
@***@***.***
  
Expectation
 
控制台不报错。
 
Actual results (or Errors)

**Comment by l246804** [comment]
开发没遇到过计算失败的情况，只有`uni-webview`构建后有这种情况。

**Comment by haoziqaq** [comment]
应该是在离开页面的时候组件元素被卸载了，这时候调 `resize` 就不合适了。我们可以优化一下这部分的逻辑，去避免一些情况调用 `resize` 可能产生的控制台报错。
