### ISSUE TITLE
swipe tabs 在ios16上卡顿

### ISSUE THREAD

**Issue by TurnerXi** [varletjs/varlet#838]
# Bug report 🐞
swipe tabs 在ios16上卡顿

## Version & Environment
version: 官网版本
env: iphone14pro  ios16.2

## Expectation
流畅滑动

## Actual results (or Errors)
https://user-images.githubusercontent.com/25336287/213128893-4f5d858a-083e-48d3-94ca-4a5e96a4cdf5.mp4

**Comment by haoziqaq** [comment]
什么浏览器？

**Comment by BeADre** [comment]
https://user-images.githubusercontent.com/34639100/213136841-a6c51a1f-ac37-4765-9af5-3b6c1d66121a.mp4

iphone13pro ios16.2 不能复现

**Comment by TurnerXi** [comment]
> 什么浏览器？

chrome

**Comment by haoziqaq** [comment]
iphone13pro chorme 没能复现

**Comment by haoziqaq** [comment]
难不成是 iphone14pro chorme 的问题。 这个我们暂时找不到机型。

**Comment by haoziqaq** [comment]
我们继续找寻一下机型，如果我们找到机型，我们会尝试去复现一下问题。也不能排除是浏览器的渲染 bug，我们以前遇到过类似的问题，过了几天更新了浏览器版本问题就消失了。

**Comment by haoziqaq** [comment]
也欢迎你来帮忙调试一下，看看问题出在哪里

**Comment by TurnerXi** [comment]
> 也欢迎你来帮忙调试一下，看看问题出在哪里

看过代码了  没看出什么问题  应该是14pro chrome的问题   
网上看了下ios chrome可能会出现这个问题
issue我关了哈  感谢非常及时的回复

顺便感谢下团队，框架做的非常棒，用起来很舒服:+1::+1::+1:
希望能够加入 290944015@qq.com

**Comment by haoziqaq** [comment]
加我微信吧 qh357229046
