### ISSUE TITLE
varlet-cli 引入ivew UI， ivew中的组件icon 不显示，是什么问题？

### ISSUE THREAD

**Issue by skyLoveSnap** [varletjs/varlet#842]
# Bug report 🐞

**Comment by haoziqaq** [comment]
方便提供一个可复现问题的仓库吗？

**Comment by skyLoveSnap** [comment]
css中指定了字体路径，但是访问的时候带着?v=3.0.0就报404，不带?v=3.0.0图标就可以正常显示。而且在其他项目中请求字体资源时都不带?v=3.0.0
<img width="768" alt="image" src="https://user-images.githubusercontent.com/40157361/215964254-9c915b4a-f276-43a2-bf71-a5b256d5eb4b.png">
![image](https://user-images.githubusercontent.com/40157361/215964272-c9e64995-b605-4ae7-a788-baeea7da6f52.png)
我想过滤掉这个版本号，这应该该在哪里设置呢？

**Comment by haoziqaq** [comment]
这应该是 vite 的行为， vite 服务器会把 ionicons.woff2?v=3.0.0 当成一个完整的文件名去处理，而不会当成 url 的 params

**Comment by haoziqaq** [comment]
如果可以的话，尽量把版本号作为文件的一部分，比如 ionicons.3.0.0.woff2 这样的，可能对 vite 更友好一些

**Comment by skyLoveSnap** [comment]
有什么方法可以过滤掉这个版本号吗？比如配置正则等方式，但是我不知道在哪去配置

**Comment by haoziqaq** [comment]
这个版本号来自哪里？ 是 iview 的么？

**Comment by haoziqaq** [comment]
理论上可以通过 vite 插件去过滤，但是不是很优雅。暂时没想到很好的方式，我可以帮你进一步定位问题。

**Comment by skyLoveSnap** [comment]
是来自ivew的，通过 vite 插件怎么过滤？谢谢

**Comment by haoziqaq** [comment]
iview 配合 vite 不会出问题么？

**Comment by haoziqaq** [comment]
是 iview 的什么版本

**Comment by haoziqaq** [comment]
把依赖罗列一下，我空了看一下

**Comment by skyLoveSnap** [comment]
其他项目vite  + ivew + vue3的 不会出现问题， "view-ui-plus": "^1.3.1"

**Comment by skyLoveSnap** [comment]
<img width="457" alt="企业微信截图_64154496-786c-4fa8-af95-e8ffcbff4279" src="https://user-images.githubusercontent.com/40157361/215973691-303cf67c-d2d4-4d9f-af07-7699d30a44e2.png">
"dependencies": {
    "@element-plus/icons-vue": "^2.0.9",
    "element-plus": "^2.2.17",
    "@varlet/ui": "^2.6.2",
    "dayjs": "^1.11.5",
    "glob": "^8.0.3",
    "less": "^4.1.3",
    "sass": "^1.54.9",
    "scss": "^0.2.4",
    "view-ui-plus": "^1.3.1"
  }
非常感谢

**Comment by haoziqaq** [comment]
没有办法复现这个问题， 你是如何引入 iview 的？

**Comment by haoziqaq** [comment]
嗯，客气了，需要帮助在这个 issue 留言就好，我先关了，感觉和 cli 关系不是特别大。
