### ISSUE TITLE
Snackbar多例模式遇上其他异步加载需求时会影响异步加载

### ISSUE THREAD

**Issue by ymTonny** [varletjs/varlet#844]
# Feature request 🚀

### Expected:
`Snackbar`开启多例模式，若同时有其他异步加载需求时，还需在异步加载需求处显示调用`allowMultiple(false)`关闭多例模式才行

### Examples:
[示例](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPSd0cyc+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBTbmFja2JhciB9IGZyb20gJ0B2YXJsZXQvdWknXG5cbmZ1bmN0aW9uIG9wZW5NdWx0aXBsZSgpIHtcblx0U25hY2tiYXIuYWxsb3dNdWx0aXBsZSh0cnVlKVxuIFxuICBjb25zdCBzbmFja2JhcjEgPSBTbmFja2Jhci5sb2FkaW5nKCdTbmFja2JhciAxJyk7XG4gIFNuYWNrYmFyLnN1Y2Nlc3MoJ1NuYWNrYmFyIDInKTtcblxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBzbmFja2JhcjEuY2xlYXIoKVxuICB9LCAxMDAwKVxufVxuXG5jb25zdCBzaG93ID0gcmVmKGZhbHNlKVxuY29uc3QgYWN0aW9ucyA9IHtcbiAgY29uZmlybTogKCkgPT4gU25hY2tiYXIuc3VjY2VzcygnY29uZmlybScpLFxuICBjYW5jZWw6ICgpID0+IFNuYWNrYmFyLmVycm9yKCdjYW5jZWwnKSxcbiAgY2xvc2U6ICgpID0+IFNuYWNrYmFyLmluZm8oJ2Nsb3NlJyksXG59XG5mdW5jdGlvbiBvbkJlZm9yZUNsb3NlKGFjdGlvbiwgZG9uZSkge1xuICBjb25zdCBzbmFjayA9IFNuYWNrYmFyLmxvYWRpbmcoJ0FzeW5jaHJvbm91cyBzaHV0ZG93biBpbiBwcm9ncmVzcycpXG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGFjdGlvbnNbYWN0aW9uXSgpXG4gICAgZG9uZSgpXG4gICB9LCAxMDAwKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIiBibG9jayBAY2xpY2s9XCJvcGVuTXVsdGlwbGVcIj7lpJrkvovmqKHlvI88L3Zhci1idXR0b24+XG4gIDx2YXItYnV0dG9uIHR5cGU9XCJ3YXJuaW5nXCIgYmxvY2sgQGNsaWNrPVwic2hvdyA9IHRydWVcIj7lvILmraXlhbPpl608L3Zhci1idXR0b24+XG4gIDx2YXItZGlhbG9nXG4gICAgdGl0bGU9XCLlhbDkuq3luo9cIlxuICAgIG1lc3NhZ2U9XCLlhbDkuq3kuLTluJYg6KGM5Lmm5aaC6KGM5LqR5rWB5rC0XCJcbiAgICB2LW1vZGVsOnNob3c9XCJzaG93XCJcbiAgICBAYmVmb3JlLWNsb3NlPVwib25CZWZvcmVDbG9zZVwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiUGxheWdyb3VuZC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBpbnN0YWxsVmFybGV0VUkgfSBmcm9tICcuL3ZhcmxldC1yZXBsLXBsdWdpbi5qcydcblxuaW5zdGFsbFZhcmxldFVJKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4yOS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpXCI6IFwiLi92YXJsZXQuZXNtLmpzXCIsXG4gICAgXCJAdmFybGV0L3RvdWNoLWVtdWxhdG9yXCI6IFwiLi92YXJsZXQtdG91Y2gtZW11bGF0b3IuanNcIixcbiAgICBcIkB2YXJsZXQvdWkvanNvbi9hcmVhLmpzb25cIjogXCIuL3ZhcmxldC1hcmVhLmpzXCJcbiAgfVxufSIsInZhcmxldC1yZXBsLXBsdWdpbi5qcyI6ImltcG9ydCBWYXJsZXRVSSwgeyBDb250ZXh0IH0gZnJvbSAnQHZhcmxldC91aSdcbmltcG9ydCAnQHZhcmxldC90b3VjaC1lbXVsYXRvcidcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxuQ29udGV4dC50b3VjaG1vdmVGb3JiaWQgPSBmYWxzZVxuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=)
### Programme:
不知道在`Snackbar`组件销毁时，验证如果是多例模式就恢复`isAllowMultiple`的默认值方案是否可行，这样在其他单例模式下就不需要用户考虑取消多例模式
### Others:
同时在官方文档处，先点击`snackbar`中的多例模式，再点击`Dialog`中的异步加载，此时`Dialog`里表现为多例模式

**Comment by BeADre** [comment]
这个我觉得是没有问题的 因为单例或者多例本身就是属于全局的

**Comment by BeADre** [comment]
> 不知道在Snackbar组件销毁时，验证如果是多例模式就恢复isAllowMultiple的默认值方案是否可行，这样在其他单例模式下就不需要用户考虑取消多例模式

在用户默认需要全局开启多例模式的情况下 这就是一个bug

**Comment by ymTonny** [comment]
> 这个我觉得是没有问题的因为单个或者多个例子本身就是属于全局的

如果是全局的概念的话，两者并存时就意味着分别要调用`allowMultiple(true)`和`allowMutiple(false)`。是这样的话官网文档上，先点击`snackbar`中的多例模式，再点击`Dialog`中的异步加载，此时`Dialog`的loading不会消失可以修复下😀

**Comment by ymTonny** [comment]
> > 不知道在Snackbar组件销毁时，验证如果是多例模式就恢复isAllowMultiple的默认值方案是否可行，这样在其他单例模式下就不需要用户考虑取消多例模式
> 
> 在用户默认需要全局开启多例模式的情况下 这就是一个bug

确实确实，没有细致的思考😂

**Comment by haoziqaq** [comment]
我觉得文档的话，卸载的时候把副作用清理掉吧。减少一些疑惑，有时候文档挂着时间长了，自己都忘记自己在其他的页面干过什么了。
