### ISSUE TITLE
[Space] inline 模式时类名错误

### ISSUE THREAD

**Issue by l246804** [varletjs/varlet#872]
# About `styles` 🛠️

![image](https://user-images.githubusercontent.com/53589602/220586340-e95fb857-4bc9-484c-bd5e-695d7405ba3f.png)

![image](https://user-images.githubusercontent.com/53589602/220586464-d846fc76-2dab-4bb2-b570-8651a943c81f.png)

**Comment by qytayh** [comment]
感谢反馈，将在下个小版本中修复这个问题，请留意版本更新
