### ISSUE TITLE
pnpm bootstrap bug

### ISSUE THREAD

**Issue by Malcn** [varletjs/varlet#873]
# Bug report 🐞

## Version & Environment
varlet 2.8..3
node 16
pnpm 7.x

## Expectation
pnpm bootstrap 执行成功

## Actual results (or Errors)
<img width="902" alt="image" src="https://user-images.githubusercontent.com/20159170/220591442-220dadf2-3e1c-41fe-97ad-4873bb68cbf5.png">

**Comment by haoziqaq** [comment]
确认你的网络环境，如果安装依然不成功，考虑通过 pnpm 修改 sharp 的淘宝镜像



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 22, 2023 18:22 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [varletjs/varlet] pnpm bootstrap bug (Issue #873)




 
Bug report 🐞
 
Version &amp; Environment
 
varlet 2.8..3
 node 16
 pnpm 7.x
 
Expectation
 
pnpm bootstrap 执行成功
 
Actual results (or Errors)

**Comment by Malcn** [comment]
删除pnpm store缓存，然后换个源解决了

**Comment by haoziqaq** [comment]
之前组织内有人遇见相同问题，设置代理可以解决。



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 22, 2023 20:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [varletjs/varlet] pnpm bootstrap bug (Issue #873)




 
似乎是引入的 sharp 这个包有兼容性问题，在执行install脚本时出错
