### ISSUE TITLE
文档站点开发模式下，会重复引入公共样式

### ISSUE THREAD

**Issue by Malcn** [varletjs/varlet#874]
# Bug report 🐞
进入本地开发模式，组件内如果导入公共样式，会导致重复引用
pnpm bootstrap
cd packages/varlet-ui
pnpm run dev

![image](https://user-images.githubusercontent.com/20159170/220618358-e7717d4f-127c-45ac-b132-1189c8f10678.png)

## Version & Environment
varlet 2.8.3
## Expectation
公共样式只引入一次

**Comment by haoziqaq** [comment]
这个可以忽略，这是每个组件的基本样式，因为需要支持按需引入，每个组件都会引入基本样式文件，我们对 sfc 有特别的编译方式，样式引入语句是分散在各个 sfc 的 style 标签中的，可以理解为一种编译器限制。在组件库编译之后不会出现包尺寸问题。
