### ISSUE TITLE
输入框在移动端上输入会乱

### ISSUE THREAD

**Issue by Rosalindjuan** [varletjs/varlet#877]
# Bug report 🐞
在手机上测试时，我本地手机使用时会产生很多乱七八糟的字符
后使用官方的例子，输入框中输入内容后，会产生很多字符（打中文时）
## Version & Environment
"@varlet/ui": "^2.8.2"
## Expectation
![img_v2_f096ba3c-c173-4f85-849f-4a37caa6081g](https://user-images.githubusercontent.com/13193046/222360553-0f52e61e-f2e9-423e-9ab1-26287abd1f66.jpg)

**Comment by a145789** [comment]
可以描述的更详细点么？或者这个问题只在 ios 上会出现么？

**Comment by Rosalindjuan** [comment]
目前用ios是如此，还没试安卓机子呢，

**Comment by Rosalindjuan** [comment]
就是点击输入的时候，我用9宫格输入中文拼音的时候，他就是会把按键里面的字符一起带上去，就比较乱，
你们的预览页面里面也是一样

**Comment by Rosalindjuan** [comment]
找同事用了安卓机子，没有问题哈

**Comment by haoziqaq** [comment]
ios 版本、手机型号、浏览器提供一下，我们来验证一下～

**Comment by Rosalindjuan** [comment]
版本15.1 苹果8Plus  微信和safari,打开都如此

**Comment by haoziqaq** [comment]
已定位到问题，下个版本修复

**Comment by haoziqaq** [comment]
@varlet/ui@2.8.6-alpha.1677756540023
