### ISSUE TITLE
nuxt3使用dialog组件函数式调用无样式

### ISSUE THREAD

**Issue by wyx-lsy** [varletjs/varlet#878]
# Bug report 🐞
![1677833689543](https://user-images.githubusercontent.com/52925701/222676106-dd7be3e5-6b6a-4723-85de-6128eb652533.png)
![1677833712663](https://user-images.githubusercontent.com/52925701/222676199-e699c3ba-1711-4262-be5c-aa6600163ca9.png)

## Version & Environment
"nuxt": "npm:nuxt3@latest",
"@varlet/ui": "^2.8.5",

**Comment by wyx-lsy** [comment]
![1677833808863](https://user-images.githubusercontent.com/52925701/222676548-c76836ee-c0d9-400e-8463-4876e3e0c3a7.png)
tree-shaking没有检测到dialog使用，未引入样式，使用<var-dialog />组件时正常

**Comment by haoziqaq** [comment]
自动引入插件不支持这样的用法。 你可以尝试这样的用法

```
<script setup lang="ts">
function handleClick() {
  Dialog('Hello')
}
</script>

<template>
  <var-button type="primary" @click="handleClick">Say Hello</var-button>
</template>
```
