### ISSUE TITLE
icon support for custom animation class names

### ISSUE THREAD

**Issue by a145789** [varletjs/varlet#879]
# Feature request 🚀

### Expected:

https://github.com/varletjs/varlet/blob/195bf9b7d9c535d31b9e02a8238d781f93b5bb1f/packages/varlet-ui/src/icon/Icon.vue#L10

add `animation-class` api, maybe here you can allow the user to customize the effect of the animation

- No breaking changes

### Examples:

```html
 <var-icon name="github" :transition="7000" animation-class="any" />
```

**Comment by haoziqaq** [comment]
yes，would you wish make it ？



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 4, 2023 15:48 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [varletjs/varlet] icon support for custom animation class names(Issue #879)




 
Feature request 🚀
 
Expected:
 
https://github.com/varletjs/varlet/blob/195bf9b7d9c535d31b9e02a8238d781f93b5bb1f/packages/varlet-ui/src/icon/Icon.vue#L10
 
add animation-class api, maybe here you can allow the user to customize the effect of the animation
  
No breaking changes
  
Examples:
  <var-icon name="github" :transition="7000" animation-class="any" /&gt;
 
Programme:
 
Others:

**Comment by a145789** [comment]
yes

**Comment by haoziqaq** [comment]
👌



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 4, 2023 23:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [varletjs/varlet] icon support for custom animation class names(Issue #879)




 
yes

**Comment by haoziqaq** [comment]
good work!
