### ISSUE TITLE
在loding组件上使用了description属性后，type="wave"的话动画效果就消失

### ISSUE THREAD

**Issue by suzhenghui-sky** [varletjs/varlet#884]
# Bug report 🐞
在loding组件上使用了description属性后，type="wave"的话动画效果就消失
## Version & Environment
 "@varlet/ui": "^2.7.1",

**Comment by haoziqaq** [comment]
`description` 是配合插槽使用的，为了满足包裹内容时提示信息。

```
<script setup>
import { ref } from 'vue'

const loading = ref(false)
</script>

<template>
  <var-button @click="loading = !loading" style="margin-bottom: 8px">
    {{ loading ? '关闭' : '打开' }}
  </var-button>
  <var-loading description="LOADING" type="circle" :loading="loading">
    <var-card 
      title="介绍" 
      description="Varlet 是一个基于Vue3开发的 Material 风格移动端组件库，全面拥抱Vue3生态，由社区的小伙伴开发和维护。" 
    />
  </var-loading>
</template>
```

**Comment by suzhenghui-sky** [comment]
我是用了插入了东西，但是动画消失了。
<VarLoading :loading="true" type="wave" description="视频来">
    <div>hello world !</div>
  </VarLoading>
你可以试试

**Comment by haoziqaq** [comment]
可以提供一个playground地址



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月10日(周五) 下午2:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [varletjs/varlet] 在loding组件上使用了description属性后，type="wave"的话动画效果就消失 (Issue #884)




 
我是用了插入了东西，但是动画消失了。
 
 
hello world !

 
 你可以试试

**Comment by haoziqaq** [comment]
复现了 thx

**Comment by suzhenghui-sky** [comment]
这是我写demo库。https://gitee.com/jyjyjy28/copy-varlet

**Comment by haoziqaq** [comment]
感谢配合和反馈，是由于容器高度过小在 flex 中导致的坍缩，已在 `alpha.1678431541952` 中修复

**Comment by suzhenghui-sky** [comment]
是CSS代码写错的缘故嘛？是把height写成了margin-lef这个的缘故嘛？

**Comment by haoziqaq** [comment]
是组件库的问题，loading 使用了 flex，但是没考虑到这种容器高度远小于 loading 尺寸的情况。导致了 `flex shrink`
