### ISSUE TITLE
collapse animation optimization

### ISSUE THREAD

**Issue by little-alei** [varletjs/varlet#915]
# Bug report 🐞
首次展开偶发（概率较高）没有高度渐变动画，而是直接到了需要的高度
## Version & Environment
2.9.1 vue3 vite

**Comment by haoziqaq** [comment]
可以提供一个最小化 `demo` 或 [playground](https://varlet.gitee.io/varlet-ui-playground/)

**Comment by little-alei** [comment]
> 可以提供一个最小化 `demo` 或 [playground](https://varlet.gitee.io/varlet-ui-playground/)

我在playground中没能复现此问题，但是在安卓手机的网页中，总是能出现。这是[测试代码](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8dmFyLWNvbGxhcHNlIHYtbW9kZWw9XCJ2YWx1ZVwiIEBjaGFuZ2U9XCJjaGFuZ2VIYW5kbGVcIiA6b2Zmc2V0PVwiZmFsc2VcIj5cblx0XHQ8dmFyLWNvbGxhcHNlLWl0ZW0gbmFtZT1cIjFcIj5cblx0XHRcdDx0ZW1wbGF0ZSAjdGl0bGU+XG5cdFx0XHRcdDx2YXItaWNvbiBuYW1lPVwicGxheS1jaXJjbGUtb3V0bGluZVwiIC8+XG5cdFx0XHRcdOi/kOihjOS4reeahOmhueebrlxuXHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDxkaXYgc3R5bGU9XCJwYWRkaW5nOiAycHggMTBweFwiIHYtaWY9XCJydW5uaW5nLmxlbmd0aCAhPSAwXCI+XG5cdFx0XHRcdDxoNSB2LWZvcj1cImluZm8gaW4gcnVubmluZ1wiIDppbmZvPVwiaW5mb1wiIDprZXk9XCJpbmZvLmlkXCI+e3sgaW5mby5uYW1lIH19PC9oNT5cblx0XHRcdDwvZGl2PlxuXHRcdFx0PGRpdiBjbGFzcz1cImVtcHR5XCIgdi1pZj1cInJ1bm5pbmcubGVuZ3RoID09IDBcIj5cblx0XHRcdFx0PGltZyBzcmM9XCJodHRwczovL2ltZy55emNkbi5jbi92YW50L2N1c3RvbS1lbXB0eS1pbWFnZS5wbmdcIiBhbHQ9XCJcIiAvPlxuXHRcdFx0XHQ8cD7ku4DkuYjkuZ/msqHmnInlk6Y8L3A+XG5cdFx0XHQ8L2Rpdj5cblx0XHQ8L3Zhci1jb2xsYXBzZS1pdGVtPlxuXHRcdDx2YXItY29sbGFwc2UtaXRlbSBuYW1lPVwiMlwiPlxuXHRcdFx0PHRlbXBsYXRlICN0aXRsZT5cblx0XHRcdFx0PHZhci1pY29uIG5hbWU9XCJiZWxsXCIgLz5cblx0XHRcdFx05Lu75YqhXG5cdFx0XHQ8L3RlbXBsYXRlPlxuXHRcdFx0PGRpdiBzdHlsZT1cInBhZGRpbmc6IDJweCAxMHB4XCIgdi1pZj1cInRhc2subGVuZ3RoICE9IDBcIj5cblx0XHRcdFx0PGg0IHYtZm9yPVwiaW5mbyBpbiBydW5uaW5nXCIgOmluZm89XCJpbmZvXCIgOmtleT1cImluZm8uaWRcIj57eyBpbmZvLm5hbWUgfX08L2g0PlxuXHRcdFx0PC9kaXY+XG5cdFx0XHQ8ZGl2IGNsYXNzPVwiZW1wdHlcIiB2LWlmPVwidGFzay5sZW5ndGggPT0gMFwiPlxuXHRcdFx0XHQ8aW1nIHNyYz1cImh0dHBzOi8vaW1nLnl6Y2RuLmNuL3ZhbnQvY3VzdG9tLWVtcHR5LWltYWdlLnBuZ1wiIGFsdD1cIlwiIC8+XG5cdFx0XHRcdDxwPuS7gOS5iOS5n+ayoeacieWTpjwvcD5cblx0XHRcdDwvZGl2PlxuXHRcdDwvdmFyLWNvbGxhcHNlLWl0ZW0+XG5cdDwvdmFyLWNvbGxhcHNlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmludGVyZmFjZSBUYXNrIHtcblx0aWQ6IG51bWJlcjtcblx0bmFtZTogc3RyaW5nO1xufVxuY29uc3QgdmFsdWUgPSByZWYoW10pO1xuY29uc3QgcnVubmluZyA9IHJlZjxUYXNrW10+KFtdKTtcbmNvbnN0IHRhc2sgPSByZWY8VGFza1tdPihbXSk7XG5mdW5jdGlvbiBjaGFuZ2VIYW5kbGUodmFsOiBzdHJpbmdbXSkge1xuXHRpZiAodmFsLmluY2x1ZGVzKFwiMVwiKSkge1xuXHRcdHJ1bm5pbmcudmFsdWUucHVzaCh7XG5cdFx0XHRpZDogcnVubmluZy52YWx1ZS5sZW5ndGggKyAxLFxuXHRcdFx0bmFtZTogYHRlc3Qke3J1bm5pbmcudmFsdWUubGVuZ3RofWAsXG5cdFx0fSk7XG5cdH1cbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5lbXB0eSB7XG5cdGRpc3BsYXk6IGZsZXg7XG5cdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG4uZW1wdHkgaW1nIHtcblx0d2lkdGg6IDEwMHB4O1xuXHRoZWlnaHQ6IDEwMHB4O1xufVxuPC9zdHlsZT5cbiIsIlBsYXlncm91bmQudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiLi92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgaWYgKHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xhc3NMaXN0LmNvbnRhaW5zKCdkYXJrJykpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKFZhcmxldFVJLlRoZW1lcy5kYXJrKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKGRhdGEudmFsdWUgPT09ICdkYXJrJyA/IFZhcmxldFVJLlRoZW1lcy5kYXJrIDogbnVsbClcbiAgICB9XG4gIH0pXG5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoVmFybGV0VUkpXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBhcHBlbmRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnLi92YXJsZXQuY3NzJ1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn1cbiJ9)
[这个是演示的视频](https://user-images.githubusercontent.com/59299759/226287944-08689d1d-2307-4420-9b54-bc33d039e8a2.mp4)

**Comment by little-alei** [comment]
> 可以提供一个最小化 `demo` 或 [playground](https://varlet.gitee.io/varlet-ui-playground/)

https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8dmFyLWNvbGxhcHNlIHYtbW9kZWw9XCJ2YWx1ZVwiIEBjaGFuZ2U9XCJjaGFuZ2VIYW5kbGVcIiA6b2Zmc2V0PVwiZmFsc2VcIj5cblx0XHQ8dmFyLWNvbGxhcHNlLWl0ZW0gbmFtZT1cIjFcIj5cblx0XHRcdDx0ZW1wbGF0ZSAjdGl0bGU+XG5cdFx0XHRcdDx2YXItaWNvbiBuYW1lPVwicGxheS1jaXJjbGUtb3V0bGluZVwiIC8+XG5cdFx0XHRcdOi/kOihjOS4reeahOmhueebrlxuXHRcdFx0PC90ZW1wbGF0ZT5cblx0XHRcdDxkaXYgc3R5bGU9XCJwYWRkaW5nOiAycHggMTBweFwiIHYtaWY9XCJydW5uaW5nLmxlbmd0aCAhPSAwXCI+XG5cdFx0XHRcdDxoNSB2LWZvcj1cImluZm8gaW4gcnVubmluZ1wiIDppbmZvPVwiaW5mb1wiIDprZXk9XCJpbmZvLmlkXCI+e3sgaW5mby5uYW1lIH19PC9oNT5cblx0XHRcdDwvZGl2PlxuXHRcdFx0PGRpdiBjbGFzcz1cImVtcHR5XCIgdi1pZj1cInJ1bm5pbmcubGVuZ3RoID09IDBcIj5cblx0XHRcdFx0PGltZyBzcmM9XCJodHRwczovL2ltZy55emNkbi5jbi92YW50L2N1c3RvbS1lbXB0eS1pbWFnZS5wbmdcIiBhbHQ9XCJcIiAvPlxuXHRcdFx0XHQ8cD7ku4DkuYjkuZ/msqHmnInlk6Y8L3A+XG5cdFx0XHQ8L2Rpdj5cblx0XHQ8L3Zhci1jb2xsYXBzZS1pdGVtPlxuXHRcdDx2YXItY29sbGFwc2UtaXRlbSBuYW1lPVwiMlwiPlxuXHRcdFx0PHRlbXBsYXRlICN0aXRsZT5cblx0XHRcdFx0PHZhci1pY29uIG5hbWU9XCJiZWxsXCIgLz5cblx0XHRcdFx05Lu75YqhXG5cdFx0XHQ8L3RlbXBsYXRlPlxuXHRcdFx0PGRpdiBzdHlsZT1cInBhZGRpbmc6IDJweCAxMHB4XCIgdi1pZj1cInRhc2subGVuZ3RoICE9IDBcIj5cblx0XHRcdFx0PGg0IHYtZm9yPVwiaW5mbyBpbiBydW5uaW5nXCIgOmluZm89XCJpbmZvXCIgOmtleT1cImluZm8uaWRcIj57eyBpbmZvLm5hbWUgfX08L2g0PlxuXHRcdFx0PC9kaXY+XG5cdFx0XHQ8ZGl2IGNsYXNzPVwiZW1wdHlcIiB2LWlmPVwidGFzay5sZW5ndGggPT0gMFwiPlxuXHRcdFx0XHQ8aW1nIHNyYz1cImh0dHBzOi8vaW1nLnl6Y2RuLmNuL3ZhbnQvY3VzdG9tLWVtcHR5LWltYWdlLnBuZ1wiIGFsdD1cIlwiIC8+XG5cdFx0XHRcdDxwPuS7gOS5iOS5n+ayoeacieWTpjwvcD5cblx0XHRcdDwvZGl2PlxuXHRcdDwvdmFyLWNvbGxhcHNlLWl0ZW0+XG5cdDwvdmFyLWNvbGxhcHNlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcbmludGVyZmFjZSBUYXNrIHtcblx0aWQ6IG51bWJlcjtcblx0bmFtZTogc3RyaW5nO1xufVxuY29uc3QgdmFsdWUgPSByZWYoW10pO1xuY29uc3QgcnVubmluZyA9IHJlZjxUYXNrW10+KFtdKTtcbmNvbnN0IHRhc2sgPSByZWY8VGFza1tdPihbXSk7XG5mdW5jdGlvbiBjaGFuZ2VIYW5kbGUodmFsOiBzdHJpbmdbXSkge1xuXHRpZiAodmFsLmluY2x1ZGVzKFwiMVwiKSkge1xuXHRcdHJ1bm5pbmcudmFsdWUucHVzaCh7XG5cdFx0XHRpZDogcnVubmluZy52YWx1ZS5sZW5ndGggKyAxLFxuXHRcdFx0bmFtZTogYHRlc3Qke3J1bm5pbmcudmFsdWUubGVuZ3RofWAsXG5cdFx0fSk7XG5cdH1cbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5lbXB0eSB7XG5cdGRpc3BsYXk6IGZsZXg7XG5cdGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG5cdGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG4uZW1wdHkgaW1nIHtcblx0d2lkdGg6IDEwMHB4O1xuXHRoZWlnaHQ6IDEwMHB4O1xufVxuPC9zdHlsZT5cbiIsIlBsYXlncm91bmQudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiLi92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbkNvbnRleHQudG91Y2htb3ZlRm9yYmlkID0gZmFsc2VcblxuYXdhaXQgYXBwZW5kU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gaW5zdGFsbFZhcmxldFVJKCkge1xuICBjb25zdCB7IHBhcmVudCB9ID0gd2luZG93XG5cbiAgY29uc3Qgc3R5bGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzdHlsZScpXG4gIHN0eWxlLmlubmVySFRNTCA9IGBcbiAgICBib2R5IHtcbiAgICAgIG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgICAgcGFkZGluZzogMTZweDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIGNvbG9yOiB2YXIoLS1jb2xvci10ZXh0KTtcbiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWNvbG9yLWJvZHkpO1xuICAgIH1cblxuICAgICo6Oi13ZWJraXQtc2Nyb2xsYmFyIHtcbiAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgfVxuICBgXG4gIGRvY3VtZW50LmhlYWQuYXBwZW5kQ2hpbGQoc3R5bGUpXG5cbiAgaWYgKHBhcmVudC5kb2N1bWVudC5kb2N1bWVudEVsZW1lbnQuY2xhc3NMaXN0LmNvbnRhaW5zKCdkYXJrJykpIHtcbiAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKFZhcmxldFVJLlRoZW1lcy5kYXJrKVxuICB9XG5cbiAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ21lc3NhZ2UnLCAoeyBkYXRhIH0pID0+IHtcbiAgICBpZiAoZGF0YS5hY3Rpb24gPT09ICd0aGVtZS1jaGFuZ2UnKSB7XG4gICAgICBWYXJsZXRVSS5TdHlsZVByb3ZpZGVyKGRhdGEudmFsdWUgPT09ICdkYXJrJyA/IFZhcmxldFVJLlRoZW1lcy5kYXJrIDogbnVsbClcbiAgICB9XG4gIH0pXG5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoVmFybGV0VUkpXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBhcHBlbmRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnLi92YXJsZXQuY3NzJ1xuICAgIGxpbmsub25sb2FkID0gcmVzb2x2ZVxuICAgIGxpbmsub25lcnJvciA9IHJlamVjdFxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQobGluaylcbiAgfSlcbn1cbiJ9

**Comment by haoziqaq** [comment]
好的，我们来定位一下问题

**Comment by little-alei** [comment]
> 好的，我们来定位一下问题
谢谢，辛苦了。好像链接太长了，不支持markdown的link格式显示，下面是playground链接。这个动画的异常在pc的浏览器中没有出现，只出现在安卓的浏览器中

**Comment by haoziqaq** [comment]
我在安卓的浏览器中没有复现，目前怀疑是一个比较小范围的兼容性问题，方便进微信群进一步定位问题吗？

**Comment by haoziqaq** [comment]
尝试升级 `2.9.3-alpha.1679304010895` 我给动画加了一次 `tick`，或许能解决问题，如果问题没被解决，可能需要你配合提供更多信息。最好进下群～

**Comment by little-alei** [comment]
> 尝试升级 `2.9.3-alpha.1679304010895` 我给动画加了一次 `tick`，或许能解决问题，如果问题没被解决，可能需要你配合提供更多信息。最好进下群～

尝试了一下，问题有改善，但还没有被没完全解决。当第一次展开时只有一个item，会出现一个比较大的高度，然后又收回去

**Comment by haoziqaq** [comment]
提供一下操作系统信息、设备信息、浏览器信息，听您描述应该就是动画帧的问题，一般出现这种情况有可能是帧率过低，或是其他原因。

**Comment by little-alei** [comment]
> 提供一下操作系统信息、设备信息、浏览器信息，听您描述应该就是动画帧的问题，一般出现这种情况有可能是帧率过低，或是其他原因。

有两台设备，安卓11和13都出现一样的问题，分别时60hz和120hz，应该不是帧率问题。webview版本分别92和110

**Comment by little-alei** [comment]
我在qq里打开链接也是一样的表现，qq用的时腾讯x5内核，不是谷歌自带的webview。怎么进群

**Comment by haoziqaq** [comment]
readme 中有二维码
