### ISSUE TITLE
Elevation related component modification

### ISSUE THREAD

**Issue by tiny-dust** [varletjs/varlet#923]
add property `elevation`, optional values is `true`、`false`、`0-24`

Components
- [x] Collapse -- @BeADre 
- [x] Button  -- @dyggod 
- [x] Fab     -- @dyggod
- [x] Paper   -- @dyggod 
- [x] Card    -- @dyggod 
- [x] Table -- @dyggod 
- [x] Tabs -- @dyggod 
- [x] AppBar -- @dyggod 
- [x] Pagination `while simple = false` -- @BeADre 
- [x] Menu  -- @haoziqaq 
- [x] Backtop -- @BeADre 
- [x] DatePicker `format elevation and add button-elevation` -- @BeADre 
- [x] TimePicker -- @BeADre 
- [x] Uploader -- @forestxieCode 
- [x] Counter -- @forestxieCode 

The behavior is as follows:

1. All new `elevation` properties default to `true`
2. The original `elevation` is `number type` and the default value change to `true`
3. The original `elevation` is `false` and the default value is still `false`
 
Elevation prop declare e.g.

```javascript
const props = {
  elevation: {
    // Boolean must be first
    type: [Boolean, String, Number], 
    default: true
  }
}
```

**Comment by BeADre** [comment]
认领: Collapse、Pagination、Backtop、DatePicker

**Comment by dyggod** [comment]
认领：Table、Tabs、AppBar
