### ISSUE TITLE
picker 默认选中项

### ISSUE THREAD

**Issue by Jaggerchen** [varletjs/varlet#960]
![image](https://user-images.githubusercontent.com/37999996/231400733-f24b2636-8845-4af5-9d8d-0b8d405ec8f2.png)
我想问一下，这个picker,怎么设置默认选中项，我这样设置，无论是数组还是数字都不能索引到选择器的某一个值

**Comment by haoziqaq** [comment]
columns 的类型是 
![image](https://user-images.githubusercontent.com/24223652/231408682-386929de-4c92-4263-8bd1-2cb518cfab14.png)

**Comment by Jaggerchen** [comment]
那现在怎么设置默认值呢

**Comment by haoziqaq** [comment]
[playground](https://varlet.gitee.io/varlet-ui-playground/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IFBpY2tlciB9IGZyb20gJ0B2YXJsZXQvdWknXG5cbmNvbnN0IHRleHRzID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMjAgfSkubWFwKChfLCBpbmRleCkgPT4gaW5kZXgpXG5cbmFzeW5jIGZ1bmN0aW9uIHBpY2tlcigpIHtcbiAgYXdhaXQgUGlja2VyKHtcbiAgICBjb2x1bW5zOiBbXG4gICAgICB7XG4gICAgICAgIHRleHRzLFxuICAgICAgICBpbml0aWFsSW5kZXg6IDEwXG4gICAgICB9XG4gICAgXVxuICB9KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHZhci1idXR0b24gdHlwZT1cInByaW1hcnlcIiBibG9jayBAY2xpY2s9XCJwaWNrZXJcIj7ljZXliJfpgInmi6k8L3Zhci1idXR0b24+XG48L3RlbXBsYXRlPlxuXG4iLCJQbGF5Z3JvdW5kLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IGluc3RhbGxWYXJsZXRVSSB9IGZyb20gJy4vdmFybGV0LXJlcGwtcGx1Z2luLmpzJ1xuXG5pbnN0YWxsVmFybGV0VUkoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjI5L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2YXJsZXQvdWlcIjogXCIuL3ZhcmxldC5lc20uanNcIixcbiAgICBcIkB2YXJsZXQvdG91Y2gtZW11bGF0b3JcIjogXCIuL3ZhcmxldC10b3VjaC1lbXVsYXRvci5qc1wiLFxuICAgIFwiQHZhcmxldC91aS9qc29uL2FyZWEuanNvblwiOiBcIi4vdmFybGV0LWFyZWEuanNcIlxuICB9XG59IiwidmFybGV0LXJlcGwtcGx1Z2luLmpzIjoiaW1wb3J0IFZhcmxldFVJLCB7IENvbnRleHQgfSBmcm9tICdAdmFybGV0L3VpJ1xuaW1wb3J0ICdAdmFybGV0L3RvdWNoLWVtdWxhdG9yJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5hd2FpdCBhcHBlbmRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBpbnN0YWxsVmFybGV0VUkoKSB7XG4gIGNvbnN0IHsgcGFyZW50IH0gPSB3aW5kb3dcblxuICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJylcbiAgc3R5bGUuaW5uZXJIVE1MID0gYFxuICAgIGJvZHkge1xuICAgICAgbWluLWhlaWdodDogMTAwdmg7XG4gICAgICBwYWRkaW5nOiAxNnB4O1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgY29sb3I6IHZhcigtLWNvbG9yLXRleHQpO1xuICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tY29sb3ItYm9keSk7XG4gICAgfVxuXG4gICAgKjo6LXdlYmtpdC1zY3JvbGxiYXIge1xuICAgICAgZGlzcGxheTogbm9uZTtcbiAgICB9XG4gIGBcbiAgZG9jdW1lbnQuaGVhZC5hcHBlbmRDaGlsZChzdHlsZSlcblxuICBpZiAocGFyZW50LmRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuY29udGFpbnMoJ2RhcmsnKSkge1xuICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoVmFybGV0VUkuVGhlbWVzLmRhcmspXG4gIH1cblxuICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignbWVzc2FnZScsICh7IGRhdGEgfSkgPT4ge1xuICAgIGlmIChkYXRhLmFjdGlvbiA9PT0gJ3RoZW1lLWNoYW5nZScpIHtcbiAgICAgIFZhcmxldFVJLlN0eWxlUHJvdmlkZXIoZGF0YS52YWx1ZSA9PT0gJ2RhcmsnID8gVmFybGV0VUkuVGhlbWVzLmRhcmsgOiBudWxsKVxuICAgIH1cbiAgfSlcblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShWYXJsZXRVSSlcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGFwcGVuZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICcuL3ZhcmxldC5jc3MnXG4gICAgbGluay5vbmxvYWQgPSByZXNvbHZlXG4gICAgbGluay5vbmVycm9yID0gcmVqZWN0XG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsaW5rKVxuICB9KVxufVxuIn0=)

**Comment by Jaggerchen** [comment]
谢谢，有点生涩api,那遇到年月日这种 怎么来设置呢

**Comment by Jaggerchen** [comment]
另外在线调试 这里
![image](https://user-images.githubusercontent.com/37999996/231411150-b7386216-c894-4630-829c-a4e43c206ac1.png)
报样式加载的错，导致没办法预览

**Comment by haoziqaq** [comment]
抱歉这么晚回复你，年月日可以优先选择日期选择器，如果一定要用 picker 实现的话，参考 [playground](https://varlet.gitee.io/varlet-ui-playground/?initialTheme=light#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IFBpY2tlciB9IGZyb20gJ0B2YXJsZXQvdWknXG5cbmNvbnN0IGdlbkNvdW50cyA9IGxlbmd0aCA9PiBBcnJheS5mcm9tKHsgbGVuZ3RoIH0sIChfLCBpbmRleCkgPT4gaW5kZXggKyAxKVxuY29uc3QgbW9udGhzID0gZ2VuQ291bnRzKDEyKVxuY29uc3QgbGVhcFllYXJGZWJydWFyeURhdGVzID0gZ2VuQ291bnRzKDI5KVxuY29uc3QgZmVicnVhcnlEYXRlcyA9IGdlbkNvdW50cygyOClcbmNvbnN0IG9kZE1vbnRoRGF0ZXMgPSBnZW5Db3VudHMoMzEpXG5jb25zdCBldmVuTW9udGhEYXRlcyA9IGdlbkNvdW50cygzMClcbmNvbnN0IGNvbHVtbnMgPSBnZW5Db2x1bW5zKDE5NzAsIDIxMDApXG5cbmZ1bmN0aW9uIGlzT2RkTW9udGgobW9udGgpIHsgXG4gIHJldHVybiBbMSwgMywgNSwgNywgOCwgMTAsIDEyXS5pbmNsdWRlcyhtb250aCkgXG59XG5cbmZ1bmN0aW9uIGlzTGVhcFllYXIoeWVhcikge1xuICByZXR1cm4gKHllYXIgJSA0ID09PSAwICYmIHllYXIgJSAxMDAgIT09IDApIHx8IHllYXIgJSA0MDAgPT09IDBcbn1cblxuZnVuY3Rpb24gZ2VuRGF0ZXMoeWVhciwgbW9udGgpIHtcbiAgaWYgKGlzTGVhcFllYXIoeWVhcikgJiYgbW9udGggPT09IDIpIHtcbiAgICByZXR1cm4gbGVhcFllYXJGZWJydWFyeURhdGVzXG4gIH1cblxuICBpZiAoIWlzTGVhcFllYXIoeWVhcikgJiYgbW9udGggPT09IDIpIHtcbiAgICByZXR1cm4gZmVicnVhcnlEYXRlc1xuICB9XG5cbiAgaWYgKGlzT2RkTW9udGgobW9udGgpKSB7XG4gICAgcmV0dXJuIG9kZE1vbnRoRGF0ZXNcbiAgfVxuXG4gIHJldHVybiBldmVuTW9udGhEYXRlc1xufVxuXG5mdW5jdGlvbiBnZW5Db2x1bW5zKHN0YXJ0WWVhciwgZW5kWWVhcikge1xuICBjb25zdCBjb2x1bW5zID0gW11cbiAgXG4gIGZvciAobGV0IHllYXIgPSBzdGFydFllYXI7IHllYXIgPCBlbmRZZWFyOyB5ZWFyKyspIHtcbiAgICBjb2x1bW5zLnB1c2goe1xuICAgICAgdGV4dDogeWVhcixcbiAgICAgIGNoaWxkcmVuOiBtb250aHMubWFwKChtb250aCkgPT4ge1xuICAgICAgICByZXR1cm4ge1xuICAgICAgICAgIHRleHQ6IG1vbnRoLFxuICAgICAgICAgIGNoaWxkcmVuOiBnZW5EYXRlcyh5ZWFyLCBtb250aCkubWFwKGRhdGUgPT4gKHsgdGV4dDogZGF0ZSB9KSlcbiAgICAgICAgfVxuICAgICAgfSlcbiAgICB9KVxuICB9XG5cbiAgcmV0dXJuIGNvbHVtbnNcbn1cblxuZnVuY3Rpb24gdGV4dEZvcm1hdHRlcih0ZXh0LCBjb2x1bW5JbmRleCkge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDApIHJldHVybiBgJHt0ZXh0feW5tGBcbiAgZWxzZSBpZiAoY29sdW1uSW5kZXggPT09IDEpIHJldHVybiBgJHt0ZXh0feaciGBcbiAgZWxzZSBpZiAoY29sdW1uSW5kZXggPT09IDIpIHJldHVybiBgJHt0ZXh0feaXpWBcbn1cblxuYXN5bmMgZnVuY3Rpb24gcGlja2VyKCkge1xuICBjb25zdCB7IHN0YXRlLCB0ZXh0cywgaW5kZXhlcyB9ID0gYXdhaXQgUGlja2VyKHtcbiAgICBjYXNjYWRlOiB0cnVlLFxuICAgIGNvbHVtbnMsXG4gICAgdGV4dEZvcm1hdHRlcixcbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx2YXItYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgYmxvY2sgQGNsaWNrPVwicGlja2VyXCI+5paH5pys5qC85byP5YyWPC92YXItYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsIlBsYXlncm91bmQudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgaW5zdGFsbFZhcmxldFVJIH0gZnJvbSAnLi92YXJsZXQtcmVwbC1wbHVnaW4uanMnXG5cbmluc3RhbGxWYXJsZXRVSSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMjkvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZhcmxldC91aVwiOiBcIi4vdmFybGV0LmVzbS5qc1wiLFxuICAgIFwiQHZhcmxldC90b3VjaC1lbXVsYXRvclwiOiBcIi4vdmFybGV0LXRvdWNoLWVtdWxhdG9yLmpzXCIsXG4gICAgXCJAdmFybGV0L3VpL2pzb24vYXJlYS5qc29uXCI6IFwiLi92YXJsZXQtYXJlYS5qc1wiXG4gIH1cbn0iLCJ2YXJsZXQtcmVwbC1wbHVnaW4uanMiOiJpbXBvcnQgVmFybGV0VUksIHsgQ29udGV4dCB9IGZyb20gJ0B2YXJsZXQvdWknXG5pbXBvcnQgJ0B2YXJsZXQvdG91Y2gtZW11bGF0b3InXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmF3YWl0IGFwcGVuZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIGluc3RhbGxWYXJsZXRVSSgpIHtcbiAgY29uc3QgeyBwYXJlbnQgfSA9IHdpbmRvd1xuXG4gIGNvbnN0IHN0eWxlID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3R5bGUnKVxuICBzdHlsZS5pbm5lckhUTUwgPSBgXG4gICAgYm9keSB7XG4gICAgICBtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICAgIHBhZGRpbmc6IDE2cHg7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICBjb2xvcjogdmFyKC0tY29sb3ItdGV4dCk7XG4gICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1jb2xvci1ib2R5KTtcbiAgICB9XG5cbiAgICAqOjotd2Via2l0LXNjcm9sbGJhciB7XG4gICAgICBkaXNwbGF5OiBub25lO1xuICAgIH1cbiAgYFxuICBkb2N1bWVudC5oZWFkLmFwcGVuZENoaWxkKHN0eWxlKVxuXG4gIGlmIChwYXJlbnQuZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5jb250YWlucygnZGFyaycpKSB7XG4gICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihWYXJsZXRVSS5UaGVtZXMuZGFyaylcbiAgfVxuXG4gIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdtZXNzYWdlJywgKHsgZGF0YSB9KSA9PiB7XG4gICAgaWYgKGRhdGEuYWN0aW9uID09PSAndGhlbWUtY2hhbmdlJykge1xuICAgICAgVmFybGV0VUkuU3R5bGVQcm92aWRlcihkYXRhLnZhbHVlID09PSAnZGFyaycgPyBWYXJsZXRVSS5UaGVtZXMuZGFyayA6IG51bGwpXG4gICAgfVxuICB9KVxuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKFZhcmxldFVJKVxufVxuXG5leHBvcnQgZnVuY3Rpb24gYXBwZW5kU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJy4vdmFybGV0LmNzcydcbiAgICBsaW5rLm9ubG9hZCA9IHJlc29sdmVcbiAgICBsaW5rLm9uZXJyb3IgPSByZWplY3RcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGxpbmspXG4gIH0pXG59XG4ifQ==)

**Comment by haoziqaq** [comment]
> 另外在线调试 这里 ![image](https://user-images.githubusercontent.com/37999996/231411150-b7386216-c894-4630-829c-a4e43c206ac1.png) 报样式加载的错，导致没办法预览

可以尝试清理一下缓存，我这边使用 chorme 浏览器是没问题的～
