### ISSUE TITLE
Updating copyright year

### ISSUE THREAD

**Issue by Brian-Nduhiu** [varletjs/varlet#977]
# Feature request 🚀
Copyright year at the footer of https://varlet.gitee.io/varlet-ui/#/en-US/index is still 2022
![image](https://user-images.githubusercontent.com/43300544/233352506-146569b9-ae64-4883-a150-981ddd143874.png)

### Expected:
Copyright © 2023 varletjs member and varlet contributors.
- No breaking changes

### Examples:

```js

```

**Comment by haoziqaq** [comment]
The time described by copyright is the time when it was first declared, so it does not need to be updated.
Thank you for your care.
