### ISSUE TITLE
输入框自动完成功能

### ISSUE THREAD

**Issue by gaoting** [varletjs/varlet#980]
参考功能：  https://www.antdv.com/components/auto-complete-cn

**Comment by haoziqaq** [comment]
下一个 minor 版本会发布 input select 的新模式，auto-complete 需要延后一段时间等新模式稳定之后再进行开发，先记录到 project 里吧。

**Comment by haoziqaq** [comment]
@tiny-dust

**Comment by tiny-dust** [comment]
> 

新任务已建

**Comment by tiny-dust** [comment]
> @tiny-dust

新任务已建
