### ISSUE TITLE
Routing function is added to the bottom navigation bar

### ISSUE THREAD

**Issue by AnyFork** [varletjs/varlet#987]
# Feature request 🚀
Routing function is added to the bottom navigation bar
### Expected:

- No breaking changes

### Examples:

```js

```

**Comment by haoziqaq** [comment]
Yes, I think we need it. Would you like to do it for us ?

**Comment by AnyFork** [comment]
I think I can give it a try
&nbsp;


小紫念沁
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [varletjs/varlet] Routing function is added to the bottom navigation bar (Issue #987)





 
Yes, I think we need it. Would you like to do it for us ?

**Comment by haoziqaq** [comment]
thanks for your help. 🙏
