### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by AnyFork** [varletjs/varlet#992]
# Bug report 🐞
使用tabs选项卡时，出现window is not defined错误，tabs不支持SSR吗？

**Comment by haoziqaq** [comment]
最新的alpha版本没有这个问题，可以尝试升级

**Comment by AnyFork** [comment]
奇怪了，前天晚上我还下载https://github.com/varletjs/varlet-install-example ，运行了nuxt例子，当时tabs确实可以SSR。alpha版本怎么下载，目前用的2.9.6

**Comment by tiny-dust** [comment]
> 奇怪了，前天晚上我还下载https://github.com/varletjs/varlet-install-example ，运行了nuxt例子，当时tabs确实可以SSR。alpha版本怎么下载，目前用的2.9.6
我们最近在对`nuxt`进行全面的升级，所以建议直接安装`alpha`版本
```shell
pnpm install @varlet/ui@alpha
```

**Comment by AnyFork** [comment]
谢谢，测试了一下，升级alpha版本确实正常了。
