### ISSUE TITLE
是否存在van-grid组件

### ISSUE THREAD

**Issue by AnyFork** [varletjs/varlet#993]
# Bug report 🐞
看文档不存在van-grid组件，自定义van-gird组件发现类型文件中存在van-grid的类型导出声明，如下图：
![image](https://user-images.githubusercontent.com/49142023/233838659-76404ad6-e5f0-490f-bb32-c6f2720f766d.png)

**Comment by haoziqaq** [comment]
这个是插件根据名称自动生成的， 我们是没有这个组件的。

**Comment by haoziqaq** [comment]
unplugin-vue-components 会匹配你模板里用到的所有以 var- 开头的组件，并尝试帮你自动引入并生成类型声明。

**Comment by haoziqaq** [comment]
但是他不会去确认包里是否真的存在这个组件。

**Comment by AnyFork** [comment]
好的
