### ISSUE TITLE
时间选择器点击报错

### ISSUE THREAD

**Issue by phojz** [varletjs/varlet#998]
# Bug report 🐞
你好，我试了下，我这个有个报错。
点击时间选择器报错如下 chooseDay is not defined

## Version & Environment
版本号：
 "@varlet/ui": "^2.10.0",
   "vue": "3.2.47",
## Expectation
点击可用
## Actual results (or E
![WX20230426-090943@2x](https://user-images.githubusercontent.com/20762479/234440511-014d6cba-8324-4ac0-addd-00e3c1821e80.png)
rrors)

**Comment by BeADre** [comment]
能给个复现链接吗

**Comment by AnyFork** [comment]
> 能给个复现链接吗

我也遇到相同的问题，"@varlet/ui": "^2.10.0",
```js
<script setup>
import { ref } from 'vue'

const date = ref('2021-04-08')
</script>

<template>
  <var-date-picker v-model="date" />
</template>
```
就官网这个简单例子报错，错误和上面错误一样。

**Comment by BeADre** [comment]
发了个alpha版本  `pnpm install @varlet/ui@2.10.1-alpha.1682612292220`安装
